// =============================================================
// MonsterQuest — game data: types, moves, species, items
// =============================================================
"use strict";

// ---- Type chart -------------------------------------------------
// TYPE_CHART[attacking][defending] = multiplier (missing = 1)
const TYPE_CHART = {
  Normal:   { Ghost: 0, Rock: 0.5 },
  Fire:     { Grass: 2, Bug: 2, Fire: 0.5, Water: 0.5, Rock: 0.5 },
  Water:    { Fire: 2, Rock: 2, Ground: 2, Water: 0.5, Grass: 0.5 },
  Grass:    { Water: 2, Rock: 2, Ground: 2, Fire: 0.5, Grass: 0.5, Bug: 0.5, Poison: 0.5, Flying: 0.5 },
  Electric: { Water: 2, Flying: 2, Grass: 0.5, Electric: 0.5, Ground: 0 },
  Flying:   { Grass: 2, Bug: 2, Electric: 0.5, Rock: 0.5 },
  Bug:      { Grass: 2, Psychic: 2, Fire: 0.5, Flying: 0.5, Poison: 0.5, Ghost: 0.5 },
  Poison:   { Grass: 2, Poison: 0.5, Rock: 0.5, Ground: 0.5, Ghost: 0.5 },
  Rock:     { Fire: 2, Flying: 2, Bug: 2, Ground: 0.5 },
  Ground:   { Fire: 2, Electric: 2, Poison: 2, Rock: 2, Flying: 0, Grass: 0.5, Bug: 0.5 },
  Psychic:  { Poison: 2, Psychic: 0.5 },
  Ghost:    { Ghost: 2, Psychic: 2, Normal: 0 },
};

const TYPE_COLORS = {
  Normal: "#a8a878", Fire: "#f08030", Water: "#6890f0", Grass: "#78c850",
  Electric: "#f8d030", Flying: "#a890f0", Bug: "#a8b820", Poison: "#a040a0",
  Rock: "#b8a038", Ground: "#e0c068", Psychic: "#f85888", Ghost: "#705898",
};

function typeMultiplier(moveType, defTypes) {
  let m = 1;
  for (const t of defTypes) {
    const row = TYPE_CHART[moveType];
    if (row && row[t] !== undefined) m *= row[t];
  }
  return m;
}

// ---- Moves ------------------------------------------------------
// kind: "phys" | "spec" | "status"
// effect: { status:"psn"|"par"|"brn"|"slp", chance } applied to target
// stat:   { who:"self"|"foe", stat:"atk"|"def"|"spd", delta }
const MOVES = {
  tackle:       { name: "Tackle",       type: "Normal",   kind: "phys", power: 35, acc: 95,  pp: 35 },
  scratch:      { name: "Scratch",      type: "Normal",   kind: "phys", power: 40, acc: 100, pp: 35 },
  quickattack:  { name: "Quick Attack", type: "Normal",   kind: "phys", power: 40, acc: 100, pp: 30, priority: 1 },
  bite:         { name: "Bite",         type: "Normal",   kind: "phys", power: 60, acc: 100, pp: 25 },
  hyperfang:    { name: "Hyper Fang",   type: "Normal",   kind: "phys", power: 80, acc: 90,  pp: 15 },
  growl:        { name: "Growl",        type: "Normal",   kind: "status", acc: 100, pp: 40, stat: { who: "foe", stat: "atk", delta: -1 } },
  tailwhip:     { name: "Tail Whip",    type: "Normal",   kind: "status", acc: 100, pp: 30, stat: { who: "foe", stat: "def", delta: -1 } },
  sharpen:      { name: "Sharpen",      type: "Normal",   kind: "status", acc: 999, pp: 30, stat: { who: "self", stat: "atk", delta: 1 } },
  harden:       { name: "Harden",       type: "Normal",   kind: "status", acc: 999, pp: 30, stat: { who: "self", stat: "def", delta: 1 } },
  vinewhip:     { name: "Vine Whip",    type: "Grass",    kind: "spec", power: 45, acc: 100, pp: 25 },
  razorleaf:    { name: "Razor Leaf",   type: "Grass",    kind: "spec", power: 55, acc: 95,  pp: 25, highCrit: true },
  sleeppowder:  { name: "Sleep Powder", type: "Grass",    kind: "status", acc: 75, pp: 15, effect: { status: "slp", chance: 100 } },
  ember:        { name: "Ember",        type: "Fire",     kind: "spec", power: 40, acc: 100, pp: 25, effect: { status: "brn", chance: 10 } },
  flameburst:   { name: "Flame Burst",  type: "Fire",     kind: "spec", power: 70, acc: 100, pp: 15, effect: { status: "brn", chance: 10 } },
  watergun:     { name: "Water Gun",    type: "Water",    kind: "spec", power: 40, acc: 100, pp: 25 },
  bubblebeam:   { name: "Bubble Beam",  type: "Water",    kind: "spec", power: 65, acc: 100, pp: 20 },
  thundershock: { name: "Thundershock", type: "Electric", kind: "spec", power: 40, acc: 100, pp: 30, effect: { status: "par", chance: 10 } },
  spark:        { name: "Spark",        type: "Electric", kind: "phys", power: 65, acc: 100, pp: 20, effect: { status: "par", chance: 20 } },
  thunderwave:  { name: "Thunder Wave", type: "Electric", kind: "status", acc: 100, pp: 20, effect: { status: "par", chance: 100 } },
  gust:         { name: "Gust",         type: "Flying",   kind: "spec", power: 40, acc: 100, pp: 35 },
  peck:         { name: "Peck",         type: "Flying",   kind: "phys", power: 35, acc: 100, pp: 35 },
  wingattack:   { name: "Wing Attack",  type: "Flying",   kind: "phys", power: 60, acc: 100, pp: 30 },
  bugbite:      { name: "Bug Bite",     type: "Bug",      kind: "phys", power: 60, acc: 100, pp: 20 },
  stringshot:   { name: "String Shot",  type: "Bug",      kind: "status", acc: 95, pp: 40, stat: { who: "foe", stat: "spd", delta: -1 } },
  poisonsting:  { name: "Poison Sting", type: "Poison",   kind: "phys", power: 15, acc: 100, pp: 35, effect: { status: "psn", chance: 30 } },
  sludge:       { name: "Sludge",       type: "Poison",   kind: "spec", power: 65, acc: 100, pp: 20, effect: { status: "psn", chance: 30 } },
  rockthrow:    { name: "Rock Throw",   type: "Rock",     kind: "phys", power: 50, acc: 90,  pp: 15 },
  rockslide:    { name: "Rock Slide",   type: "Rock",     kind: "phys", power: 75, acc: 90,  pp: 10 },
  mudshot:      { name: "Mud Shot",     type: "Ground",   kind: "spec", power: 55, acc: 95,  pp: 15 },
  confusion:    { name: "Confusion",    type: "Psychic",  kind: "spec", power: 50, acc: 100, pp: 25 },
  psybeam:      { name: "Psybeam",      type: "Psychic",  kind: "spec", power: 65, acc: 100, pp: 20 },
  lick:         { name: "Lick",         type: "Ghost",    kind: "phys", power: 30, acc: 100, pp: 30, effect: { status: "par", chance: 30 } },
  shadebolt:    { name: "Shade Bolt",   type: "Ghost",    kind: "spec", power: 60, acc: 100, pp: 20 },
};

// ---- Species ----------------------------------------------------
// base: [hp, atk, def, spd, spc]
// learnset: [level, moveId] — level 1 moves are the starting kit
// art: 16 rows of chars; "." transparent, chars map into pal
//   common chars: o outline, k pupil, w eye-white
const SPECIES = {
  sproutle: {
    name: "SPROUTLE", types: ["Grass"], base: [45, 49, 49, 45, 55],
    catchRate: 45, baseExp: 64, evolvesTo: "bloomurk", evolveLevel: 16,
    learnset: [[1, "tackle"], [1, "growl"], [7, "vinewhip"], [13, "sleeppowder"], [20, "razorleaf"]],
    pal: { o: "#1c3a1c", A: "#63b34f", B: "#2e7d32", C: "#a5d6a7", w: "#ffffff", k: "#1a1a1a", m: "#c62828" },
    art: [
      "......oBB.......",
      ".....oBBBBo.....",
      "....oBBBBBBo....",
      ".....oBBBo......",
      ".......o........",
      "....ooAAAoo.....",
      "...oAAAAAAAo....",
      "..oAAwkAAwkAo...",
      "..oAAwwAAwwAo...",
      "..oAAAAAAAAAo...",
      "..oAAAmmmAAAo...",
      "..oCAAAAAAACo...",
      "...oAAAAAAAo....",
      "....ooAAAoo.....",
      "...oAo...oAo....",
      "................",
    ],
  },
  bloomurk: {
    name: "BLOOMURK", types: ["Grass"], base: [60, 62, 63, 60, 80],
    catchRate: 45, baseExp: 141,
    learnset: [[1, "tackle"], [1, "growl"], [7, "vinewhip"], [13, "sleeppowder"], [22, "razorleaf"]],
    pal: { o: "#1c3a1c", A: "#4f9d3f", B: "#2e6d22", C: "#e91e8c", w: "#ffffff", k: "#1a1a1a", m: "#7b1fa2" },
    art: [
      "....C..oB..C....",
      "...CCCoBBoCCC...",
      "....CoBBBBoC....",
      "...oBBBBBBBBo...",
      "....oBBBBBBo....",
      "...ooAAAAAAoo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAAAmmmmmAAAAo.",
      ".oAAAAAAAAAAAAo.",
      "..oAAAAAAAAAAo..",
      "...oAAoooAAo....",
      "..oAAo...oAAo...",
      "................",
    ],
  },
  cindercub: {
    name: "CINDERCUB", types: ["Fire"], base: [44, 52, 43, 55, 50],
    catchRate: 45, baseExp: 65, evolvesTo: "pyroursa", evolveLevel: 16,
    learnset: [[1, "scratch"], [1, "growl"], [7, "ember"], [13, "bite"], [20, "flameburst"]],
    pal: { o: "#4a1a08", A: "#e8813c", B: "#f4b942", C: "#c74a1e", w: "#ffffff", k: "#1a1a1a", m: "#7a2d10" },
    art: [
      "......B.........",
      ".....BBB..B.....",
      "..oo.BCB.BBB....",
      ".oAAo.C.oCBo....",
      ".oAAAooooAAo....",
      "..oAAAAAAAAoo...",
      ".oAAwkAAAwkAAo..",
      ".oAAwwAAAwwAAo..",
      ".oAABBAAABBAAo..",
      ".oAAAAmmmAAAAo..",
      "..oAAAAAAAAAo...",
      "..oAABBBBBAAo...",
      "..oAABBBBBAAo...",
      "...oAAAAAAAo....",
      "..oAAo...oAAo...",
      "................",
    ],
  },
  pyroursa: {
    name: "PYROURSA", types: ["Fire"], base: [58, 64, 58, 70, 65],
    catchRate: 45, baseExp: 142,
    learnset: [[1, "scratch"], [1, "growl"], [7, "ember"], [13, "bite"], [22, "flameburst"]],
    pal: { o: "#3a1204", A: "#d4622a", B: "#f4b942", C: "#ffd76e", w: "#ffffff", k: "#1a1a1a", m: "#5a1d08" },
    art: [
      ".....C.....C....",
      "....CBC...CBC...",
      ".oo.CBBC.CBBC...",
      "oAAo.BB...BB....",
      "oAAAoooooooo....",
      ".oAAAAAAAAAAo...",
      "oAAwwkAAAwwkAo..",
      "oAAwwwAAAwwwAo..",
      "oAAAAAmmmAAAAAo.",
      "oAABAAmmmAABAAo.",
      "oAABBAAAAABBAAo.",
      ".oABBBBBBBBBAo..",
      ".oAABBBBBBBAAo..",
      "..oAAAAAAAAAo...",
      ".oAAoo...ooAAo..",
      "................",
    ],
  },
  aquafin: {
    name: "AQUAFIN", types: ["Water"], base: [46, 48, 55, 43, 60],
    catchRate: 45, baseExp: 66, evolvesTo: "tidalfin", evolveLevel: 16,
    learnset: [[1, "tackle"], [1, "tailwhip"], [7, "watergun"], [13, "bite"], [20, "bubblebeam"]],
    pal: { o: "#0d2a52", A: "#4f8fd4", B: "#8fc3f0", C: "#2a5fa8", w: "#ffffff", k: "#1a1a1a", m: "#0d3a6a" },
    art: [
      "......oCo.......",
      ".....oCCCo......",
      "....ooCCCoo.....",
      "...oAAACAAAo....",
      "..oAAAAAAAAAo...",
      ".oAAwkAAAwkAAo..",
      ".oAAwwAAAwwAAo..",
      ".oAAAAAAAAAAAoo.",
      "oCoAABBBBBAAoCCo",
      "oCCoABBBBBAoCCo.",
      ".oCoABBBBBAoCo..",
      "..oAAABBAAAo....",
      "...oAAAAAAo.....",
      "....oAAAAo......",
      "...oCo..oCo.....",
      "................",
    ],
  },
  tidalfin: {
    name: "TIDALFIN", types: ["Water"], base: [60, 63, 70, 58, 75],
    catchRate: 45, baseExp: 143,
    learnset: [[1, "tackle"], [1, "tailwhip"], [7, "watergun"], [13, "bite"], [22, "bubblebeam"]],
    pal: { o: "#081f42", A: "#3a76ba", B: "#9fd3f8", C: "#1d4d94", w: "#ffffff", k: "#1a1a1a", m: "#0a2f5a" },
    art: [
      "..oCo......oCo..",
      "..oCCo....oCCo..",
      "...oCCoooCCCo...",
      "...oACCCCCAAo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      "oCoAAABBBBAAAoo.",
      "oCCoAABBBBAAoCCo",
      "oCCoAABBBBAAoCo.",
      ".ooAAABBBBAAAo..",
      "..oAAAAAAAAAo...",
      "...oAAAAAAAo....",
      "..oCCo...oCCo...",
      "................",
    ],
  },
  nibbit: {
    name: "NIBBIT", types: ["Normal"], base: [35, 50, 32, 60, 25],
    catchRate: 255, baseExp: 51, evolvesTo: "gnawlord", evolveLevel: 18,
    learnset: [[1, "tackle"], [3, "tailwhip"], [7, "quickattack"], [12, "bite"], [18, "hyperfang"]],
    pal: { o: "#3a2a1a", A: "#b08a5a", B: "#e8d0a8", C: "#7a5a3a", w: "#ffffff", k: "#1a1a1a", m: "#5a3a22" },
    art: [
      "..oo......oo....",
      ".oAAo....oAAo...",
      ".oABAo..oABAo...",
      ".oAABooooBAAo...",
      "..oAAAAAAAAo....",
      ".oAAwkAAwkAAo...",
      ".oAAwwAAwwAAo...",
      ".oAAAAooAAAAo...",
      "..oAAAwwAAAo....",
      "..oAAAAAAAAo....",
      ".oAAABBBBAAAo..o",
      ".oAAABBBBAAAo.oC",
      ".oAAABBBBAAAooC.",
      "..oAAAAAAAAoCC..",
      "..oAo....oAo....",
      "................",
    ],
  },
  gnawlord: {
    name: "GNAWLORD", types: ["Normal"], base: [55, 71, 50, 85, 45],
    catchRate: 127, baseExp: 116,
    learnset: [[1, "tackle"], [3, "tailwhip"], [7, "quickattack"], [12, "bite"], [18, "hyperfang"]],
    pal: { o: "#2a1a0a", A: "#8a6a42", B: "#e0c898", C: "#5a3a22", w: "#ffffff", k: "#1a1a1a", m: "#3a2210" },
    art: [
      ".ooo........ooo.",
      "oAAAo......oAAAo",
      "oABBAo....oABBAo",
      "oAABBooooooBBAAo",
      ".oAAAAAAAAAAAAo.",
      "oAAwwkAAAAwwkAAo",
      "oAAwwwAAAAwwwAAo",
      "oAAAAAoooAAAAAAo",
      ".oAAAAwwwAAAAo..",
      ".oAAAAAwwAAAAo..",
      "oAAAABBBBBAAAAo.",
      "oAAAABBBBBAAAAo.",
      "oAAAABBBBBAAAAoo",
      ".oAAAAAAAAAAoCCo",
      ".oAAo.....oAoCo.",
      "................",
    ],
  },
  flitchick: {
    name: "FLITCHICK", types: ["Normal", "Flying"], base: [40, 45, 35, 56, 35],
    catchRate: 255, baseExp: 54, evolvesTo: "galewing", evolveLevel: 18,
    learnset: [[1, "peck"], [3, "growl"], [7, "gust"], [12, "quickattack"], [16, "wingattack"]],
    pal: { o: "#4a3208", A: "#e8c85a", B: "#f8e8a8", C: "#e88a2a", w: "#ffffff", k: "#1a1a1a", m: "#a8641a" },
    art: [
      "................",
      "......ooo.......",
      ".....oAAAo......",
      "....oAwkAAo.....",
      "....oAwwAAoCC...",
      "....oAAAACCC....",
      "....oAAAAo......",
      "...ooAAAAoo.....",
      "..oAABBBBAAo....",
      ".oAAoBBBBoAAo...",
      ".oAAoBBBBoAAo...",
      "..ooABBBBAoo....",
      "....oAAAAo......",
      ".....oAAo.......",
      "....CCoCC.......",
      "................",
    ],
  },
  galewing: {
    name: "GALEWING", types: ["Normal", "Flying"], base: [63, 60, 55, 81, 50],
    catchRate: 127, baseExp: 122,
    learnset: [[1, "peck"], [3, "growl"], [7, "gust"], [12, "quickattack"], [18, "wingattack"]],
    pal: { o: "#3a2606", A: "#d4a83a", B: "#f8ecc0", C: "#d4661a", w: "#ffffff", k: "#1a1a1a", m: "#8a4a12" },
    art: [
      "......oo........",
      ".....oAAoo......",
      "....oAwkAAo.....",
      "....oAwwAAooCC..",
      ".....oAAAACCC...",
      "..o..oAAAAo.o...",
      ".oAo.oAAAAo.oAo.",
      "oAAooAABBAAooAAo",
      "oAAAoABBBBAoAAAo",
      "oAAAABBBBBBAAAAo",
      ".oAAABBBBBBAAAo.",
      "..ooABBBBBBAoo..",
      "....oAAAAAAo....",
      ".....oAAAAo.....",
      "....CCo..oCC....",
      "................",
    ],
  },
  buzzler: {
    name: "BUZZLER", types: ["Bug", "Poison"], base: [40, 55, 45, 50, 35],
    catchRate: 190, baseExp: 52,
    learnset: [[1, "poisonsting"], [4, "stringshot"], [10, "bugbite"], [18, "sludge"]],
    pal: { o: "#2a2a0a", A: "#b8c832", B: "#6a7a1a", C: "#c0b0e8", w: "#ffffff", k: "#1a1a1a", m: "#4a5210" },
    art: [
      "..o..........o..",
      "...o........o...",
      "....o..oo..o....",
      "...ooAAAAAAoo...",
      "..oAAwkAAwkAAo..",
      "..oAAwwAAwwAAo..",
      "...oAAAAAAAAo...",
      "CCooABBBBBBAooCC",
      "CCCoABBBBBBAoCCC",
      "CCooBBAAAABBooCC",
      "..oABBAAAABBAo..",
      "..oABBBBBBBBAo..",
      "...oABBBBBBAo...",
      "....oABBBBAo....",
      ".....oooooo.....",
      "................",
    ],
  },
  sparkit: {
    name: "SPARKIT", types: ["Electric"], base: [40, 45, 40, 70, 55],
    catchRate: 150, baseExp: 58,
    learnset: [[1, "thundershock"], [4, "growl"], [9, "quickattack"], [14, "thunderwave"], [17, "spark"]],
    pal: { o: "#4a3a00", A: "#f8d030", B: "#f8ec90", C: "#e87a1a", w: "#ffffff", k: "#1a1a1a", m: "#a8641a" },
    art: [
      "oo............oo",
      "oCo..........oCo",
      ".oCo........oCo.",
      "..oAoo....ooAo..",
      "..oAAAooooAAAo..",
      "..oAAAAAAAAAAo..",
      ".oAAwkAAAAwkAAo.",
      ".oAAwwAAAAwwAAo.",
      ".oAACCAAAACCAAo.",
      ".oAAAAmmmmAAAAo.",
      "..oAAAAAAAAAAo..",
      "..oAABBBBBBAAo..",
      "..oAABBBBBBAAo..",
      "...oAAAAAAAAo...",
      "..oAAo....oAAo..",
      "................",
    ],
  },
  boulderhorn: {
    name: "BOULDERHORN", types: ["Rock", "Ground"], base: [60, 70, 85, 30, 35],
    catchRate: 120, baseExp: 86,
    learnset: [[1, "tackle"], [5, "harden"], [9, "rockthrow"], [14, "mudshot"], [20, "rockslide"]],
    pal: { o: "#2a2218", A: "#a89468", B: "#7a6a4a", C: "#e8e0d0", w: "#ffffff", k: "#1a1a1a", m: "#4a3e2a" },
    art: [
      ".......oCo......",
      "......oCCCo.....",
      "......oCCCo.....",
      "...ooooCCoooo...",
      "..oAAAAAAAAAAo..",
      ".oAABAAAAAABAAo.",
      ".oAAwkAAAAwkAAo.",
      "oAAAwwAAAAwwAAAo",
      "oABAAAAAAAAAABAo",
      "oAAAAmmmmmmAAAAo",
      "oAABAAAAAAAABAAo",
      ".oAAABBBBBBAAAo.",
      ".oAABBBBBBBBAAo.",
      "..oAAAAAAAAAAo..",
      ".oAAoo....ooAAo.",
      "................",
    ],
  },
  mistwisp: {
    name: "MISTWISP", types: ["Ghost", "Poison"], base: [35, 40, 40, 75, 70],
    catchRate: 90, baseExp: 95,
    learnset: [[1, "lick"], [6, "poisonsting"], [12, "shadebolt"], [18, "sludge"]],
    pal: { o: "#241436", A: "#8a6ab8", B: "#5a3a8a", C: "#c8b8e8", w: "#ffffff", k: "#1a1a1a", m: "#3a2258" },
    art: [
      "................",
      ".....oooooo.....",
      "...ooAAAAAAoo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAAAmmmmmmAAAo.",
      ".oAAAAmmmmAAAAo.",
      "..oAAAAAAAAAAo..",
      "..oCAAACCAAACo..",
      "...oAAoAAoAAo...",
      "...oAo.oAo.oo...",
      "....o...o.......",
      "................",
      "................",
    ],
  },
  psyfawn: {
    name: "PSYFAWN", types: ["Psychic"], base: [45, 40, 45, 60, 75],
    catchRate: 75, baseExp: 92,
    learnset: [[1, "tackle"], [6, "confusion"], [10, "growl"], [15, "psybeam"]],
    pal: { o: "#4a2a3a", A: "#e8a8c8", B: "#c87aa8", C: "#f8e8f0", w: "#ffffff", k: "#1a1a1a", m: "#8a4a6a" },
    art: [
      "..oo........oo..",
      ".oBBo......oBBo.",
      ".oBCBo....oBCBo.",
      "..oBBooooooBBo..",
      "...oAAAAAAAAo...",
      "..oAAwkAAwkAAo..",
      "..oAAwwAAwwAAo..",
      "..oAAAACCAAAAo..",
      "...oAAACCAAAo...",
      "....oAAAAAAo....",
      "...oAABBBBAAo...",
      "...oAABBBBAAo...",
      "...oAABBBBAAo...",
      "....oAAAAAAo....",
      "...oAo....oAo...",
      "................",
    ],
  },
};

// ---- Experience curve (medium-fast) -----------------------------
function expForLevel(level) { return level * level * level; }

function statsAtLevel(speciesId, level) {
  const b = SPECIES[speciesId].base;
  const calc = (base) => Math.floor((base * 2 * level) / 100) + 5;
  return {
    hp: Math.floor((b[0] * 2 * level) / 100) + level + 10,
    atk: calc(b[1]), def: calc(b[2]), spd: calc(b[3]), spc: calc(b[4]),
  };
}

// Moves a freshly generated monster of this level knows (last 4 learned)
function movesAtLevel(speciesId, level) {
  const known = SPECIES[speciesId].learnset.filter(([l]) => l <= level).map(([, m]) => m);
  return known.slice(-4);
}

function makeMonster(speciesId, level) {
  const stats = statsAtLevel(speciesId, level);
  return {
    species: speciesId,
    nickname: SPECIES[speciesId].name,
    level,
    exp: expForLevel(level),
    hp: stats.hp,
    stats,
    status: null,        // "psn" | "par" | "brn" | "slp"
    sleepTurns: 0,
    moves: movesAtLevel(speciesId, level).map((id) => ({ id, pp: MOVES[id].pp })),
  };
}

// ---- Items ------------------------------------------------------
const ITEMS = {
  potion:       { name: "Potion",        price: 300,  kind: "heal", amount: 20, desc: "Restores 20 HP." },
  superpotion:  { name: "Super Potion",  price: 700,  kind: "heal", amount: 50, desc: "Restores 50 HP." },
  antidote:     { name: "Antidote",      price: 100,  kind: "cure", cures: ["psn"], desc: "Cures poison." },
  awakening:    { name: "Awakening",     price: 250,  kind: "cure", cures: ["slp", "par", "brn"], desc: "Cures status ills." },
  capsule:      { name: "Capsule",       price: 200,  kind: "ball", bonus: 1,   desc: "Catches wild monsters." },
  greatcapsule: { name: "Great Capsule", price: 600,  kind: "ball", bonus: 1.5, desc: "A better Capsule." },
};

const STATUS_NAMES = { psn: "PSN", par: "PAR", brn: "BRN", slp: "SLP" };
