// =============================================================
// MonsterQuest — game data: types, moves, species, items
// =============================================================
"use strict";

// ---- Type chart -------------------------------------------------
// TYPE_CHART[attacking][defending] = multiplier (missing = 1)
const TYPE_CHART = {
  Normal:   { Ghost: 0, Rock: 0.5 },
  Fire:     { Grass: 2, Bug: 2, Fire: 0.5, Water: 0.5, Rock: 0.5 },
  Water:    { Fire: 2, Rock: 2, Ground: 2, Cyber: 2, Water: 0.5, Grass: 0.5 },
  Grass:    { Water: 2, Rock: 2, Ground: 2, Fire: 0.5, Grass: 0.5, Bug: 0.5, Poison: 0.5, Flying: 0.5 },
  Electric: { Water: 2, Flying: 2, Grass: 0.5, Electric: 0.5, Ground: 0 },
  Flying:   { Grass: 2, Bug: 2, Electric: 0.5, Rock: 0.5 },
  Bug:      { Grass: 2, Psychic: 2, Fire: 0.5, Flying: 0.5, Poison: 0.5, Ghost: 0.5 },
  Poison:   { Grass: 2, Poison: 0.5, Rock: 0.5, Ground: 0.5, Ghost: 0.5 },
  Rock:     { Fire: 2, Flying: 2, Bug: 2, Ground: 0.5 },
  Ground:   { Fire: 2, Electric: 2, Poison: 2, Rock: 2, Cyber: 2, Flying: 0, Grass: 0.5, Bug: 0.5 },
  Psychic:  { Poison: 2, Psychic: 0.5, Cyber: 0.5 },
  Ghost:    { Ghost: 2, Psychic: 2, Normal: 0 },
  Cyber:    { Psychic: 2, Electric: 2, Ground: 0.5, Rock: 0.5, Cyber: 0.5 },
};

const TYPE_COLORS = {
  Normal: "#a8a878", Fire: "#f08030", Water: "#6890f0", Grass: "#78c850",
  Electric: "#f8d030", Flying: "#a890f0", Bug: "#a8b820", Poison: "#a040a0",
  Rock: "#b8a038", Ground: "#e0c068", Psychic: "#f85888", Ghost: "#705898",
  Cyber: "#20b898",
};

function typeMultiplier(moveType, defTypes) {
  let m = 1;
  for (const t of defTypes) {
    const row = TYPE_CHART[moveType];
    if (row && row[t] !== undefined) m *= row[t];
  }
  return m;
}

// ---- Moves ------------------------------------------------------
// kind: "phys" | "spec" | "status"
// effect: { status:"psn"|"par"|"brn"|"slp", chance } applied to target
// stat:   { who:"self"|"foe", stat:"atk"|"def"|"spd", delta }
const MOVES = {
  tackle:       { name: "Tackle",       type: "Normal",   kind: "phys", power: 35, acc: 95,  pp: 35 },
  scratch:      { name: "Scratch",      type: "Normal",   kind: "phys", power: 40, acc: 100, pp: 35 },
  quickattack:  { name: "Quick Attack", type: "Normal",   kind: "phys", power: 40, acc: 100, pp: 30, priority: 1 },
  bite:         { name: "Bite",         type: "Normal",   kind: "phys", power: 60, acc: 100, pp: 25 },
  hyperfang:    { name: "Hyper Fang",   type: "Normal",   kind: "phys", power: 80, acc: 90,  pp: 15 },
  growl:        { name: "Growl",        type: "Normal",   kind: "status", acc: 100, pp: 40, stat: { who: "foe", stat: "atk", delta: -1 } },
  tailwhip:     { name: "Tail Whip",    type: "Normal",   kind: "status", acc: 100, pp: 30, stat: { who: "foe", stat: "def", delta: -1 } },
  sharpen:      { name: "Sharpen",      type: "Normal",   kind: "status", acc: 999, pp: 30, stat: { who: "self", stat: "atk", delta: 1 } },
  harden:       { name: "Harden",       type: "Normal",   kind: "status", acc: 999, pp: 30, stat: { who: "self", stat: "def", delta: 1 } },
  vinewhip:     { name: "Vine Whip",    type: "Grass",    kind: "spec", power: 45, acc: 100, pp: 25 },
  razorleaf:    { name: "Razor Leaf",   type: "Grass",    kind: "spec", power: 55, acc: 95,  pp: 25, highCrit: true },
  sleeppowder:  { name: "Sleep Powder", type: "Grass",    kind: "status", acc: 75, pp: 15, effect: { status: "slp", chance: 100 } },
  ember:        { name: "Ember",        type: "Fire",     kind: "spec", power: 40, acc: 100, pp: 25, effect: { status: "brn", chance: 10 } },
  flameburst:   { name: "Flame Burst",  type: "Fire",     kind: "spec", power: 70, acc: 100, pp: 15, effect: { status: "brn", chance: 10 } },
  watergun:     { name: "Water Gun",    type: "Water",    kind: "spec", power: 40, acc: 100, pp: 25 },
  bubblebeam:   { name: "Bubble Beam",  type: "Water",    kind: "spec", power: 65, acc: 100, pp: 20 },
  thundershock: { name: "Thundershock", type: "Electric", kind: "spec", power: 40, acc: 100, pp: 30, effect: { status: "par", chance: 10 } },
  spark:        { name: "Spark",        type: "Electric", kind: "phys", power: 65, acc: 100, pp: 20, effect: { status: "par", chance: 20 } },
  thunderwave:  { name: "Thunder Wave", type: "Electric", kind: "status", acc: 100, pp: 20, effect: { status: "par", chance: 100 } },
  gust:         { name: "Gust",         type: "Flying",   kind: "spec", power: 40, acc: 100, pp: 35 },
  peck:         { name: "Peck",         type: "Flying",   kind: "phys", power: 35, acc: 100, pp: 35 },
  wingattack:   { name: "Wing Attack",  type: "Flying",   kind: "phys", power: 60, acc: 100, pp: 30 },
  bugbite:      { name: "Bug Bite",     type: "Bug",      kind: "phys", power: 60, acc: 100, pp: 20 },
  stringshot:   { name: "String Shot",  type: "Bug",      kind: "status", acc: 95, pp: 40, stat: { who: "foe", stat: "spd", delta: -1 } },
  poisonsting:  { name: "Poison Sting", type: "Poison",   kind: "phys", power: 15, acc: 100, pp: 35, effect: { status: "psn", chance: 30 } },
  sludge:       { name: "Sludge",       type: "Poison",   kind: "spec", power: 65, acc: 100, pp: 20, effect: { status: "psn", chance: 30 } },
  rockthrow:    { name: "Rock Throw",   type: "Rock",     kind: "phys", power: 50, acc: 90,  pp: 15 },
  rockslide:    { name: "Rock Slide",   type: "Rock",     kind: "phys", power: 75, acc: 90,  pp: 10 },
  mudshot:      { name: "Mud Shot",     type: "Ground",   kind: "spec", power: 55, acc: 95,  pp: 15 },
  confusion:    { name: "Confusion",    type: "Psychic",  kind: "spec", power: 50, acc: 100, pp: 25 },
  psybeam:      { name: "Psybeam",      type: "Psychic",  kind: "spec", power: 65, acc: 100, pp: 20 },
  lick:         { name: "Lick",         type: "Ghost",    kind: "phys", power: 30, acc: 100, pp: 30, effect: { status: "par", chance: 30 } },
  shadebolt:    { name: "Shade Bolt",   type: "Ghost",    kind: "spec", power: 60, acc: 100, pp: 20 },
  aquajet:      { name: "Aqua Jet",     type: "Water",    kind: "phys", power: 40, acc: 100, pp: 20, priority: 1 },
  clawsmash:    { name: "Claw Smash",   type: "Water",    kind: "phys", power: 75, acc: 95,  pp: 15, highCrit: true },
  hydroblast:   { name: "Hydro Blast",  type: "Water",    kind: "spec", power: 85, acc: 100, pp: 10 },
  flamelash:    { name: "Flame Lash",   type: "Fire",     kind: "spec", power: 85, acc: 100, pp: 10, effect: { status: "brn", chance: 10 } },
  voltstrike:   { name: "Volt Strike",  type: "Electric", kind: "spec", power: 85, acc: 100, pp: 10, effect: { status: "par", chance: 10 } },
  petalstorm:   { name: "Petal Storm",  type: "Grass",    kind: "spec", power: 80, acc: 100, pp: 10 },
  quake:        { name: "Quake",        type: "Ground",   kind: "phys", power: 80, acc: 100, pp: 10 },
  bouldercrush: { name: "Boulder Crush",type: "Rock",     kind: "phys", power: 85, acc: 85,  pp: 10 },
  nightpulse:   { name: "Night Pulse",  type: "Ghost",    kind: "spec", power: 80, acc: 100, pp: 10 },
  mindblast:    { name: "Mind Blast",   type: "Psychic",  kind: "spec", power: 85, acc: 100, pp: 10 },
  skydive:      { name: "Sky Dive",     type: "Flying",   kind: "phys", power: 80, acc: 95,  pp: 10 },
  venomlash:    { name: "Venom Lash",   type: "Poison",   kind: "phys", power: 75, acc: 100, pp: 15, effect: { status: "psn", chance: 20 } },
  pixelbeam:    { name: "Pixel Beam",   type: "Normal",   kind: "spec", power: 70, acc: 100, pp: 15 },
  screech:      { name: "Screech",      type: "Normal",   kind: "status", acc: 85, pp: 30, stat: { who: "foe", stat: "def", delta: -2 } },
  agility:      { name: "Agility",      type: "Psychic",  kind: "status", acc: 999, pp: 30, stat: { who: "self", stat: "spd", delta: 2 } },
  regrow:       { name: "Regrow",       type: "Grass",    kind: "status", acc: 999, pp: 10, heal: 0.5 },
  slam:         { name: "Slam",         type: "Normal",   kind: "phys", power: 80, acc: 95,  pp: 15 },
  bitblast:     { name: "Bit Blast",    type: "Cyber",    kind: "spec", power: 40, acc: 100, pp: 30 },
  datastream:   { name: "Data Stream",  type: "Cyber",    kind: "spec", power: 65, acc: 100, pp: 20, effect: { status: "par", chance: 10 } },
  hackslash:    { name: "Hack Slash",   type: "Cyber",    kind: "phys", power: 70, acc: 100, pp: 15, highCrit: true },
  zeroday:      { name: "Zero Day",     type: "Cyber",    kind: "spec", power: 95, acc: 100, pp: 5 },
  glitchburst:  { name: "Glitch Burst", type: "Cyber",    kind: "phys", power: 85, acc: 90,  pp: 10 },
  ddos:         { name: "DDoS",         type: "Cyber",    kind: "status", acc: 90, pp: 20, stat: { who: "foe", stat: "spd", delta: -2 } },
  encrypt:      { name: "Encrypt",      type: "Cyber",    kind: "status", acc: 999, pp: 20, stat: { who: "self", stat: "def", delta: 2 } },
};

// ---- Species ----------------------------------------------------
// base: [hp, atk, def, spd, spc]
// learnset: [level, moveId] — level 1 moves are the starting kit
// art: 16 rows of chars; "." transparent, chars map into pal
//   common chars: o outline, k pupil, w eye-white
const SPECIES = {
  sproutle: {
    name: "SPROUTLE", types: ["Grass"], base: [45, 49, 49, 45, 55],
    catchRate: 45, baseExp: 64, evolvesTo: "bloomurk", evolveLevel: 16,
    learnset: [[1, "tackle"], [1, "growl"], [7, "vinewhip"], [13, "sleeppowder"], [20, "razorleaf"]],
    pal: { o: "#1c3a1c", A: "#63b34f", B: "#2e7d32", C: "#a5d6a7", w: "#ffffff", k: "#1a1a1a", m: "#c62828" },
    art: [
      "......oBB.......",
      ".....oBBBBo.....",
      "....oBBBBBBo....",
      ".....oBBBo......",
      ".......o........",
      "....ooAAAoo.....",
      "...oAAAAAAAo....",
      "..oAAwkAAwkAo...",
      "..oAAwwAAwwAo...",
      "..oAAAAAAAAAo...",
      "..oAAAmmmAAAo...",
      "..oCAAAAAAACo...",
      "...oAAAAAAAo....",
      "....ooAAAoo.....",
      "...oAo...oAo....",
      "................",
    ],
  },
  bloomurk: {
    name: "BLOOMURK", types: ["Grass"], base: [60, 62, 63, 60, 80],
    catchRate: 45, baseExp: 141,
    learnset: [[1, "tackle"], [1, "growl"], [7, "vinewhip"], [13, "sleeppowder"], [22, "razorleaf"], [32, "petalstorm"]],
    pal: { o: "#1c3a1c", A: "#4f9d3f", B: "#2e6d22", C: "#e91e8c", w: "#ffffff", k: "#1a1a1a", m: "#7b1fa2" },
    art: [
      "....C..oB..C....",
      "...CCCoBBoCCC...",
      "....CoBBBBoC....",
      "...oBBBBBBBBo...",
      "....oBBBBBBo....",
      "...ooAAAAAAoo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAAAmmmmmAAAAo.",
      ".oAAAAAAAAAAAAo.",
      "..oAAAAAAAAAAo..",
      "...oAAoooAAo....",
      "..oAAo...oAAo...",
      "................",
    ],
  },
  cindercub: {
    name: "CINDERCUB", types: ["Fire"], base: [44, 52, 43, 55, 50],
    catchRate: 45, baseExp: 65, evolvesTo: "pyroursa", evolveLevel: 16,
    learnset: [[1, "scratch"], [1, "growl"], [7, "ember"], [13, "bite"], [20, "flameburst"]],
    pal: { o: "#4a1a08", A: "#e8813c", B: "#f4b942", C: "#c74a1e", w: "#ffffff", k: "#1a1a1a", m: "#7a2d10" },
    art: [
      "......B.........",
      ".....BBB..B.....",
      "..oo.BCB.BBB....",
      ".oAAo.C.oCBo....",
      ".oAAAooooAAo....",
      "..oAAAAAAAAoo...",
      ".oAAwkAAAwkAAo..",
      ".oAAwwAAAwwAAo..",
      ".oAABBAAABBAAo..",
      ".oAAAAmmmAAAAo..",
      "..oAAAAAAAAAo...",
      "..oAABBBBBAAo...",
      "..oAABBBBBAAo...",
      "...oAAAAAAAo....",
      "..oAAo...oAAo...",
      "................",
    ],
  },
  pyroursa: {
    name: "PYROURSA", types: ["Fire"], base: [58, 64, 58, 70, 65],
    catchRate: 45, baseExp: 142,
    learnset: [[1, "scratch"], [1, "growl"], [7, "ember"], [13, "bite"], [22, "flameburst"], [32, "flamelash"]],
    pal: { o: "#3a1204", A: "#d4622a", B: "#f4b942", C: "#ffd76e", w: "#ffffff", k: "#1a1a1a", m: "#5a1d08" },
    art: [
      ".....C.....C....",
      "....CBC...CBC...",
      ".oo.CBBC.CBBC...",
      "oAAo.BB...BB....",
      "oAAAoooooooo....",
      ".oAAAAAAAAAAo...",
      "oAAwwkAAAwwkAo..",
      "oAAwwwAAAwwwAo..",
      "oAAAAAmmmAAAAAo.",
      "oAABAAmmmAABAAo.",
      "oAABBAAAAABBAAo.",
      ".oABBBBBBBBBAo..",
      ".oAABBBBBBBAAo..",
      "..oAAAAAAAAAo...",
      ".oAAoo...ooAAo..",
      "................",
    ],
  },
  aquafin: {
    name: "AQUAFIN", types: ["Water"], base: [46, 48, 55, 43, 60],
    catchRate: 45, baseExp: 66, evolvesTo: "tidalfin", evolveLevel: 16,
    learnset: [[1, "tackle"], [1, "tailwhip"], [7, "watergun"], [13, "bite"], [20, "bubblebeam"]],
    pal: { o: "#0d2a52", A: "#4f8fd4", B: "#8fc3f0", C: "#2a5fa8", w: "#ffffff", k: "#1a1a1a", m: "#0d3a6a" },
    art: [
      "......oCo.......",
      ".....oCCCo......",
      "....ooCCCoo.....",
      "...oAAACAAAo....",
      "..oAAAAAAAAAo...",
      ".oAAwkAAAwkAAo..",
      ".oAAwwAAAwwAAo..",
      ".oAAAAAAAAAAAoo.",
      "oCoAABBBBBAAoCCo",
      "oCCoABBBBBAoCCo.",
      ".oCoABBBBBAoCo..",
      "..oAAABBAAAo....",
      "...oAAAAAAo.....",
      "....oAAAAo......",
      "...oCo..oCo.....",
      "................",
    ],
  },
  tidalfin: {
    name: "TIDALFIN", types: ["Water"], base: [60, 63, 70, 58, 75],
    catchRate: 45, baseExp: 143,
    learnset: [[1, "tackle"], [1, "tailwhip"], [7, "watergun"], [13, "bite"], [22, "bubblebeam"], [32, "hydroblast"]],
    pal: { o: "#081f42", A: "#3a76ba", B: "#9fd3f8", C: "#1d4d94", w: "#ffffff", k: "#1a1a1a", m: "#0a2f5a" },
    art: [
      "..oCo......oCo..",
      "..oCCo....oCCo..",
      "...oCCoooCCCo...",
      "...oACCCCCAAo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      "oCoAAABBBBAAAoo.",
      "oCCoAABBBBAAoCCo",
      "oCCoAABBBBAAoCo.",
      ".ooAAABBBBAAAo..",
      "..oAAAAAAAAAo...",
      "...oAAAAAAAo....",
      "..oCCo...oCCo...",
      "................",
    ],
  },
  nibbit: {
    name: "NIBBIT", types: ["Normal"], base: [35, 50, 32, 60, 25],
    catchRate: 255, baseExp: 51, evolvesTo: "gnawlord", evolveLevel: 18,
    learnset: [[1, "tackle"], [3, "tailwhip"], [7, "quickattack"], [12, "bite"], [18, "hyperfang"]],
    pal: { o: "#3a2a1a", A: "#b08a5a", B: "#e8d0a8", C: "#7a5a3a", w: "#ffffff", k: "#1a1a1a", m: "#5a3a22" },
    art: [
      "..oo......oo....",
      ".oAAo....oAAo...",
      ".oABAo..oABAo...",
      ".oAABooooBAAo...",
      "..oAAAAAAAAo....",
      ".oAAwkAAwkAAo...",
      ".oAAwwAAwwAAo...",
      ".oAAAAooAAAAo...",
      "..oAAAwwAAAo....",
      "..oAAAAAAAAo....",
      ".oAAABBBBAAAo..o",
      ".oAAABBBBAAAo.oC",
      ".oAAABBBBAAAooC.",
      "..oAAAAAAAAoCC..",
      "..oAo....oAo....",
      "................",
    ],
  },
  gnawlord: {
    name: "GNAWLORD", types: ["Normal"], base: [55, 71, 50, 85, 45],
    catchRate: 127, baseExp: 116,
    learnset: [[1, "tackle"], [3, "tailwhip"], [7, "quickattack"], [12, "bite"], [18, "hyperfang"], [26, "screech"]],
    pal: { o: "#2a1a0a", A: "#8a6a42", B: "#e0c898", C: "#5a3a22", w: "#ffffff", k: "#1a1a1a", m: "#3a2210" },
    art: [
      ".ooo........ooo.",
      "oAAAo......oAAAo",
      "oABBAo....oABBAo",
      "oAABBooooooBBAAo",
      ".oAAAAAAAAAAAAo.",
      "oAAwwkAAAAwwkAAo",
      "oAAwwwAAAAwwwAAo",
      "oAAAAAoooAAAAAAo",
      ".oAAAAwwwAAAAo..",
      ".oAAAAAwwAAAAo..",
      "oAAAABBBBBAAAAo.",
      "oAAAABBBBBAAAAo.",
      "oAAAABBBBBAAAAoo",
      ".oAAAAAAAAAAoCCo",
      ".oAAo.....oAoCo.",
      "................",
    ],
  },
  flitchick: {
    name: "FLITCHICK", types: ["Normal", "Flying"], base: [40, 45, 35, 56, 35],
    catchRate: 255, baseExp: 54, evolvesTo: "galewing", evolveLevel: 18,
    learnset: [[1, "peck"], [3, "growl"], [7, "gust"], [12, "quickattack"], [16, "wingattack"]],
    pal: { o: "#4a3208", A: "#e8c85a", B: "#f8e8a8", C: "#e88a2a", w: "#ffffff", k: "#1a1a1a", m: "#a8641a" },
    art: [
      "................",
      "......ooo.......",
      ".....oAAAo......",
      "....oAwkAAo.....",
      "....oAwwAAoCC...",
      "....oAAAACCC....",
      "....oAAAAo......",
      "...ooAAAAoo.....",
      "..oAABBBBAAo....",
      ".oAAoBBBBoAAo...",
      ".oAAoBBBBoAAo...",
      "..ooABBBBAoo....",
      "....oAAAAo......",
      ".....oAAo.......",
      "....CCoCC.......",
      "................",
    ],
  },
  galewing: {
    name: "GALEWING", types: ["Normal", "Flying"], base: [63, 60, 55, 81, 50],
    catchRate: 127, baseExp: 122,
    learnset: [[1, "peck"], [3, "growl"], [7, "gust"], [12, "quickattack"], [18, "wingattack"], [26, "skydive"]],
    pal: { o: "#3a2606", A: "#d4a83a", B: "#f8ecc0", C: "#d4661a", w: "#ffffff", k: "#1a1a1a", m: "#8a4a12" },
    art: [
      "......oo........",
      ".....oAAoo......",
      "....oAwkAAo.....",
      "....oAwwAAooCC..",
      ".....oAAAACCC...",
      "..o..oAAAAo.o...",
      ".oAo.oAAAAo.oAo.",
      "oAAooAABBAAooAAo",
      "oAAAoABBBBAoAAAo",
      "oAAAABBBBBBAAAAo",
      ".oAAABBBBBBAAAo.",
      "..ooABBBBBBAoo..",
      "....oAAAAAAo....",
      ".....oAAAAo.....",
      "....CCo..oCC....",
      "................",
    ],
  },
  buzzler: {
    name: "BUZZLER", types: ["Bug", "Poison"], base: [40, 55, 45, 50, 35],
    catchRate: 190, baseExp: 52, evolvesTo: "venomdrone", evolveLevel: 20,
    learnset: [[1, "poisonsting"], [4, "stringshot"], [10, "bugbite"], [18, "sludge"]],
    pal: { o: "#2a2a0a", A: "#b8c832", B: "#6a7a1a", C: "#c0b0e8", w: "#ffffff", k: "#1a1a1a", m: "#4a5210" },
    art: [
      "..o..........o..",
      "...o........o...",
      "....o..oo..o....",
      "...ooAAAAAAoo...",
      "..oAAwkAAwkAAo..",
      "..oAAwwAAwwAAo..",
      "...oAAAAAAAAo...",
      "CCooABBBBBBAooCC",
      "CCCoABBBBBBAoCCC",
      "CCooBBAAAABBooCC",
      "..oABBAAAABBAo..",
      "..oABBBBBBBBAo..",
      "...oABBBBBBAo...",
      "....oABBBBAo....",
      ".....oooooo.....",
      "................",
    ],
  },
  sparkit: {
    name: "SPARKIT", types: ["Electric"], base: [40, 45, 40, 70, 55],
    catchRate: 150, baseExp: 58, evolvesTo: "fulgurcat", evolveLevel: 22,
    learnset: [[1, "thundershock"], [4, "growl"], [9, "quickattack"], [14, "thunderwave"], [17, "spark"]],
    pal: { o: "#4a3a00", A: "#f8d030", B: "#f8ec90", C: "#e87a1a", w: "#ffffff", k: "#1a1a1a", m: "#a8641a" },
    art: [
      "oo............oo",
      "oCo..........oCo",
      ".oCo........oCo.",
      "..oAoo....ooAo..",
      "..oAAAooooAAAo..",
      "..oAAAAAAAAAAo..",
      ".oAAwkAAAAwkAAo.",
      ".oAAwwAAAAwwAAo.",
      ".oAACCAAAACCAAo.",
      ".oAAAAmmmmAAAAo.",
      "..oAAAAAAAAAAo..",
      "..oAABBBBBBAAo..",
      "..oAABBBBBBAAo..",
      "...oAAAAAAAAo...",
      "..oAAo....oAAo..",
      "................",
    ],
  },
  boulderhorn: {
    name: "BOULDERHORN", types: ["Rock", "Ground"], base: [60, 70, 85, 30, 35],
    catchRate: 120, baseExp: 86,
    learnset: [[1, "tackle"], [5, "harden"], [9, "rockthrow"], [14, "mudshot"], [20, "rockslide"]],
    pal: { o: "#2a2218", A: "#a89468", B: "#7a6a4a", C: "#e8e0d0", w: "#ffffff", k: "#1a1a1a", m: "#4a3e2a" },
    art: [
      ".......oCo......",
      "......oCCCo.....",
      "......oCCCo.....",
      "...ooooCCoooo...",
      "..oAAAAAAAAAAo..",
      ".oAABAAAAAABAAo.",
      ".oAAwkAAAAwkAAo.",
      "oAAAwwAAAAwwAAAo",
      "oABAAAAAAAAAABAo",
      "oAAAAmmmmmmAAAAo",
      "oAABAAAAAAAABAAo",
      ".oAAABBBBBBAAAo.",
      ".oAABBBBBBBBAAo.",
      "..oAAAAAAAAAAo..",
      ".oAAoo....ooAAo.",
      "................",
    ],
  },
  mistwisp: {
    name: "MISTWISP", types: ["Ghost", "Poison"], base: [35, 40, 40, 75, 70],
    catchRate: 90, baseExp: 95, evolvesTo: "phantasmal", evolveLevel: 30,
    learnset: [[1, "lick"], [6, "poisonsting"], [12, "shadebolt"], [18, "sludge"]],
    pal: { o: "#241436", A: "#8a6ab8", B: "#5a3a8a", C: "#c8b8e8", w: "#ffffff", k: "#1a1a1a", m: "#3a2258" },
    art: [
      "................",
      ".....oooooo.....",
      "...ooAAAAAAoo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAAAmmmmmmAAAo.",
      ".oAAAAmmmmAAAAo.",
      "..oAAAAAAAAAAo..",
      "..oCAAACCAAACo..",
      "...oAAoAAoAAo...",
      "...oAo.oAo.oo...",
      "....o...o.......",
      "................",
      "................",
    ],
  },
  psyfawn: {
    name: "PSYFAWN", types: ["Psychic"], base: [45, 40, 45, 60, 75],
    catchRate: 75, baseExp: 92, evolvesTo: "psyelk", evolveLevel: 28,
    learnset: [[1, "tackle"], [6, "confusion"], [10, "growl"], [15, "psybeam"]],
    pal: { o: "#4a2a3a", A: "#e8a8c8", B: "#c87aa8", C: "#f8e8f0", w: "#ffffff", k: "#1a1a1a", m: "#8a4a6a" },
    art: [
      "..oo........oo..",
      ".oBBo......oBBo.",
      ".oBCBo....oBCBo.",
      "..oBBooooooBBo..",
      "...oAAAAAAAAo...",
      "..oAAwkAAwkAAo..",
      "..oAAwwAAwwAAo..",
      "..oAAAACCAAAAo..",
      "...oAAACCAAAo...",
      "....oAAAAAAo....",
      "...oAABBBBAAo...",
      "...oAABBBBAAo...",
      "...oAABBBBAAo...",
      "....oAAAAAAo....",
      "...oAo....oAo...",
      "................",
    ],
  },
  puddlish: {
    name: "PUDDLISH", types: ["Water"], base: [40, 45, 50, 40, 55],
    catchRate: 190, baseExp: 59, evolvesTo: "torrentide", evolveLevel: 20,
    learnset: [[1, "watergun"], [1, "tailwhip"], [8, "quickattack"], [12, "aquajet"], [18, "bubblebeam"]],
    pal: { o: "#0d2a52", A: "#6aa8e0", B: "#a8d8f8", C: "#3a70b0", w: "#ffffff", k: "#1a1a1a", m: "#12406e" },
    art: [
      "................",
      "....ooooooo.....",
      "...oAAAAAAAo....",
      "..oAAAAAAAAAo...",
      ".oAAwwkAAwwkAo..",
      ".oAAwwwAAwwwAo..",
      ".oAAAAAAAAAAAo..",
      ".oAABmmmmmBAAo..",
      ".oAAABBBBBAAAo..",
      "..oAAAAAAAAAoo..",
      "...oAAAAAAAoCCo.",
      "....oooooooCCo..",
      "...oCo...oCo....",
      "..oCCo...oCCo...",
      "................",
      "................",
    ],
  },
  torrentide: {
    name: "TORRENTIDE", types: ["Water"], base: [65, 70, 75, 60, 80],
    catchRate: 75, baseExp: 153,
    learnset: [[1, "watergun"], [1, "tailwhip"], [12, "aquajet"], [18, "bubblebeam"], [30, "hydroblast"]],
    pal: { o: "#081f42", A: "#3a76ba", B: "#a8d8f8", C: "#1d4d94", w: "#ffffff", k: "#1a1a1a", m: "#0a2f5a" },
    art: [
      "....oCo....oCo..",
      "...oCCCo..oCCCo.",
      "..ooCCCooooCCoo.",
      ".oAAACCCCCCAAAo.",
      "oAAAAAAAAAAAAAAo",
      "oAAwwkAAAAwwkAAo",
      "oAAwwwAAAAwwwAAo",
      "oAAAAAAAAAAAAAAo",
      "oAAABmmmmmmBAAAo",
      "oAAAABBBBBBAAAoo",
      ".oAAABBBBBBAAoCo",
      ".oAAAABBBBAAooCo",
      "..oAAAAAAAAoCCo.",
      "...oAAAAAAoCCo..",
      "..oCCo..oCCo....",
      "................",
    ],
  },
  crabbex: {
    name: "CRABBEX", types: ["Water", "Rock"], base: [45, 75, 60, 35, 40],
    catchRate: 160, baseExp: 78,
    learnset: [[1, "scratch"], [1, "harden"], [9, "watergun"], [15, "clawsmash"], [24, "bubblebeam"]],
    pal: { o: "#3a1208", A: "#e06a3a", B: "#f8b088", C: "#a84420", w: "#ffffff", k: "#1a1a1a", m: "#6a2810" },
    art: [
      "oCCo........oCCo",
      "oCCCo......oCCCo",
      ".oCCCo....oCCCo.",
      ".oCCo......oCCo.",
      "..oCo..oo..oCo..",
      "..ooooAAAAoooo..",
      ".oAAAAAAAAAAAAo.",
      "oAAwwkAAAAwwkAAo",
      "oAAwwwAAAAwwwAAo",
      "oAAAAAAAAAAAAAAo",
      "oAABmmmmmmmmBAAo",
      ".oAAABBBBBBAAAo.",
      "..oAAAAAAAAAAo..",
      "...oooooooooo...",
      "..oCo.oCCo..oCo.",
      "................",
    ],
  },
  squeakwing: {
    name: "SQUEAKWING", types: ["Poison", "Flying"], base: [38, 42, 35, 68, 40],
    catchRate: 255, baseExp: 54, evolvesTo: "shriekwing", evolveLevel: 22,
    learnset: [[1, "gust"], [1, "poisonsting"], [8, "bite"], [14, "wingattack"], [20, "venomlash"]],
    pal: { o: "#241436", A: "#7a5aa8", B: "#b89ae0", C: "#4a3270", w: "#ffffff", k: "#1a1a1a", m: "#e0e0f0" },
    art: [
      "..o..........o..",
      ".oAo........oAo.",
      ".oAAo..oo..oAAo.",
      "..oAAooAAooAAo..",
      "..oAAAAAAAAAAo..",
      ".oAAwkAAAAwkAAo.",
      "oCAAwwAAAAwwAACo",
      "oCCAAAAAAAAAACCo",
      "oCCCAAmmmmAACCCo",
      "oCCCAAmAAmAACCCo",
      ".oCCAAAAAAAACCo.",
      "..ooAAAAAAAAoo..",
      "....oAAAAAAo....",
      ".....oAooAo.....",
      "......o..o......",
      "................",
    ],
  },
  shriekwing: {
    name: "SHRIEKWING", types: ["Poison", "Flying"], base: [68, 72, 60, 95, 60],
    catchRate: 90, baseExp: 135,
    learnset: [[1, "gust"], [1, "poisonsting"], [8, "bite"], [14, "wingattack"], [20, "venomlash"], [28, "skydive"]],
    pal: { o: "#180c28", A: "#5a3a8a", B: "#9a7ac8", C: "#38205a", w: "#ffffff", k: "#c62828", m: "#e0e0f0" },
    art: [
      ".oo...........oo",
      "oAAo....oo...oAA",
      "oAAAo.oAAAo.oAAo",
      "oAAAAoAAAAAoAAAo",
      "oCAAAAAAAAAAAACo",
      "oCCAAwkAAAwkAACo",
      "oCCAAwwAAAwwAACo",
      "oCCCAAAAAAAACCCo",
      "oCCCAmmmmmmACCCo",
      "oCCCAmAmmAmACCCo",
      ".oCCAAAAAAAACCo.",
      ".oCCAAAAAAAACCo.",
      "..ooAAAAAAAAoo..",
      "....oAAAAAAo....",
      ".....oAooAo.....",
      "................",
    ],
  },
  flarepup: {
    name: "FLAREPUP", types: ["Fire"], base: [48, 60, 40, 60, 48],
    catchRate: 150, baseExp: 70, evolvesTo: "infernhound", evolveLevel: 24,
    learnset: [[1, "scratch"], [1, "growl"], [7, "ember"], [13, "bite"], [19, "flameburst"]],
    pal: { o: "#4a1a08", A: "#e88a4a", B: "#f8d0a0", C: "#f4b942", w: "#ffffff", k: "#1a1a1a", m: "#7a2d10" },
    art: [
      "..oo......oo....",
      ".oAAo....oAAo...",
      ".oAmAo..oAmAo...",
      ".oAAAooooAAAo...",
      "..oAAAAAAAAo..C.",
      ".oAAwkAAwkAAo.CC",
      ".oAAwwAAwwAAooCC",
      ".oAAAAooAAAAoCC.",
      "..oAAAmmAAAoCC..",
      "..oAAAAAAAAoC...",
      ".oAAABBBBAAAo...",
      ".oAAABBBBAAAo...",
      "..oAAABBAAAo....",
      "...oAAAAAAo.....",
      "..oAAo..oAAo....",
      "................",
    ],
  },
  infernhound: {
    name: "INFERNHOUND", types: ["Fire"], base: [70, 88, 58, 88, 72],
    catchRate: 60, baseExp: 160,
    learnset: [[1, "scratch"], [1, "growl"], [7, "ember"], [13, "bite"], [19, "flameburst"], [30, "flamelash"]],
    pal: { o: "#3a1204", A: "#d4622a", B: "#f4b942", C: "#ffd76e", w: "#ffffff", k: "#1a1a1a", m: "#5a1d08" },
    art: [
      ".oo........oo...",
      "oAAo......oAAo..",
      "oAmAo....oAmAo..",
      "oAAAAooooAAAAo..",
      ".oAAAAAAAAAAoo..",
      "oAAwwkAAAwwkAAoC",
      "oAAwwwAAAwwwAoCC",
      "oAAAAAoooAAAAoCC",
      ".oAAAAmmmAAAoCCC",
      ".oAABAAAAABAoCC.",
      "oAAABBAAAABBAAo.",
      "oAAABBBBBBBBAAo.",
      "oAAAABBBBBBAAAo.",
      ".oAAAAAAAAAAAo..",
      ".oAAoo...ooAAo..",
      "................",
    ],
  },
  lavaslug: {
    name: "LAVASLUG", types: ["Fire", "Ground"], base: [55, 58, 70, 25, 60],
    catchRate: 120, baseExp: 88,
    learnset: [[1, "ember"], [5, "harden"], [11, "mudshot"], [17, "flameburst"], [26, "quake"]],
    pal: { o: "#3a1000", A: "#c05028", B: "#f8d030", C: "#f47a1e", w: "#ffffff", k: "#1a1a1a", m: "#5a1d08" },
    art: [
      "................",
      "................",
      "....ooo..ooo....",
      "...oBBBooBBBo...",
      "..oBCCBBBBCCBo..",
      ".oBCCCCBBCCCCBo.",
      ".oBCBBCCCCBBCBo.",
      ".oABBABBBBABBAo.",
      "oAAwkAAAAAAwkAAo",
      "oAAwwAAAAAAwwAAo",
      "oAAAAAAAAAAAAAAo",
      "oAAAmmmmmmmmAAAo",
      "oAAAAAAAAAAAAAAo",
      ".oAAAAAAAAAAAAo.",
      "..oooooooooooo..",
      "................",
    ],
  },
  petalfae: {
    name: "PETALFAE", types: ["Grass", "Psychic"], base: [48, 42, 50, 62, 78],
    catchRate: 100, baseExp: 105,
    learnset: [[1, "vinewhip"], [1, "growl"], [9, "confusion"], [15, "razorleaf"], [21, "regrow"], [27, "petalstorm"]],
    pal: { o: "#3a1a3a", A: "#f0a0c8", B: "#78c850", C: "#f8e070", w: "#ffffff", k: "#1a1a1a", m: "#a04a7a" },
    art: [
      "....oo....oo....",
      "...oAAo..oAAo...",
      "..oAAAAooAAAAo..",
      "..oAACCCCCCAAo..",
      "...oCCCCCCCCo...",
      "..oCCwkCCwkCCo..",
      "..oCCwwCCwwCCo..",
      "...oCCmmmmCCo...",
      "..oAACCCCCCAAo..",
      ".oAAAoBBBBoAAAo.",
      ".oAAoBBBBBBoAAo.",
      "..ooBBBBBBBBoo..",
      "....oBBBBBBo....",
      ".....oBooBo.....",
      "....oBo..oBo....",
      "................",
    ],
  },
  oakling: {
    name: "OAKLING", types: ["Grass"], base: [50, 55, 58, 40, 50],
    catchRate: 140, baseExp: 72, evolvesTo: "groveguard", evolveLevel: 25,
    learnset: [[1, "tackle"], [1, "harden"], [8, "vinewhip"], [14, "bite"], [20, "razorleaf"]],
    pal: { o: "#2a1a0a", A: "#8a6a42", B: "#4a9a3a", C: "#2e6d22", w: "#ffffff", k: "#1a1a1a", m: "#5a3a22" },
    art: [
      "......oBBo......",
      ".....oBBBBo.....",
      "....oBCBBCBo....",
      ".....oBBBBo.....",
      "......oBo.......",
      "....ooAAAoo.....",
      "...oAAAAAAAo....",
      "..oAAwkAAwkAo...",
      "..oAAwwAAwwAo...",
      "..oAAAAAAAAAo...",
      "..oAAmmmmmAAo...",
      "..oAAAAAAAAAo...",
      "...oAAAAAAAo....",
      "....oAAAAAo.....",
      "...oAAo.oAAo....",
      "................",
    ],
  },
  groveguard: {
    name: "GROVEGUARD", types: ["Grass"], base: [75, 82, 85, 55, 70],
    catchRate: 60, baseExp: 161,
    learnset: [[1, "tackle"], [1, "harden"], [8, "vinewhip"], [14, "bite"], [20, "razorleaf"], [30, "petalstorm"], [34, "quake"]],
    pal: { o: "#1c1206", A: "#6a4a2a", B: "#2e7d32", C: "#43a047", w: "#ffffff", k: "#1a1a1a", m: "#3a2210" },
    art: [
      "..oBBo....oBBo..",
      ".oBBBBoooBBBBo..",
      "oBBCBBBBBBBCBBo.",
      "oBBBBBBBBBBBBBo.",
      ".oBBBBBBBBBBBo..",
      "..ooAAAAAAAoo...",
      ".oAAAAAAAAAAAo..",
      "oAAwwkAAAwwkAAo.",
      "oAAwwwAAAwwwAAo.",
      "oAAAAAAAAAAAAAo.",
      "oAAAmmmmmmmAAAo.",
      "oAAAAAAAAAAAAAo.",
      "oAAAAAAAAAAAAAo.",
      ".oAAAAooAAAAAo..",
      ".oAAo....oAAo...",
      "................",
    ],
  },
  venomdrone: {
    name: "VENOMDRONE", types: ["Bug", "Poison"], base: [62, 80, 62, 72, 50],
    catchRate: 75, baseExp: 138,
    learnset: [[1, "poisonsting"], [4, "stringshot"], [10, "bugbite"], [18, "sludge"], [23, "venomlash"], [30, "agility"]],
    pal: { o: "#1a1a06", A: "#c8d838", B: "#4a5210", C: "#d8c8f0", w: "#ffffff", k: "#c62828", m: "#2a2e08" },
    art: [
      ".oo.........oo..",
      "o..o.........o..",
      ".o..o..oo..o..o.",
      "..oooAAAAAooo...",
      ".oAAwkAAAwkAAo..",
      ".oAAwwAAAwwAAo..",
      "..oAAAAAAAAAo...",
      "CCooABBBBBAooCC.",
      "CCCoABBBBBAoCCC.",
      "CCCoBBAAABBoCCC.",
      "CCooABBBBBAooCC.",
      ".oAABBBBBBBAAo..",
      "..oABBBBBBBAo...",
      "...oABBBBBAo....",
      "....oooBooo.....",
      "......oBo.......",
    ],
  },
  fulgurcat: {
    name: "FULGURCAT", types: ["Electric"], base: [62, 68, 58, 98, 80],
    catchRate: 75, baseExp: 145,
    learnset: [[1, "thundershock"], [9, "quickattack"], [14, "thunderwave"], [17, "spark"], [24, "agility"], [30, "voltstrike"]],
    pal: { o: "#3a2c00", A: "#f0c020", B: "#f8ec90", C: "#e8791a", w: "#ffffff", k: "#1a1a1a", m: "#8a5a10" },
    art: [
      ".oo..........oo.",
      "oCAo........oACo",
      "oCCAo......oACCo",
      ".oAAoo....ooAAo.",
      ".oAAAAooooAAAAo.",
      ".oAAAAAAAAAAAAo.",
      "oAAwwkAAAAwwkAAo",
      "oAAwwwAAAAwwwAAo",
      "oAACCAAAAAACCAAo",
      ".oAAAmmmmmmAAAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAABBBBBBBBAAo.",
      "..oAABBBBBBAAoo.",
      "...oAAAAAAAAoCCo",
      "..oAAo....oAoCo.",
      "................",
    ],
  },
  psyelk: {
    name: "PSYELK", types: ["Psychic"], base: [70, 60, 65, 85, 105],
    catchRate: 50, baseExp: 155,
    learnset: [[1, "tackle"], [6, "confusion"], [15, "psybeam"], [24, "agility"], [30, "mindblast"]],
    pal: { o: "#3a1c2a", A: "#d888b0", B: "#a85a88", C: "#f8e8f0", w: "#ffffff", k: "#1a1a1a", m: "#7a3a5a" },
    art: [
      "oBo..........oBo",
      "oBBo.oo..oo.oBBo",
      "oBoBoBBooBBoBoBo",
      ".oBBBBooooBBBBo.",
      "..ooAAAAAAAAoo..",
      ".oAAwkAAAAwkAAo.",
      ".oAAwwAAAAwwAAo.",
      ".oAAAACCCCAAAAo.",
      "..oAAACCCCAAAo..",
      "...oAAAAAAAAo...",
      "..oAAABBBBAAAo..",
      "..oAAABBBBAAAo..",
      "..oAAABBBBAAAo..",
      "...oAAAAAAAAo...",
      "..oAo......oAo..",
      "................",
    ],
  },
  phantasmal: {
    name: "PHANTASMAL", types: ["Ghost", "Poison"], base: [58, 62, 58, 105, 100],
    catchRate: 45, baseExp: 158,
    learnset: [[1, "lick"], [6, "poisonsting"], [12, "shadebolt"], [18, "sludge"], [24, "screech"], [31, "nightpulse"]],
    pal: { o: "#140824", A: "#6a4a9a", B: "#38205a", C: "#b8a0e0", w: "#ffffff", k: "#c62828", m: "#241040" },
    art: [
      "..oCo..oo..oCo..",
      "..oCCooAAooCCo..",
      "...oAAAAAAAAo...",
      "..oAAAAAAAAAAo..",
      ".oAAwwkAAwwkAAo.",
      ".oAAwwwAAwwwAAo.",
      ".oAAAAAAAAAAAAo.",
      "oAAAmmmmmmmmAAAo",
      "oAAAmAAAAAAmAAAo",
      "oAAAAAAAAAAAAAAo",
      ".oAAAAAAAAAAAAo.",
      ".oCAAACCAAACCo..",
      "..oAAoAAoAAo....",
      "..oAo.oAo.oo....",
      "...o...o........",
      "................",
    ],
  },
  chompkin: {
    name: "CHOMPKIN", types: ["Grass", "Ghost"], base: [55, 70, 60, 50, 65],
    catchRate: 45, baseExp: 120,
    learnset: [[1, "tackle"], [1, "lick"], [10, "vinewhip"], [16, "shadebolt"], [22, "razorleaf"], [28, "nightpulse"]],
    pal: { o: "#3a1404", A: "#f08828", B: "#2e7d32", C: "#f8d060", w: "#f8e070", k: "#1a1a1a", m: "#5a2408" },
    art: [
      "......oBBo......",
      ".....oBBBo......",
      "......oBo.......",
      "...ooooooooo....",
      "..oAAAAAAAAAo...",
      ".oAAoAAAAoAAAo..",
      "oAAAAAAAAAAAAAo.",
      "oAwwAAAAAAwwAAo.",
      "oAwwAAAAAAwwAAo.",
      "oAAAAAAAAAAAAAo.",
      "oAmmAmmAmmAmmAo.",
      "oAAmmAAmmAAmmAo.",
      ".oAAAAAAAAAAAo..",
      "..oAAAAAAAAAo...",
      "...ooooooooo....",
      "................",
    ],
  },
  pixelit: {
    name: "PIXELIT", types: ["Cyber"], base: [65, 60, 70, 40, 75],
    catchRate: 30, baseExp: 130,
    learnset: [[1, "bitblast"], [1, "harden"], [12, "psybeam"], [18, "pixelbeam"], [24, "regrow"], [30, "zeroday"]],
    pal: { o: "#101040", A: "#e04878", B: "#48c8e0", C: "#f8e048", w: "#ffffff", k: "#1a1a1a", m: "#282868" },
    art: [
      "....oooooooo....",
      "...oBBBBBBBBo...",
      "..oBBAABBAABBo..",
      "..oBAAAABAAABo..",
      ".oABwwkAABwwkAo.",
      ".oABwwwAABwwwAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAACCCCCCCCAAo.",
      ".oAACmmmmmmCAAo.",
      "..oAACCCCCCAAo..",
      "..oBBAAAAAABBo..",
      "..oBBBAAAABBBo..",
      "...oBBoBBoBBo...",
      "...oBo.oo.oBo...",
      "....o......o....",
      "................",
    ],
  },
  terrataur: {
    name: "TERRATAUR", types: ["Rock", "Ground"], base: [90, 100, 110, 45, 65],
    catchRate: 5, baseExp: 220,
    learnset: [[1, "rockthrow"], [1, "harden"], [20, "mudshot"], [26, "rockslide"], [32, "quake"], [38, "bouldercrush"]],
    pal: { o: "#180f08", A: "#8a7050", B: "#5a4630", C: "#e8e0d0", w: "#ffffff", k: "#c62828", m: "#3a2c1a" },
    art: [
      "oCCo........oCCo",
      "oCCCo......oCCCo",
      ".oCCCoooooCCCo..",
      "..oAAAAAAAAAo...",
      ".oAAAAAAAAAAAo..",
      "oAABwkAAAAwkBAAo",
      "oAABwwAAAAwwBAAo",
      "oAAAAAAAAAAAAAAo",
      "oAAAmmmmmmmmAAAo",
      "oABAAAAAAAAAABAo",
      "oAABBAABBAABBAAo",
      "oAABBBBBBBBBBAAo",
      ".oAABBBBBBBBAAo.",
      "..oAAAAAAAAAAo..",
      ".oAAoo....ooAAo.",
      "................",
    ],
  },
  zephyrion: {
    name: "ZEPHYRION", types: ["Electric", "Flying"], base: [85, 95, 80, 120, 105],
    catchRate: 3, baseExp: 240,
    learnset: [[1, "thundershock"], [1, "gust"], [20, "spark"], [28, "skydive"], [34, "voltstrike"], [40, "agility"]],
    pal: { o: "#2a2200", A: "#f8d030", B: "#f8f8e0", C: "#e87a1a", w: "#ffffff", k: "#c62828", m: "#8a6a00" },
    art: [
      "......oo...o....",
      ".....oAAo.oAo...",
      "....oAwkAoAo....",
      "....oAwwAAo.....",
      ".....oAAAACo....",
      ".o...oAAAAoCC...",
      "oAo.oAAAAAo.....",
      "oAAoAABBAAAo.o..",
      "oAAAABBBBAAAoAo.",
      "oAAAABBBBAAAAAo.",
      ".oAAABBBBAAAAAo.",
      "..ooABBBBAAAoo..",
      "..oAAABBAAAo....",
      ".oAooAAAAo......",
      "oo..oCooCo......",
      ".....CC..CC.....",
    ],
  },
};


// ---- Cheshire expansion roster (procedurally sprited) ----------
Object.assign(SPECIES, {
  thornarch: {
    name: "THORNARCH", types: ["Grass"], base: [113, 97, 93, 77, 112],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "vinewhip"], [6, "growl"], [15, "razorleaf"], [21, "sleeppowder"], [30, "petalstorm"], [36, "quake"], [36, "regrow"]],
    gen: { body: "tall", size: 2, feats: ["leaf", "horns"] },
  },
  ursablaze: {
    name: "URSABLAZE", types: ["Fire"], base: [100, 108, 85, 96, 102],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "ember"], [5, "growl"], [14, "bite"], [20, "flameburst"], [33, "flamelash"], [36, "slam"]],
    gen: { body: "quad", size: 2, feats: ["flame", "ears"] },
  },
  tidalord: {
    name: "TIDALORD", types: ["Water"], base: [92, 99, 109, 85, 107],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "watergun"], [5, "tailwhip"], [13, "aquajet"], [20, "bubblebeam"], [33, "hydroblast"], [36, "clawsmash"]],
    gen: { body: "tall", size: 2, feats: ["fins", "horns"] },
  },
  silkin: {
    name: "SILKIN", types: ["Bug"], base: [54, 73, 58, 60, 47],
    catchRate: 200, baseExp: 58, evolvesTo: "cocoonet", evolveLevel: 9,
    learnset: [[1, "poisonsting"], [5, "stringshot"], [12, "bugbite"], [24, "venomlash"]],
    gen: { body: "serpent", size: 0, feats: ["antennae"] },
  },
  cocoonet: {
    name: "COCOONET", types: ["Bug"], base: [51, 69, 61, 63, 48],
    catchRate: 200, baseExp: 58, evolvesTo: "loomoth", evolveLevel: 18,
    learnset: [[1, "poisonsting"], [5, "stringshot"], [10, "harden"], [12, "bugbite"], [24, "venomlash"]],
    gen: { body: "orb", size: 0, feats: ["shell"] },
  },
  loomoth: {
    name: "LOOMOTH", types: ["Bug", "Psychic"], base: [66, 78, 66, 93, 96],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "poisonsting"], [5, "stringshot"], [11, "confusion"], [12, "bugbite"], [16, "psybeam"], [20, "sleeppowder"], [24, "venomlash"], [25, "agility"]],
    gen: { body: "winged", size: 1, feats: ["antennae"] },
  },
  grinkit: {
    name: "GRINKIT", types: ["Normal"], base: [65, 63, 57, 57, 50],
    catchRate: 200, baseExp: 58, evolvesTo: "grinmalkin", evolveLevel: 24,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [16, "bite"], [24, "slam"], [32, "hyperfang"]],
    gen: { body: "quad", size: 0, feats: ["ears", "grin", "tail"] },
  },
  grinmalkin: {
    name: "GRINMALKIN", types: ["Normal", "Psychic"], base: [111, 96, 90, 101, 94],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [16, "bite"], [22, "confusion"], [24, "slam"], [28, "nightpulse"], [32, "hyperfang"], [36, "mindblast"]],
    pal: { o: "#2a1440", A: "#9a5ad8", B: "#5c2ea0", C: "#f0a0d8", w: "#ffffff", k: "#1a1a1a", m: "#3a1a60" },
    art: [
      "..oo........oo..",
      ".oAAo......oAAo.",
      ".oACAo....oACAo.",
      "..oAAooooooAAo..",
      "..oABAABAABAAo..",
      ".oAAwkAAAAwkAAo.",
      ".oAAAAAAAAAAAAo.",
      ".oAwwwwwwwwwwAo.",
      ".oAmwmwmwmwmwAo.",
      "..oAAAAAAAAAAo..",
      "..oABAABAABAAoo.",
      ".oAAAAAAAAAAoCCo",
      ".oAAAAAAAAAAoCo.",
      "..oAAooooAAAo...",
      "..oAo....oAo....",
      "................",
    ],
  },
  cryssal: {
    name: "CRYSSAL", types: ["Rock"], base: [77, 91, 114, 48, 70],
    catchRate: 110, baseExp: 120, evolvesTo: "salberg", evolveLevel: 30,
    learnset: [[1, "harden"], [9, "rockthrow"], [22, "rockslide"], [35, "bouldercrush"]],
    gen: { body: "orb", size: 1, feats: ["rocks", "gem"] },
  },
  salberg: {
    name: "SALBERG", types: ["Rock", "Water"], base: [94, 105, 147, 56, 90],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "harden"], [8, "tailwhip"], [9, "rockthrow"], [15, "aquajet"], [20, "bubblebeam"], [22, "rockslide"], [35, "bouldercrush"]],
    gen: { body: "blob", size: 2, feats: ["rocks", "gem"] },
  },
  perchip: {
    name: "PERCHIP", types: ["Water"], base: [53, 51, 66, 55, 67],
    catchRate: 200, baseExp: 58, evolvesTo: "piketide", evolveLevel: 22,
    learnset: [[1, "watergun"], [5, "tailwhip"], [13, "aquajet"], [20, "bubblebeam"], [33, "hydroblast"]],
    gen: { body: "fish", size: 0, feats: ["fins"] },
  },
  piketide: {
    name: "PIKETIDE", types: ["Water"], base: [82, 77, 87, 71, 82],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "watergun"], [5, "tailwhip"], [13, "aquajet"], [20, "bubblebeam"], [26, "clawsmash"], [33, "hydroblast"]],
    gen: { body: "fish", size: 2, feats: ["fins"] },
  },
  herowing: {
    name: "HEROWING", types: ["Water", "Flying"], base: [77, 77, 69, 96, 80],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "watergun"], [5, "tailwhip"], [9, "gust"], [13, "aquajet"], [19, "wingattack"], [20, "bubblebeam"], [31, "skydive"], [33, "hydroblast"]],
    gen: { body: "winged", size: 2, feats: ["fins"] },
  },
  swanling: {
    name: "SWANLING", types: ["Water", "Flying"], base: [59, 52, 55, 65, 61],
    catchRate: 200, baseExp: 58, evolvesTo: "swanguard", evolveLevel: 26,
    learnset: [[1, "watergun"], [5, "tailwhip"], [10, "gust"], [13, "aquajet"], [20, "bubblebeam"], [20, "wingattack"], [31, "skydive"], [33, "hydroblast"]],
    gen: { body: "winged", size: 0, feats: [] },
  },
  swanguard: {
    name: "SWANGUARD", types: ["Water", "Flying"], base: [95, 94, 94, 110, 98],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "watergun"], [5, "tailwhip"], [11, "gust"], [13, "aquajet"], [20, "bubblebeam"], [20, "wingattack"], [30, "skydive"], [33, "hydroblast"]],
    gen: { body: "winged", size: 2, feats: ["horns"] },
  },
  vulpik: {
    name: "VULPIK", types: ["Fire"], base: [56, 64, 53, 62, 57],
    catchRate: 200, baseExp: 58, evolvesTo: "vulpyre", evolveLevel: 22,
    learnset: [[1, "ember"], [5, "growl"], [14, "bite"], [20, "flameburst"], [33, "flamelash"]],
    gen: { body: "quad", size: 0, feats: ["ears", "tail"] },
  },
  vulpyre: {
    name: "VULPYRE", types: ["Fire"], base: [74, 93, 65, 84, 84],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "ember"], [5, "growl"], [14, "bite"], [20, "flameburst"], [33, "flamelash"]],
    gen: { body: "quad", size: 1, feats: ["ears", "tail", "flame"] },
  },
  brocklet: {
    name: "BROCKLET", types: ["Ground"], base: [69, 70, 64, 44, 45],
    catchRate: 200, baseExp: 58, evolvesTo: "brocklord", evolveLevel: 24,
    learnset: [[1, "tackle"], [6, "harden"], [13, "mudshot"], [31, "quake"]],
    gen: { body: "quad", size: 0, feats: ["stripes"] },
  },
  brocklord: {
    name: "BROCKLORD", types: ["Ground"], base: [92, 96, 85, 63, 64],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "tackle"], [6, "harden"], [13, "mudshot"], [28, "slam"], [31, "quake"]],
    gen: { body: "quad", size: 2, feats: ["stripes"] },
  },
  prickpip: {
    name: "PRICKPIP", types: ["Grass"], base: [63, 54, 61, 50, 64],
    catchRate: 200, baseExp: 58, evolvesTo: "bramblehog", evolveLevel: 20,
    learnset: [[1, "vinewhip"], [6, "growl"], [15, "razorleaf"], [21, "sleeppowder"], [30, "petalstorm"], [36, "regrow"]],
    gen: { body: "blob", size: 0, feats: ["horns"] },
  },
  bramblehog: {
    name: "BRAMBLEHOG", types: ["Grass"], base: [91, 74, 84, 61, 91],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "vinewhip"], [6, "growl"], [15, "razorleaf"], [21, "sleeppowder"], [30, "petalstorm"], [36, "regrow"]],
    gen: { body: "blob", size: 1, feats: ["horns", "leaf"] },
  },
  woolvolt: {
    name: "WOOLVOLT", types: ["Electric"], base: [49, 54, 54, 68, 67],
    catchRate: 200, baseExp: 58, evolvesTo: "ramvolt", evolveLevel: 24,
    learnset: [[1, "thundershock"], [6, "growl"], [15, "spark"], [20, "thunderwave"], [28, "agility"], [34, "voltstrike"]],
    gen: { body: "blob", size: 0, feats: ["ears"] },
  },
  ramvolt: {
    name: "RAMVOLT", types: ["Electric"], base: [74, 75, 65, 99, 87],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "thundershock"], [6, "growl"], [15, "spark"], [20, "thunderwave"], [28, "agility"], [34, "voltstrike"]],
    gen: { body: "quad", size: 2, feats: ["horns", "bolt"] },
  },
  nutchit: {
    name: "NUTCHIT", types: ["Normal"], base: [70, 59, 59, 58, 46],
    catchRate: 200, baseExp: 58, evolvesTo: "oaknaw", evolveLevel: 20,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [16, "bite"], [24, "slam"], [32, "hyperfang"]],
    gen: { body: "quad", size: 0, feats: ["ears", "tail"] },
  },
  oaknaw: {
    name: "OAKNAW", types: ["Normal", "Grass"], base: [98, 73, 89, 66, 74],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [15, "razorleaf"], [16, "bite"], [23, "sleeppowder"], [24, "slam"], [32, "hyperfang"]],
    gen: { body: "quad", size: 1, feats: ["ears", "tail", "leaf"] },
  },
  molburrow: {
    name: "MOLBURROW", types: ["Ground"], base: [72, 65, 63, 46, 46],
    catchRate: 200, baseExp: 58,
    learnset: [[1, "tackle"], [6, "harden"], [13, "mudshot"], [18, "quake"]],
    gen: { body: "blob", size: 0, feats: [] },
  },
  parkstag: {
    name: "PARKSTAG", types: ["Normal", "Grass"], base: [96, 74, 85, 69, 76],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [15, "razorleaf"], [16, "bite"], [22, "sleeppowder"], [24, "slam"], [32, "hyperfang"]],
    gen: { body: "quad", size: 2, feats: ["horns"] },
  },
  creamoo: {
    name: "CREAMOO", types: ["Normal"], base: [92, 74, 84, 79, 71],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [16, "bite"], [22, "regrow"], [24, "slam"], [32, "hyperfang"]],
    gen: { body: "quad", size: 2, feats: ["ears"] },
  },
  peakite: {
    name: "PEAKITE", types: ["Flying", "Rock"], base: [82, 99, 89, 66, 64],
    catchRate: 110, baseExp: 120, evolvesTo: "cragclaw", evolveLevel: 32,
    learnset: [[1, "peck"], [7, "gust"], [10, "rockthrow"], [16, "wingattack"], [22, "rockslide"], [30, "skydive"], [35, "bouldercrush"]],
    gen: { body: "winged", size: 1, feats: ["rocks"] },
  },
  cragclaw: {
    name: "CRAGCLAW", types: ["Flying", "Rock"], base: [91, 127, 111, 86, 77],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "peck"], [7, "gust"], [11, "rockthrow"], [16, "wingattack"], [22, "rockslide"], [30, "skydive"], [39, "bouldercrush"]],
    gen: { body: "winged", size: 2, feats: ["rocks", "horns"] },
  },
  owlume: {
    name: "OWLUME", types: ["Flying", "Psychic"], base: [49, 48, 44, 81, 70],
    catchRate: 200, baseExp: 58, evolvesTo: "strigyx", evolveLevel: 26,
    learnset: [[1, "peck"], [7, "gust"], [9, "confusion"], [16, "wingattack"], [19, "psybeam"], [26, "agility"], [30, "skydive"]],
    gen: { body: "orb", size: 1, feats: ["ears"] },
  },
  strigyx: {
    name: "STRIGYX", types: ["Flying", "Psychic"], base: [78, 79, 74, 134, 127],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "peck"], [7, "gust"], [8, "confusion"], [16, "wingattack"], [19, "psybeam"], [26, "agility"], [30, "skydive"]],
    gen: { body: "winged", size: 2, feats: ["ears", "gem"] },
  },
  chuglet: {
    name: "CHUGLET", types: ["Fire", "Ground"], base: [62, 74, 58, 49, 50],
    catchRate: 200, baseExp: 58, evolvesTo: "steamloco", evolveLevel: 28,
    learnset: [[1, "ember"], [5, "growl"], [7, "harden"], [14, "bite"], [15, "mudshot"], [20, "flameburst"], [33, "flamelash"], [35, "quake"]],
    gen: { body: "orb", size: 1, feats: ["screen", "stripes"] },
  },
  steamloco: {
    name: "STEAMLOCO", types: ["Fire", "Ground"], base: [109, 121, 101, 80, 81],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "ember"], [5, "growl"], [10, "harden"], [14, "bite"], [14, "mudshot"], [20, "flameburst"], [30, "slam"], [31, "quake"], [33, "flamelash"]],
    gen: { body: "blob", size: 2, feats: ["screen", "stripes"] },
  },
  bitmite: {
    name: "BITMITE", types: ["Cyber"], base: [50, 57, 52, 63, 70],
    catchRate: 200, baseExp: 58, evolvesTo: "megamite", evolveLevel: 20,
    learnset: [[1, "bitblast"], [8, "ddos"], [16, "datastream"], [22, "hackslash"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "orb", size: 0, feats: ["pixel", "antennae"] },
  },
  megamite: {
    name: "MEGAMITE", types: ["Cyber"], base: [72, 76, 76, 88, 87],
    catchRate: 110, baseExp: 120, evolvesTo: "gigamite", evolveLevel: 36,
    learnset: [[1, "bitblast"], [8, "ddos"], [16, "datastream"], [22, "hackslash"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "orb", size: 1, feats: ["pixel", "antennae"] },
  },
  gigamite: {
    name: "GIGAMITE", types: ["Cyber"], base: [89, 87, 94, 109, 112],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [8, "ddos"], [16, "datastream"], [22, "hackslash"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "orb", size: 2, feats: ["pixel", "antennae", "horns"] },
  },
  virling: {
    name: "VIRLING", types: ["Cyber", "Poison"], base: [59, 53, 56, 59, 65],
    catchRate: 200, baseExp: 58, evolvesTo: "wormhack", evolveLevel: 25,
    learnset: [[1, "bitblast"], [8, "ddos"], [8, "tailwhip"], [16, "datastream"], [20, "sludge"], [22, "hackslash"], [28, "encrypt"], [28, "venomlash"], [36, "zeroday"]],
    gen: { body: "blob", size: 0, feats: ["pixel"] },
  },
  wormhack: {
    name: "WORMHACK", types: ["Cyber", "Poison"], base: [91, 98, 94, 97, 112],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [8, "ddos"], [11, "tailwhip"], [16, "datastream"], [17, "sludge"], [22, "hackslash"], [28, "encrypt"], [29, "venomlash"], [36, "zeroday"]],
    gen: { body: "serpent", size: 2, feats: ["pixel"] },
  },
  phishfin: {
    name: "PHISHFIN", types: ["Cyber", "Water"], base: [49, 54, 57, 55, 77],
    catchRate: 200, baseExp: 58, evolvesTo: "spearphish", evolveLevel: 28,
    learnset: [[1, "bitblast"], [5, "tailwhip"], [8, "ddos"], [16, "aquajet"], [16, "datastream"], [22, "hackslash"], [24, "bubblebeam"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "fish", size: 1, feats: ["antennae"] },
  },
  spearphish: {
    name: "SPEARPHISH", types: ["Cyber", "Water"], base: [86, 79, 99, 96, 132],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [7, "tailwhip"], [8, "ddos"], [16, "aquajet"], [16, "datastream"], [22, "hackslash"], [23, "bubblebeam"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "fish", size: 2, feats: ["antennae", "horns"] },
  },
  trojanox: {
    name: "TROJANOX", types: ["Cyber", "Ground"], base: [97, 113, 95, 89, 98],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [8, "ddos"], [10, "harden"], [14, "mudshot"], [16, "datastream"], [22, "hackslash"], [28, "encrypt"], [32, "quake"], [36, "zeroday"]],
    gen: { body: "quad", size: 2, feats: ["screen", "stripes"] },
  },
  botnetle: {
    name: "BOTNETLE", types: ["Cyber", "Bug"], base: [63, 91, 72, 95, 79],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "bitblast"], [6, "stringshot"], [8, "ddos"], [13, "bugbite"], [16, "datastream"], [22, "hackslash"], [27, "venomlash"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "orb", size: 1, feats: ["antennae", "shell"] },
  },
  cyphero: {
    name: "CYPHERO", types: ["Cyber", "Psychic"], base: [75, 71, 74, 116, 157],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [8, "ddos"], [11, "confusion"], [16, "datastream"], [18, "psybeam"], [22, "hackslash"], [25, "agility"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "tall", size: 1, feats: ["screen", "gem"] },
  },
  firewaul: {
    name: "FIREWAUL", types: ["Cyber", "Fire"], base: [80, 92, 78, 112, 130],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [8, "ddos"], [8, "growl"], [14, "bite"], [16, "datastream"], [22, "hackslash"], [23, "flameburst"], [28, "encrypt"], [36, "zeroday"]],
    gen: { body: "quad", size: 1, feats: ["flame", "screen"] },
  },
  droneling: {
    name: "DRONELING", types: ["Cyber", "Flying"], base: [48, 52, 43, 88, 61],
    catchRate: 200, baseExp: 58, evolvesTo: "datadrake", evolveLevel: 30,
    learnset: [[1, "bitblast"], [8, "ddos"], [9, "gust"], [16, "datastream"], [19, "wingattack"], [22, "hackslash"], [28, "encrypt"], [31, "skydive"], [36, "zeroday"]],
    gen: { body: "winged", size: 0, feats: ["screen"] },
  },
  datadrake: {
    name: "DATADRAKE", types: ["Cyber", "Flying"], base: [76, 87, 74, 149, 105],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "bitblast"], [8, "ddos"], [8, "gust"], [16, "datastream"], [16, "wingattack"], [22, "hackslash"], [28, "encrypt"], [34, "skydive"], [36, "zeroday"]],
    gen: { body: "winged", size: 2, feats: ["screen", "horns"] },
  },
  gloamite: {
    name: "GLOAMITE", types: ["Ghost", "Rock"], base: [51, 67, 68, 40, 66],
    catchRate: 200, baseExp: 58, evolvesTo: "gloamguard", evolveLevel: 28,
    learnset: [[1, "lick"], [8, "screech"], [10, "rockthrow"], [14, "shadebolt"], [25, "rockslide"], [29, "nightpulse"], [37, "bouldercrush"]],
    gen: { body: "orb", size: 0, feats: ["rocks", "wisp"] },
  },
  gloamguard: {
    name: "GLOAMGUARD", types: ["Ghost", "Rock"], base: [80, 107, 127, 75, 104],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "lick"], [8, "screech"], [10, "rockthrow"], [14, "shadebolt"], [26, "rockslide"], [29, "nightpulse"], [36, "bouldercrush"]],
    gen: { body: "tall", size: 2, feats: ["rocks", "wisp"] },
  },
  manorwraith: {
    name: "MANORWRAITH", types: ["Ghost"], base: [80, 86, 85, 117, 124],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "lick"], [8, "screech"], [14, "shadebolt"], [24, "sleeppowder"], [29, "nightpulse"]],
    gen: { body: "tall", size: 1, feats: ["wisp"] },
  },
  mossling: {
    name: "MOSSLING", types: ["Grass"], base: [70, 55, 57, 48, 63],
    catchRate: 200, baseExp: 58, evolvesTo: "mossbear", evolveLevel: 26,
    learnset: [[1, "vinewhip"], [6, "growl"], [15, "razorleaf"], [21, "sleeppowder"], [30, "petalstorm"], [36, "regrow"]],
    gen: { body: "blob", size: 0, feats: ["leaf"] },
  },
  mossbear: {
    name: "MOSSBEAR", types: ["Grass", "Ground"], base: [127, 112, 112, 64, 77],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "vinewhip"], [6, "growl"], [9, "harden"], [15, "razorleaf"], [16, "mudshot"], [21, "sleeppowder"], [30, "petalstorm"], [35, "quake"], [36, "regrow"]],
    gen: { body: "quad", size: 2, feats: ["leaf", "ears"] },
  },
  sporeling: {
    name: "SPORELING", types: ["Grass", "Poison"], base: [68, 57, 59, 47, 60],
    catchRate: 200, baseExp: 58, evolvesTo: "fungore", evolveLevel: 24,
    learnset: [[1, "vinewhip"], [6, "growl"], [11, "tailwhip"], [15, "razorleaf"], [20, "sludge"], [21, "sleeppowder"], [30, "petalstorm"], [30, "venomlash"], [36, "regrow"]],
    gen: { body: "orb", size: 0, feats: ["leaf"] },
  },
  fungore: {
    name: "FUNGORE", types: ["Grass", "Poison"], base: [89, 72, 88, 64, 87],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "vinewhip"], [6, "growl"], [10, "tailwhip"], [15, "razorleaf"], [20, "sleeppowder"], [21, "sludge"], [30, "petalstorm"], [31, "venomlash"], [36, "regrow"]],
    gen: { body: "tall", size: 1, feats: ["leaf"] },
  },
  bogleap: {
    name: "BOGLEAP", types: ["Water", "Poison"], base: [66, 51, 64, 50, 61],
    catchRate: 200, baseExp: 58, evolvesTo: "toadlore", evolveLevel: 26,
    learnset: [[1, "watergun"], [5, "tailwhip"], [13, "aquajet"], [20, "bubblebeam"], [21, "sludge"], [30, "venomlash"], [33, "hydroblast"]],
    gen: { body: "blob", size: 0, feats: [] },
  },
  toadlore: {
    name: "TOADLORE", types: ["Water", "Poison"], base: [107, 91, 105, 81, 108],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "watergun"], [5, "tailwhip"], [13, "aquajet"], [19, "sludge"], [20, "bubblebeam"], [31, "venomlash"], [33, "hydroblast"]],
    gen: { body: "blob", size: 2, feats: ["horns"] },
  },
  volteel: {
    name: "VOLTEEL", types: ["Electric", "Water"], base: [73, 73, 74, 89, 92],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "thundershock"], [6, "growl"], [8, "tailwhip"], [13, "aquajet"], [15, "spark"], [20, "thunderwave"], [21, "bubblebeam"], [28, "agility"], [34, "voltstrike"]],
    gen: { body: "serpent", size: 1, feats: ["bolt", "fins"] },
  },
  cauldrip: {
    name: "CAULDRIP", types: ["Poison"], base: [66, 56, 57, 57, 57],
    catchRate: 200, baseExp: 58, evolvesTo: "hexbrew", evolveLevel: 27,
    learnset: [[1, "poisonsting"], [8, "tailwhip"], [17, "sludge"], [27, "venomlash"]],
    gen: { body: "orb", size: 0, feats: [] },
  },
  hexbrew: {
    name: "HEXBREW", types: ["Poison", "Ghost"], base: [93, 81, 93, 112, 113],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "poisonsting"], [8, "tailwhip"], [10, "screech"], [17, "shadebolt"], [17, "sludge"], [27, "venomlash"], [29, "nightpulse"]],
    gen: { body: "orb", size: 2, feats: ["wisp"] },
  },
  testudo: {
    name: "TESTUDO", types: ["Rock"], base: [75, 96, 111, 47, 72],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "harden"], [9, "rockthrow"], [18, "encrypt"], [22, "rockslide"], [35, "bouldercrush"]],
    gen: { body: "blob", size: 1, feats: ["shell", "horns"] },
  },
  curdli: {
    name: "CURDLI", types: ["Normal"], base: [64, 59, 56, 64, 49],
    catchRate: 200, baseExp: 58, evolvesTo: "cheshwheel", evolveLevel: 26,
    learnset: [[1, "tackle"], [4, "growl"], [10, "quickattack"], [14, "regrow"], [16, "bite"], [24, "slam"], [32, "hyperfang"]],
    gen: { body: "blob", size: 0, feats: [] },
  },
  cheshwheel: {
    name: "CHESHWHEEL", types: ["Normal", "Ground"], base: [108, 93, 87, 60, 53],
    catchRate: 110, baseExp: 120,
    learnset: [[1, "tackle"], [4, "growl"], [8, "harden"], [10, "quickattack"], [13, "mudshot"], [16, "bite"], [24, "slam"], [31, "quake"], [32, "hyperfang"]],
    gen: { body: "orb", size: 2, feats: ["stripes"] },
  },
  webshade: {
    name: "WEBSHADE", types: ["Bug", "Ghost"], base: [47, 61, 55, 72, 57],
    catchRate: 200, baseExp: 58, evolvesTo: "widowisp", evolveLevel: 27,
    learnset: [[1, "poisonsting"], [5, "stringshot"], [11, "screech"], [12, "bugbite"], [18, "shadebolt"], [24, "venomlash"], [30, "nightpulse"]],
    gen: { body: "orb", size: 0, feats: ["antennae", "wisp"] },
  },
  widowisp: {
    name: "WIDOWISP", types: ["Bug", "Ghost"], base: [68, 98, 92, 130, 104],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "poisonsting"], [5, "stringshot"], [10, "screech"], [12, "bugbite"], [15, "shadebolt"], [24, "venomlash"], [29, "nightpulse"]],
    gen: { body: "orb", size: 1, feats: ["antennae", "wisp"] },
  },
  drakelet: {
    name: "DRAKELET", types: ["Flying", "Fire"], base: [51, 63, 44, 79, 55],
    catchRate: 200, baseExp: 58, evolvesTo: "wyverm", evolveLevel: 34,
    learnset: [[1, "peck"], [6, "growl"], [7, "gust"], [16, "wingattack"], [17, "bite"], [23, "flameburst"], [30, "skydive"]],
    gen: { body: "winged", size: 0, feats: ["horns", "tail"] },
  },
  wyverm: {
    name: "WYVERM", types: ["Flying", "Fire"], base: [80, 112, 70, 138, 92],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "peck"], [5, "growl"], [7, "gust"], [16, "wingattack"], [17, "bite"], [24, "flameburst"], [30, "skydive"]],
    gen: { body: "winged", size: 2, feats: ["horns", "flame", "tail"] },
  },
  bricklum: {
    name: "BRICKLUM", types: ["Rock", "Ground"], base: [105, 136, 140, 45, 67],
    catchRate: 55, baseExp: 172,
    learnset: [[1, "harden"], [9, "rockthrow"], [16, "mudshot"], [22, "rockslide"], [35, "bouldercrush"], [35, "quake"]],
    gen: { body: "tall", size: 2, feats: ["rocks", "stripes"] },
  },
  merlynx: {
    name: "MERLYNX", types: ["Psychic", "Ghost"], base: [94, 82, 87, 146, 180],
    catchRate: 4, baseExp: 235,
    learnset: [[1, "confusion"], [1, "tackle"], [8, "screech"], [15, "shadebolt"], [16, "psybeam"], [25, "agility"], [30, "mindblast"], [32, "nightpulse"], [44, "regrow"]],
    gen: { body: "quad", size: 1, feats: ["ears", "gem", "wisp", "tail"] },
  },
  glitchra: {
    name: "GLITCHRA", types: ["Cyber", "Ghost"], base: [104, 96, 82, 122, 186],
    catchRate: 4, baseExp: 235,
    learnset: [[1, "bitblast"], [1, "lick"], [20, "datastream"], [30, "glitchburst"], [38, "zeroday"], [44, "nightpulse"]],
    pal: { o: "#0a2a24", A: "#12463c", B: "#28c8a0", C: "#a0f8e0", w: "#ffffff", k: "#0a0a0a", m: "#081812" },
    art: [
      ".B..C......C..B.",
      "..BB..oooo..BB..",
      "....ooAAAAoo....",
      "...oAAAAAAAAo...",
      "..oAmmmmmmmmAo..",
      "..oAmCkmmkCmAo..",
      "..oAmmmmmmmmAo..",
      "..oAmmBBBBmmAo..",
      "..oABABABABAAo..",
      "..oAABABABAAAo..",
      "...oABABABAAo...",
      ".C..oAABAAo..C..",
      "....oAo.oAo.....",
      "...oB....oB.....",
      ".BB.........BB..",
      "................",
    ],
  },
});

// ---- Experience curve (medium-fast) -----------------------------
function expForLevel(level) { return level * level * level; }

function statsAtLevel(speciesId, level) {
  const b = SPECIES[speciesId].base;
  const calc = (base) => Math.floor((base * 2 * level) / 100) + 5;
  return {
    hp: Math.floor((b[0] * 2 * level) / 100) + level + 10,
    atk: calc(b[1]), def: calc(b[2]), spd: calc(b[3]), spc: calc(b[4]),
  };
}

// Moves a freshly generated monster of this level knows (last 4 learned)
function movesAtLevel(speciesId, level) {
  const known = SPECIES[speciesId].learnset.filter(([l]) => l <= level).map(([, m]) => m);
  return known.slice(-4);
}

function makeMonster(speciesId, level) {
  const stats = statsAtLevel(speciesId, level);
  return {
    species: speciesId,
    nickname: SPECIES[speciesId].name,
    level,
    exp: expForLevel(level),
    hp: stats.hp,
    stats,
    status: null,        // "psn" | "par" | "brn" | "slp"
    sleepTurns: 0,
    moves: movesAtLevel(speciesId, level).map((id) => ({ id, pp: MOVES[id].pp })),
  };
}

// ---- Items ------------------------------------------------------
const ITEMS = {
  potion:       { name: "Potion",        price: 300,  kind: "heal", amount: 20, desc: "Restores 20 HP." },
  superpotion:  { name: "Super Potion",  price: 700,  kind: "heal", amount: 50, desc: "Restores 50 HP." },
  antidote:     { name: "Antidote",      price: 100,  kind: "cure", cures: ["psn"], desc: "Cures poison." },
  awakening:    { name: "Awakening",     price: 250,  kind: "cure", cures: ["slp", "par", "brn"], desc: "Cures status ills." },
  capsule:      { name: "Capsule",       price: 200,  kind: "ball", bonus: 1,   desc: "Catches wild monsters." },
  greatcapsule: { name: "Great Capsule", price: 600,  kind: "ball", bonus: 1.5, desc: "A better Capsule." },
  ultracapsule: { name: "Ultra Capsule", price: 1500, kind: "ball", bonus: 2,   desc: "The best Capsule made." },
  hyperpotion:  { name: "Hyper Potion",  price: 1500, kind: "heal", amount: 120, desc: "Restores 120 HP." },
  berry:        { name: "Berry",         price: 150,  kind: "heal", amount: 30, desc: "A sweet berry. Restores 30 HP." },
  oldrod:       { name: "Old Rod",       price: 0,    kind: "key",  desc: "Face water and press Z to fish!" },
};

const STATUS_NAMES = { psn: "PSN", par: "PAR", brn: "BRN", slp: "SLP" };
