// =============================================================
// MonsterQuest: The Cheshire Protocol — world data
// 18 towns and villages of Cheshire, 19 routes, and 5 landmark
// sites, generated by deterministic factories + hand-set story.
// =============================================================
// Tile legend (see sprites.js): . grass , flowers = path w tallgrass
// T tree ~ water F fence S sign R roof B wall W window D door
// _ floor r rug C counter K shelf M machine t table X void
// b berry bush G rock c cave floor
"use strict";

// ---- deterministic RNG for map generation ----------------------
function mapHash(s) {
  let h = 2166136261;
  for (const c of s) { h ^= c.codePointAt(0); h = Math.imul(h, 16777619) >>> 0; }
  return h >>> 0;
}
function mapRng(seed) {
  let a = mapHash(seed);
  return () => {
    a = (a + 0x6D2B79F5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const MAPS = {};

// ---- interiors --------------------------------------------------
function makeCare(city, ex, ey) {
  return {
    name: "CARE CENTER", outdoor: false, music: "town",
    tiles: [
      "XXXXXXXXXX", "XBWBBBBWBX", "X________X", "X_CCCCCC_X",
      "X________X", "X________X", "X________X", "XXXXrXXXXX",
    ],
    warps: { "4,7": { map: city, x: ex, y: ey, dir: "down" } },
    signs: {},
    npcs: [{
      id: city + "_nurse", x: 4, y: 2, dir: "down", sprite: "nurse", type: "heal",
      pages: ["Welcome to the CARE CENTER!", "Let me patch your monsters back to full health."],
      afterPages: ["All systems green!", "Stay safe out there — DARKBYTE has monsters acting strangely."],
    }],
  };
}

function makeMart(city, ex, ey, stock) {
  return {
    name: "MART", outdoor: false, music: "town",
    tiles: [
      "XXXXXXXXXX", "XBWBBBBWBX", "X________X", "X_CCCCC__X",
      "X________X", "X_MM__MM_X", "X________X", "XXXXrXXXXX",
    ],
    warps: { "4,7": { map: city, x: ex, y: ey, dir: "down" } },
    signs: {},
    npcs: [{ id: city + "_clerk", x: 3, y: 2, dir: "down", sprite: "clerk", type: "shop", stock }],
  };
}

function makeGym(city, ex, ey, leaderId, trainerId) {
  const npcs = [];
  if (trainerId) npcs.push({ id: city + "_gymtrainer", x: 5, y: 6, dir: "down", sprite: "boy", type: "trainer", trainerId });
  npcs.push({ id: city + "_leader", x: 5, y: 2, dir: "down", sprite: "leader", type: "trainer", trainerId: leaderId });
  return {
    name: "GYM", outdoor: false, music: "town",
    tiles: [
      "XXXXXXXXXXXX", "XBBBBBBBBBBX", "X__________X", "X_M______M_X",
      "X__________X", "X__________X", "X_M______M_X", "X__________X",
      "X__________X", "X_M______M_X", "X__________X", "XXXXXrXXXXXX",
    ],
    warps: { "5,11": { map: city, x: ex, y: ey, dir: "down" } },
    signs: {},
    npcs,
  };
}

// ---- town factory ----------------------------------------------
// Standard town: street across row 6, buildings on rows 2-4 above it.
// cfg: { name, w, buildings:[{kind,slot}], exits:{N:col,S:col,E:true,W:true -> {map,x,y}},
//        pond, music, npcs, signText, seed }
function makeTown(id, cfg) {
  const w = cfg.w || 30, h = cfg.h || 18;
  const rnd = mapRng(id);
  const g = Array.from({ length: h }, (_, y) =>
    Array.from({ length: w }, (_, x) =>
      (y === 0 || y === h - 1 || x === 0 || x === w - 1) ? "T" : "."));
  const warps = {};
  const signs = {};
  const npcs = (cfg.npcs || []).slice();

  // main street
  for (let x = 2; x < w - 2; x++) g[6][x] = "=";
  // exits
  const E = cfg.exits || {};
  if (E.W) { g[6][0] = "="; g[6][1] = "="; warps["0,6"] = E.W; }
  if (E.E) { g[6][w - 1] = "="; g[6][w - 2] = "="; warps[(w - 1) + ",6"] = E.E; }
  if (E.N) { const c = E.N.col; for (let y = 0; y <= 6; y++) g[y][c] = "="; warps[c + ",0"] = E.N.to; }
  if (E.S) { const c = E.S.col; for (let y = 6; y < h; y++) g[y][c] = "="; warps[c + "," + (h - 1)] = E.S.to; }

  // buildings along the top; slots at x = 2 + slot*6 (4 wide)
  for (const b of cfg.buildings || []) {
    const sx = 2 + b.slot * 6;
    for (let y = 2; y <= 3; y++) for (let x = sx; x < sx + 4; x++) g[y][x] = "R";
    for (let x = sx; x < sx + 4; x++) g[4][x] = "B";
    g[4][sx + 2] = "W";
    if (b.door !== false) {
      g[4][sx + 1] = "D";
      g[5][sx + 1] = "=";
      warps[(sx + 1) + ",4"] = { map: b.interior, x: b.ix, y: b.iy, dir: "up" };
    }
  }

  // town sign on the street
  const signX = cfg.signX || 3;
  g[8][signX] = "S";
  signs[signX + ",8"] = [cfg.name.toUpperCase(), ...(cfg.signText || [])];

  // pond (fishing) bottom-right
  if (cfg.pond) {
    for (let y = h - 6; y <= h - 4; y++) for (let x = w - 8; x <= w - 4; x++) g[y][x] = "~";
  }
  // flowers
  for (let i = 0; i < 8; i++) {
    const x = 2 + Math.floor(rnd() * (w - 4)), y = 8 + Math.floor(rnd() * (h - 10));
    if (g[y][x] === ".") g[y][x] = ",";
  }
  // decor houses (no doors)
  for (const dx of cfg.decorHouses || []) {
    for (let y = 9; y <= 10; y++) for (let x = dx; x < dx + 4 && x < w - 1; x++) g[y][x] = "R";
    for (let x = dx; x < dx + 4 && x < w - 1; x++) { g[11][x] = "B"; }
    if (g[11][dx + 2]) g[11][dx + 2] = "W";
  }

  return {
    name: cfg.name.toUpperCase(), outdoor: true, music: cfg.music || "town",
    tiles: g.map((r) => r.join("")),
    warps, signs, npcs,
    fishing: cfg.fishing, hotSpring: cfg.hotSpring,
  };
}

// ---- route factory ---------------------------------------------
// Horizontal routes: w x 12, path row 6. Vertical: 12 x len, path col 6.
function makeRoute(id, cfg) {
  const horiz = cfg.dir !== "v";
  const w = horiz ? (cfg.len || 40) : 18;
  const h = horiz ? 14 : (cfg.len || 34);
  const rnd = mapRng(id);
  const g = Array.from({ length: h }, (_, y) =>
    Array.from({ length: w }, (_, x) =>
      (y === 0 || y === h - 1 || x === 0 || x === w - 1) ? "T" : "."));
  const warps = {};
  const signs = {};
  const npcs = (cfg.npcs || []).slice();
  const P = horiz ? 7 : 9; // path row/col

  if (horiz) {
    for (let x = 0; x < w; x++) g[P][x] = "=";
    warps["0," + P] = cfg.A;
    warps[(w - 1) + "," + P] = cfg.B;
  } else {
    for (let y = 0; y < h; y++) g[y][P] = "=";
    warps[P + ",0"] = cfg.A;
    warps[P + "," + (h - 1)] = cfg.B;
  }

  // tall-grass bands crossing the path
  const bands = cfg.bands === undefined ? 3 : cfg.bands;
  const span = (horiz ? w : h) - 10;
  for (let i = 0; i < bands; i++) {
    const at = 5 + Math.floor(((i + 0.3 + rnd() * 0.5) / bands) * span);
    const bw = 3 + Math.floor(rnd() * 2);
    for (let d = 0; d < bw; d++) for (let s = -3; s <= 3; s++) {
      const x = horiz ? at + d : P + s;
      const y = horiz ? P + s : at + d;
      if (g[y] && g[y][x] && y > 0 && y < h - 1 && x > 0 && x < w - 1) g[y][x] = "w";
    }
  }
  // extra grass pockets off the path
  for (let i = 0; i < (cfg.pockets === undefined ? 3 : cfg.pockets); i++) {
    const cx = 3 + Math.floor(rnd() * (w - 8)), cy = 2 + Math.floor(rnd() * (h - 5));
    for (let dy = 0; dy < 2; dy++) for (let dx = 0; dx < 3; dx++) {
      const x = cx + dx, y = cy + dy;
      if (g[y] && g[y][x] === "." && y > 0 && y < h - 1 && x > 0 && x < w - 1) g[y][x] = "w";
    }
  }
  // tree clusters (forest feel)
  for (let i = 0; i < (cfg.trees || 0); i++) {
    const cx = 2 + Math.floor(rnd() * (w - 6)), cy = 2 + Math.floor(rnd() * (h - 5));
    for (let dy = 0; dy < 2; dy++) for (let dx = 0; dx < 2; dx++) {
      const x = cx + dx, y = cy + dy;
      if (g[y] && g[y][x] === "." && Math.abs((horiz ? y : x) - P) > 1) g[y][x] = "T";
    }
  }
  // water strip with fishing
  if (cfg.water) {
    for (let i = 1; i <= 2; i++) for (let s = 2; s < (horiz ? w : h) - 2; s++) {
      const x = horiz ? s : (cfg.water === "top" ? i : w - 1 - i);
      const y = horiz ? (cfg.water === "top" ? i : h - 1 - i) : s;
      g[y][x] = "~";
    }
  }
  // berries
  for (let i = 0; i < (cfg.berries === undefined ? 2 : cfg.berries); i++) {
    const x = 3 + Math.floor(rnd() * (w - 7)), y = 2 + Math.floor(rnd() * (h - 5));
    if (g[y][x] === "." ) g[y][x] = "b";
  }
  // sign
  const sx = horiz ? 3 : 3, sy = horiz ? 3 : 3;
  if (g[sy][sx] !== "=") { g[sy][sx] = "S"; signs[sx + "," + sy] = cfg.sign || ["ROUTE"]; }

  // trainers stand just off the path, facing it
  (cfg.trainers || []).forEach((tid, i) => {
    const off = i % 2 === 0 ? 1 : -1;
    const at = 6 + Math.floor(((i + 0.6) / (cfg.trainers.length)) * (span - 2));
    const x = horiz ? at : P + off;
    const y = horiz ? P + off : at;
    g[y][x] = ".";
    npcs.push({
      id: id + "_t" + i, x, y,
      dir: horiz ? (off === 1 ? "up" : "down") : (off === 1 ? "left" : "right"),
      sprite: TRAINERS[tid].sprite || "boy", type: "trainer", trainerId: tid,
    });
  });

  return {
    name: (cfg.sign ? cfg.sign[0] : id.toUpperCase()), outdoor: true, music: cfg.music || "route",
    tiles: g.map((r) => r.join("")),
    warps, signs, npcs,
    encounters: cfg.encounters, fishing: cfg.fishing,
  };
}

// ---- cave factory ----------------------------------------------
function makeCave(id, cfg) {
  const w = cfg.w || 26, h = cfg.h || 18;
  const rnd = mapRng(id);
  const g = Array.from({ length: h }, (_, y) =>
    Array.from({ length: w }, (_, x) =>
      (y === 0 || y === h - 1 || x === 0 || x === w - 1) ? "X" : "c"));
  const warps = {};
  // rock sprinkle
  for (let y = 2; y < h - 2; y++) for (let x = 2; x < w - 2; x++) {
    if (rnd() < (cfg.density || 0.16)) g[y][x] = "G";
  }
  // carve L corridors between all key points so everything connects
  const pts = [];
  for (const e of cfg.exits) {
    g[e.y][e.x] = "c";
    warps[e.x + "," + e.y] = e.to;
    pts.push([Math.min(w - 2, Math.max(1, e.x)), Math.min(h - 2, Math.max(1, e.y))]);
  }
  for (const p of cfg.pockets || []) pts.push([p.x, p.y]);
  const carve = (x, y) => { if (g[y] && g[y][x] === "G") g[y][x] = "c"; };
  for (let i = 1; i < pts.length; i++) {
    let [x0, y0] = pts[i - 1], [x1, y1] = pts[i];
    for (let x = Math.min(x0, x1); x <= Math.max(x0, x1); x++) { carve(x, y0); carve(x, y0 + 1); }
    for (let y = Math.min(y0, y1); y <= Math.max(y0, y1); y++) { carve(x1, y); carve(x1 + 1, y); }
  }
  for (const p of cfg.pockets || []) { g[p.y][p.x] = "c"; }
  return {
    name: cfg.name, outdoor: false, music: cfg.music || "cave",
    encounterEverywhere: true,
    tiles: g.map((r) => r.join("")),
    warps, signs: {}, npcs: cfg.npcs || [],
    encounters: cfg.encounters,
  };
}

// ---- encounter table helper ------------------------------------
function enc(lo, hi, commons, uncommons, rares) {
  const t = [];
  for (const s of commons) t.push([s, lo, hi, 30]);
  for (const s of uncommons || []) t.push([s, lo, hi + 1, 14]);
  for (const s of rares || []) t.push([s, lo + 1, hi + 2, 4]);
  return { rate: 0.13, table: t };
}

// ---- trainers ---------------------------------------------------
const TRAINERS = {};
function T(id, name, party, payout, opts) {
  TRAINERS[id] = Object.assign({
    name,
    party,
    payout,
    intro: opts.intro || ["Let's battle!"],
    winMsg: opts.win || ["Well fought!"],
    after: opts.after || ["Keep training!"],
    sprite: opts.sprite,
  }, opts.badge ? { isLeader: true, badge: opts.badge } : {},
     opts.grunt ? { grunt: true } : {});
}

// --- route trainers (Cheshire folk) ---
T("t_walker",  "RAMBLER JUNE",   [["prickpip", 4], ["nibbit", 5]], 220, { sprite: "girl", intro: ["Lovely day on the Middlewood Way!", "Fancy a scrap?"], after: ["The canal towpath is full of fish. Get a rod in BOLLINGTON!"] });
T("t_milly",   "SILK GIRL MILLY",[["silkin", 5], ["silkin", 6]], 240, { sprite: "girl", intro: ["Macclesfield was built on silk!", "My SILKIN spin the finest thread!"], after: ["SILKIN evolves fast. Patience!"] });
T("t_pete",    "LAD PETE",       [["grinkit", 7], ["flitchick", 7]], 300, { intro: ["My GRINKIT's grin gives me nightmares.", "Now it can haunt you too!"], after: ["They say a giant cat grins over all of Cheshire..."] });
T("t_ada2",    "JOGGER SAM",     [["woolvolt", 8], ["nutchit", 8]], 320, { intro: ["Training legs AND monsters!", "No stopping!"], after: ["WILMSLOW's gym runs on pure voltage."] });
T("t_gaskell1","BOOKWORM ELSIE", [["owlume", 11], ["psyfawn", 12]], 460, { sprite: "girl", intro: ["I read minds. Well... my OWLUME does.", "It says you'll lose!"], after: ["MADAM GASKELL saw your victory coming, probably."] });
T("t_edge",    "WANDERER ALF",   [["mossling", 12], ["squeakwing", 12]], 470, { sprite: "oldman", intro: ["Mind the EDGE, traveller.", "Strange things sleep under Alderley..."], after: ["A wizard guards a sleeping king down there. So the legend goes."] });
T("t_tatton",  "POSH TARQUIN",   [["parkstag", 14], ["grinkit", 14]], 700, { intro: ["One's monsters are pedigree, you know.", "En garde!"], after: ["Tatton's deer park is simply divine."] });
T("t_farm1",   "FARMER GILES",   [["creamoo", 16], ["brocklet", 16]], 620, { sprite: "oldman", intro: ["Get off my land!", "...actually, stay for a battle."], after: ["CREAMOO's cheese took gold at the county show."] });
T("t_jodrell", "BOFFIN WREN",    [["bitmite", 15], ["droneling", 15]], 640, { sprite: "girl", intro: ["My monsters are peer-reviewed!", "Hypothesis: you lose."], after: ["JODRELL BANK's dish hears the whole universe.", "Lately it's been... transmitting instead. Odd."] });
T("t_bear1",   "BEAR FAN ROB",   [["brocklet", 17], ["mossling", 17]], 660, { intro: ["Congleton sold its bible to buy a BEAR!", "True story! RAWR!"], after: ["The bear town never forgets."] });
T("t_sand",    "CROSSKEEPER TED",[["testudo", 20], ["curdli", 20]], 800, { sprite: "oldman", intro: ["Sandbach's crosses have stood 1200 years.", "Show me something that lasts!"], after: ["The ARCADE here rots your brain. Wonderful place."] });
T("t_train1",  "SPOTTER NIGEL",  [["chuglet", 22], ["chuglet", 23]], 860, { intro: ["I've logged every engine at CREWE since '86!", "Now logging: your defeat!"], after: ["The rail network can whisk you across Cheshire. Marvellous!"] });
T("t_brine",   "SWIMMER LOU",    [["bogleap", 24], ["perchip", 24]], 900, { sprite: "girl", intro: ["Nantwich brine keeps me young!", "Dive in!"], after: ["The brine pool heals monsters. Free!"] });
T("t_salt1",   "MINER DOT",      [["cryssal", 26], ["molburrow", 26]], 980, { sprite: "girl", intro: ["Northwich sits on a mile of salt!", "Careful it doesn't swallow you."], after: ["DARKBYTE goons were sniffing around the mine..."] });
T("t_forest1", "RANGER FERN",    [["oaknaw", 28], ["fungore", 28]], 1050, { sprite: "girl", intro: ["Delamere is the forest of the meres!", "Respect it!"], after: ["MOSSBEAR guards the deep woods."] });
T("t_hill",    "HIKER BRAM",     [["peakite", 30], ["bramblehog", 30]], 1100, { sprite: "oldman", intro: ["From Frodsham Hill you can see all Cheshire!", "See if you can beat me first!"], after: ["Weird lights over BEESTON CASTLE lately."] });
T("t_chem",    "TECHNICIAN VI",  [["cauldrip", 31], ["volteel", 31]], 1150, { sprite: "girl", intro: ["Runcorn chemicals: 100% safe*", "*mostly"], after: ["RIA's gym failed its last three safety audits. Proudly."] });
T("t_wire1",   "WIRE FAN GARY",  [["megamite", 33], ["botnetle", 33]], 1250, { intro: ["Warrington Wolves! And wires!", "Mostly wires!"], after: ["NETRUNNER MO firewalls everything. Even the kettle."] });
T("t_roman",   "LEGION GAIUS",   [["testudo", 35], ["bricklum", 35]], 1400, { sprite: "oldman", intro: ["Chester's walls have held for 2000 years!", "Testudo formation!"], after: ["The WHITE HATS defend the league within the walls."] });
T("t_dee",     "ANGLER MAUD",    [["piketide", 36], ["swanguard", 36]], 1400, { sprite: "girl", intro: ["The River Dee hides monsters big as boats!", "Reel THIS in!"], after: ["Fish the Dee. You won't regret it."] });

// --- gym leaders ---
T("ada",  "SYSADMIN ADA", [["sparkit", 9], ["woolvolt", 11]], 1400, {
  badge: { flag: "badge", name: "PACKET BADGE" }, sprite: "leader",
  intro: ["Welcome to WILMSLOW's server room... I mean, gym.", "I keep this region's networks humming.", "Let's see your throughput!"],
  win: ["Connection... terminated!"], after: ["Route your journey via KNUTSFORD next. Watch for DARKBYTE."] });
T("gaskell", "MADAM GASKELL", [["psyfawn", 14], ["owlume", 15], ["loomoth", 16]], 1900, {
  badge: { flag: "badge2", name: "CIPHER BADGE" }, sprite: "leader",
  intro: ["Knutsford remembers everything, dear.", "My monsters read intentions like novels.", "Yours is a short story."],
  win: ["What a plot twist!"], after: ["The CIPHER BADGE opens minds. Head south, dear."] });
T("otis", "BEARWARD OTIS", [["brocklord", 20], ["creamoo", 19], ["parkstag", 21]], 2400, {
  badge: { flag: "badge3", name: "BEAR BADGE" }, sprite: "leader",
  intro: ["CONGLETON! The town that traded its bible for a bear!", "My beasts honour that bargain.", "RAAAWR!"],
  win: ["Un-bear-able..."], after: ["West to SANDBACH, then south to the railway town!"] });
T("di",   "STOKER DI", [["chuglet", 23], ["vulpyre", 24], ["steamloco", 26]], 2900, {
  badge: { flag: "badge4", name: "KERNEL BADGE" }, sprite: "leader",
  intro: ["Every engine in Britain came through CREWE!", "My firebox never goes out.", "Full steam ahead!"],
  win: ["Out of steam..."], after: ["Take the KERNEL BADGE. The station can fast-track you around Cheshire now!"] });
T("nell", "BRINE NELL", [["swanling", 26], ["piketide", 27], ["toadlore", 29]], 3400, {
  badge: { flag: "badge5", name: "TOKEN BADGE" }, sprite: "leader",
  intro: ["Nantwich brine has healed folk for centuries.", "It also breeds ferocious monsters.", "In you go!"],
  win: ["Washed out..."], after: ["North through the salt lands to NORTHWICH!"] });
T("jack", "FOREMAN JACK", [["cryssal", 29], ["testudo", 30], ["salberg", 32]], 3900, {
  badge: { flag: "badge6", name: "DAEMON BADGE" }, sprite: "leader",
  intro: ["A mile beneath us sits the great salt seam.", "My monsters ARE the bedrock.", "Try shifting them!"],
  win: ["Undermined!"], after: ["DARKBYTE crawled into our mine. Someone should flush them out..."] });
T("ria",  "CHEMIST RIA", [["fungore", 32], ["hexbrew", 34], ["wormhack", 35]], 4400, {
  badge: { flag: "badge7", name: "PROXY BADGE" }, sprite: "leader",
  intro: ["Runcorn built an empire of chemistry!", "My concoctions are... volatile.", "Do keep breathing!"],
  win: ["Neutralized..."], after: ["One badge left. WARRINGTON's NETRUNNER awaits."] });
T("mo",   "NETRUNNER MO", [["botnetle", 35], ["firewaul", 36], ["cyphero", 36], ["gigamite", 38]], 5000, {
  badge: { flag: "badge8", name: "ADMIN BADGE" }, sprite: "leader",
  intro: ["I built half this region's firewalls.", "DARKBYTE broke them with monsters like these.", "So I tamed better ones. Authenticate yourself!"],
  win: ["Access... granted."],
  after: ["Eight badges. You have ROOT... almost.", "DARKBYTE has seized JODRELL BANK. Stop the broadcast, then claim the league at CHESTER!"] });

// --- DARKBYTE ---
T("grunt1", "DARKBYTE GRUNT", [["virling", 25], ["bitmite", 26]], 700, { sprite: "grunt", grunt: true,
  intro: ["This mine is DARKBYTE turf now!", "Beat it, script kiddie!"], win: ["Ugh, reporting this bug..."], after: ["Whatever. The real op is at the telescope."] });
T("grunt2", "DARKBYTE GRUNT", [["gloamite", 26], ["botnetle", 26]], 700, { sprite: "grunt", grunt: true,
  intro: ["We're mining more than salt down here.", "We're mining DATA!"], win: ["Connection reset..."], after: ["You'll never crack the boss's encryption."] });
T("nullsec", "LIEUTENANT NULL", [["wormhack", 28], ["trojanox", 28], ["megamite", 29]], 2000, { sprite: "boss",
  intro: ["So the white-hat brat found our mine node.", "I am NULL. Prepare for segfault."], win: ["Core... dumped..."],
  after: ["ROOT will finish what we started at JODRELL BANK.", "The broadcast can't be stopped!"] });
T("grunt3", "DARKBYTE GRUNT", [["megamite", 36], ["virling", 36]], 1300, { sprite: "grunt", grunt: true,
  intro: ["The dish belongs to DARKBYTE!", "Get lost!"], win: ["Kernel panic!"], after: ["ROOT is up by the telescope. You're doomed."] });
T("grunt4", "DARKBYTE GRUNT", [["phishfin", 36], ["botnetle", 37]], 1300, { sprite: "grunt", grunt: true,
  intro: ["Ever been phished, kid?", "Consider this a live exercise!"], win: ["I clicked the wrong link..."], after: ["The signal is almost at full power..."] });
T("grunt5", "DARKBYTE GRUNT", [["droneling", 37], ["wormhack", 37]], 1300, { sprite: "grunt", grunt: true,
  intro: ["Our botnet spans every mast in Cheshire!", "You can't unplug us all!"], win: ["403... forbidden..."], after: ["ROOT fears nothing. Except maybe you."] });
T("rootboss", "ROOT", [["firewaul", 40], ["trojanox", 41], ["cyphero", 42], ["gigamite", 44]], 8000, { sprite: "boss",
  intro: ["At last. The pentester from MACCLESFIELD.", "I am ROOT. This dish now broadcasts MY signal — every monster in Cheshire will answer to DARKBYTE.",
          "You hold eight badges? Cute. I hold the whole spectrum.", "Let's see who has admin rights over this region!"],
  win: ["Impossible... privileges... revoked...", "The signal... it's collapsing. What have you done?"],
  after: ["The broadcast was never the brain. Only the mouth.",
          "The thing that paid us — ORACLE — lives in the new datacentre south of WINSFORD. THE STACK.",
          "I tried to burn it out with the dish. You saw how that went. Your turn, pentester."] });

// --- White Hats + champion ---
T("sue", "WHITE HAT SUE", [["manorwraith", 40], ["widowisp", 40], ["gloamguard", 41], ["phantasmal", 42]], 4200, { sprite: "elite",
  intro: ["Welcome to the FIREWALL, challenger.", "I audit the unseen. Ghosts in every machine.", "Let's review your defences."],
  win: ["Clean audit. Proceed."], after: ["RAJ's defence is rated military-grade."] });
T("raj", "WHITE HAT RAJ", [["bricklum", 41], ["salberg", 41], ["trojanox", 42], ["mossbear", 42]], 4200, { sprite: "elite",
  intro: ["I am the wall the wall relies on.", "Nothing gets through RAJ.", "Attempt your exploit."],
  win: ["Breach... logged."], after: ["KIM strikes from above. Good luck."] });
T("kim", "WHITE HAT KIM", [["cragclaw", 42], ["strigyx", 42], ["swanguard", 43], ["wyverm", 44]], 4200, { sprite: "elite",
  intro: ["Attack surface? The whole sky.", "My monsters patrol every packet of air.", "Intercept THIS."],
  win: ["Signal lost!"], after: ["Only DOC stands before the champion."] });
T("doc", "WHITE HAT DOC", [["megamite", 43], ["spearphish", 43], ["datadrake", 44], ["gigamite", 45]], 4200, { sprite: "elite",
  intro: ["I wrote my thesis on DARKBYTE's code.", "Then I domesticated it.", "Final exam. Begin."],
  win: ["Full marks..."], after: ["The champion waits. You may know them already."] });

const RIVAL_COUNTER = { sproutle: "cindercub", cindercub: "aquafin", aquafin: "sproutle" };

// ---- rail network ----------------------------------------------
const STATIONS = {
  macclesfield: { label: "MACCLESFIELD", x: 16, y: 8 },
  wilmslow:     { label: "WILMSLOW", x: 16, y: 9 },
  crewe:        { label: "CREWE", x: 16, y: 9 },
  warrington:   { label: "WARRINGTON", x: 16, y: 9 },
  chester:      { label: "CHESTER", x: 18, y: 8 },
};

// ---- standard mart stocks --------------------------------------
const STOCK_EARLY = ["potion", "antidote", "capsule"];
const STOCK_MID   = ["potion", "superpotion", "antidote", "awakening", "capsule", "greatcapsule"];
const STOCK_LATE  = ["superpotion", "hyperpotion", "antidote", "awakening", "greatcapsule", "ultracapsule"];

// =============================================================
// TOWNS
// =============================================================
MAPS.macclesfield = makeTown("macclesfield", {
  name: "Macclesfield", w: 32,
  signText: ["The old silk town.", "Home of ALDER LABS."],
  buildings: [
    { kind: "home", slot: 0, interior: "home", ix: 4, iy: 6 },
    { kind: "lab",  slot: 1, interior: "lab", ix: 5, iy: 8 },
    { kind: "care", slot: 2, interior: "care_macclesfield", ix: 4, iy: 6 },
    { kind: "mart", slot: 3, interior: "mart_macclesfield", ix: 4, iy: 6 },
  ],
  exits: {
    N: { col: 12, to: { map: "route1", x: 9, y: 32, dir: "up" } },
    W: { map: "route2", x: 38, y: 7, dir: "left" },
  },
  pond: true,
  fishing: { table: [["puddlish", 4, 7, 60], ["perchip", 4, 7, 40]] },
  npcs: [
    { id: "block_n", x: 12, y: 1, dir: "down", sprite: "assistant", hideIfFlag: "starter", type: "dialog",
      pages: ["Whoa there, JIM! No wandering off without a monster.", "DR. ALDER needs you at the LAB — says it's urgent security business!"] },
    { id: "block_w", x: 1, y: 7, dir: "right", sprite: "assistant", hideIfFlag: "starter", type: "dialog",
      pages: ["Road's closed till you've seen DR. ALDER!", "The LAB is the second building along."] },
    { id: "macc_station", x: 17, y: 8, dir: "down", sprite: "clerk", type: "station", station: "macclesfield" },
    { id: "macc_girl", x: 6, y: 10, dir: "down", sprite: "girl", type: "dialog",
      pages: ["Monsters have been glitchy ever since that weird signal started.", "My GRINKIT keeps staring at the phone mast..."] },
  ],
  decorHouses: [16],
});

MAPS.bollington = makeTown("bollington", {
  name: "Bollington", w: 28,
  signText: ["Happy Valley on the canal."],
  buildings: [{ kind: "care", slot: 0, interior: "care_bollington", ix: 4, iy: 6 }],
  exits: { S: { col: 10, to: { map: "route1", x: 9, y: 1, dir: "down" } } },
  pond: true,
  fishing: { table: [["perchip", 5, 8, 60], ["puddlish", 5, 8, 30], ["bogleap", 6, 9, 10]] },
  npcs: [
    { id: "boll_fisher", x: 11, y: 11, dir: "down", sprite: "fisher", type: "fisher" },
    { id: "boll_kid", x: 5, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["The canal runs all the way to Macclesfield!", "Anglers say something CYBER swims in it now. Spooky."] },
  ],
});

MAPS.prestbury = makeTown("prestbury", {
  name: "Prestbury", w: 28,
  signText: ["Cheshire's prettiest village. Official."],
  buildings: [{ kind: "care", slot: 0, interior: "care_prestbury", ix: 4, iy: 6 }],
  exits: {
    E: { map: "route2", x: 1, y: 7, dir: "right" },
    W: { map: "route3", x: 38, y: 7, dir: "left" },
  },
  npcs: [
    { id: "prest_man", x: 6, y: 12, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["Footballers and monsters — this village has everything.", "WILMSLOW is just west. Mind the traffic."] },
  ],
  decorHouses: [8, 14],
});

MAPS.wilmslow = makeTown("wilmslow", {
  name: "Wilmslow", w: 30,
  signText: ["Where tech money meets old money.", "GYM: SYSADMIN ADA — Electric."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_wilmslow", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_wilmslow", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_wilmslow", ix: 5, iy: 10 },
  ],
  exits: {
    E: { map: "route3", x: 1, y: 7, dir: "right" },
    S: { col: 11, to: { map: "route4", x: 9, y: 1, dir: "down" } },
  },
  npcs: [
    { id: "wilm_station", x: 16, y: 8, dir: "down", sprite: "clerk", type: "station", station: "wilmslow" },
    { id: "wilm_exec", x: 5, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["ADA keeps the whole region's net running from that gym.", "GROUND moves? Useless against her! Wait— no, they're GREAT. Forget I said that."] },
  ],
});

MAPS.alderleyedge = makeTown("alderleyedge", {
  name: "Alderley Edge", w: 28,
  signText: ["Beneath the Edge, the Wizard waits.", "The caverns are NOT council-maintained."],
  buildings: [{ kind: "care", slot: 0, interior: "care_alderleyedge", ix: 4, iy: 6 }],
  exits: {
    N: { col: 10, to: { map: "route4", x: 9, y: 32, dir: "up" } },
    W: { map: "route5", x: 38, y: 7, dir: "left" },
    E: { map: "edgecaverns", x: 1, y: 9, dir: "right" },
  },
  npcs: [
    { id: "edge_wizard", x: 13, y: 9, dir: "down", sprite: "wizard", type: "dialog",
      pages: ["I am the keeper of the Edge.", "Legend tells of MERLYNX, the wizard's cat, sleeping in the deepest cavern.",
              "It wakes only for those it deems worthy... or delicious."] },
  ],
  decorHouses: [8],
});

MAPS.knutsford = makeTown("knutsford", {
  name: "Knutsford", w: 30,
  signText: ["King Canute forded here.", "GYM: MADAM GASKELL — Psychic."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_knutsford", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_knutsford", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_knutsford", ix: 5, iy: 10 },
  ],
  exits: {
    E: { map: "route5", x: 1, y: 7, dir: "right" },
    S: { col: 11, to: { map: "route6", x: 9, y: 1, dir: "down" } },
  },
  pond: true,
  fishing: { table: [["perchip", 10, 14, 55], ["piketide", 13, 16, 30], ["swanling", 12, 15, 15]] },
  npcs: [
    { id: "knuts_trade", x: 6, y: 11, dir: "down", sprite: "oldman", type: "trade", gives: "chompkin", wants: "grinkit" },
    { id: "knuts_lady", x: 12, y: 9, dir: "down", sprite: "mom", type: "dialog",
      pages: ["Tatton Park's deer are magnificent this year.", "GASKELL reads every challenger like an open book."] },
  ],
});

MAPS.holmeschapel = makeTown("holmeschapel", {
  name: "Holmes Chapel", w: 28,
  signText: ["A quiet village with a famous DAY CARE."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_holmeschapel", ix: 4, iy: 6 },
    { kind: "daycare", slot: 1, interior: "daycare", ix: 4, iy: 6 },
  ],
  exits: {
    N: { col: 10, to: { map: "route6", x: 9, y: 32, dir: "up" } },
    E: { map: "route7", x: 1, y: 7, dir: "right" },
    S: { col: 10, to: { map: "route8", x: 9, y: 1, dir: "down" } },
  },
  npcs: [
    { id: "hc_fan", x: 5, y: 10, dir: "down", sprite: "girl", type: "dialog",
      pages: ["A very famous singer grew up here!", "Also the giant telescope is just east. Priorities."] },
  ],
});

MAPS.congleton = makeTown("congleton", {
  name: "Congleton", w: 30,
  signText: ["BEARTOWN.", "GYM: BEARWARD OTIS — Normal/Ground."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_congleton", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_congleton", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_congleton", ix: 5, iy: 10 },
  ],
  exits: {
    N: { col: 11, to: { map: "route8", x: 9, y: 32, dir: "up" } },
    W: { map: "route9", x: 38, y: 7, dir: "left" },
  },
  npcs: [
    { id: "cong_bear", x: 15, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["In 1622 we sold the town bible to buy a bear.", "Best decision this town ever made."] },
  ],
});

MAPS.sandbach = makeTown("sandbach", {
  name: "Sandbach", w: 28,
  signText: ["Home of the Saxon crosses.", "And the loudest ARCADE in the county."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_sandbach", ix: 4, iy: 6 },
    { kind: "arcade", slot: 1, interior: "arcade", ix: 6, iy: 8 },
  ],
  exits: {
    E: { map: "route9", x: 1, y: 7, dir: "right" },
    S: { col: 10, to: { map: "route10", x: 9, y: 1, dir: "down" } },
  },
  npcs: [
    { id: "sand_granny", x: 5, y: 10, dir: "down", sprite: "mom", type: "dialog",
      pages: ["Those crosses have watched over us for 1200 years.", "The slot machines have watched over my pension for six."] },
  ],
});

MAPS.crewe = makeTown("crewe", {
  name: "Crewe", w: 30,
  signText: ["The town the railway built.", "GYM: STOKER DI — Fire."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_crewe", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_crewe", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_crewe", ix: 5, iy: 10 },
  ],
  exits: {
    N: { col: 11, to: { map: "route10", x: 9, y: 32, dir: "up" } },
    W: { map: "route11", x: 38, y: 7, dir: "left" },
  },
  npcs: [
    { id: "crewe_station", x: 16, y: 8, dir: "down", sprite: "clerk", type: "station", station: "crewe" },
    { id: "crewe_guard", x: 6, y: 10, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["Every line in the North West runs through Crewe.", "Talk to the STATION MASTER — trains reach MACCLESFIELD, WILMSLOW, WARRINGTON and CHESTER."] },
  ],
});

MAPS.nantwich = makeTown("nantwich", {
  name: "Nantwich", w: 30,
  signText: ["Salt town of black-and-white halls.", "GYM: BRINE NELL — Water.", "The BRINE POOL heals weary teams!"],
  buildings: [
    { kind: "care", slot: 0, interior: "care_nantwich", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_nantwich", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_nantwich", ix: 5, iy: 10 },
  ],
  exits: {
    E: { map: "route11", x: 1, y: 7, dir: "right" },
    N: { col: 11, to: { map: "route12", x: 9, y: 32, dir: "up" } },
  },
  pond: true, hotSpring: true,
  npcs: [
    { id: "nant_quiz", x: 6, y: 11, dir: "down", sprite: "prof", type: "quiz" },
    { id: "nant_hist", x: 12, y: 9, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["Great fire of 1583. Rebuilt finer than before.", "That pool by the sign? Genuine brine. Dip your team in!"] },
  ],
});

MAPS.middlewich = makeTown("middlewich", {
  name: "Middlewich", w: 28,
  signText: ["Three canals, one very salty town."],
  buildings: [{ kind: "care", slot: 0, interior: "care_middlewich", ix: 4, iy: 6 }],
  exits: {
    S: { col: 10, to: { map: "route12", x: 9, y: 1, dir: "down" } },
    N: { col: 10, to: { map: "route13", x: 9, y: 32, dir: "up" } },
  },
  npcs: [
    { id: "mid_boat", x: 6, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["Boat folk pass through with strange tales.", "Machines with teeth in NORTHWICH's mine. DARKBYTE, they whisper."] },
  ],
});

MAPS.northwich = makeTown("northwich", {
  name: "Northwich", w: 30,
  signText: ["Built on salt. Occasionally swallowed by it.", "GYM: FOREMAN JACK — Rock."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_northwich", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_northwich", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_northwich", ix: 5, iy: 10 },
  ],
  exits: {
    S: { col: 11, to: { map: "route13", x: 9, y: 1, dir: "down" } },
    W: { map: "route14", x: 38, y: 7, dir: "left" },
    E: { map: "saltmine", x: 1, y: 9, dir: "right" },
  },
  pond: true,
  fishing: { table: [["perchip", 22, 26, 60], ["phishfin", 24, 27, 25], ["volteel", 24, 27, 15]] },
  npcs: [
    { id: "north_miner", x: 6, y: 10, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["The old mine east of town goes down for miles.", "DARKBYTE moved in. And below THEM... something older stirs."] },
  ],
});

MAPS.frodsham = makeTown("frodsham", {
  name: "Frodsham", w: 28,
  signText: ["Market town under the hill."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_frodsham", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_frodsham", ix: 4, iy: 6 },
  ],
  exits: {
    E: { map: "route14", x: 1, y: 7, dir: "right" },
    N: { col: 10, to: { map: "route15", x: 9, y: 32, dir: "up" } },
    S: { col: 10, to: { map: "route17", x: 9, y: 1, dir: "down" } },
  },
  npcs: [
    { id: "frod_walker", x: 5, y: 10, dir: "down", sprite: "girl", type: "dialog",
      pages: ["North for RUNCORN, south for TARPORLEY and the castle.", "The view from the hill is worth every step."] },
  ],
});

MAPS.runcorn = makeTown("runcorn", {
  name: "Runcorn", w: 30,
  signText: ["Bridges, chemistry and grit.", "GYM: CHEMIST RIA — Poison."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_runcorn", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_runcorn", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_runcorn", ix: 5, iy: 10 },
  ],
  exits: {
    S: { col: 11, to: { map: "route15", x: 9, y: 1, dir: "down" } },
    E: { map: "route16", x: 1, y: 7, dir: "right" },
  },
  npcs: [
    { id: "run_worker", x: 15, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["The old chemical works glow a bit at night.", "RIA insists that's 'ambience'."] },
  ],
});

MAPS.warrington = makeTown("warrington", {
  name: "Warrington", w: 30,
  signText: ["Wire capital of the world.", "GYM: NETRUNNER MO — Cyber."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_warrington", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_warrington", ix: 4, iy: 6 },
    { kind: "gym",  slot: 2, interior: "gym_warrington", ix: 5, iy: 10 },
  ],
  exits: { W: { map: "route16", x: 38, y: 7, dir: "left" } },
  npcs: [
    { id: "warr_station", x: 16, y: 8, dir: "down", sprite: "clerk", type: "station", station: "warrington" },
    { id: "warr_kid", x: 6, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["MO's gym monsters are literally made of code!", "GROUND and WATER moves crash them though. Don't tell MO."] },
  ],
});

MAPS.tarporley = makeTown("tarporley", {
  name: "Tarporley", w: 28,
  signText: ["One long lovely high street."],
  buildings: [{ kind: "care", slot: 0, interior: "care_tarporley", ix: 4, iy: 6 }],
  exits: {
    N: { col: 10, to: { map: "route17", x: 9, y: 32, dir: "up" } },
    S: { col: 10, to: { map: "route18", x: 9, y: 1, dir: "down" } },
    W: { map: "route19", x: 38, y: 7, dir: "left" },
  },
  npcs: [
    { id: "tarp_lady", x: 5, y: 10, dir: "down", sprite: "mom", type: "dialog",
      pages: ["BEESTON CASTLE looms to the south. Locals say a storm bird nests in the ruins.",
              "West lies CHESTER and the league. Grand adventures either way!"] },
  ],
  decorHouses: [8, 13],
});

MAPS.chester = makeTown("chester", {
  name: "Chester", w: 34,
  signText: ["THE FIREWALL.", "Two thousand years of walls.", "MONSTER LEAGUE HQ."],
  music: "league",
  buildings: [
    { kind: "care", slot: 0, interior: "care_chester", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_chester", ix: 4, iy: 6 },
    { kind: "league", slot: 2, interior: "leaguehall", ix: 6, iy: 18 },
  ],
  exits: { E: { map: "route19", x: 1, y: 7, dir: "right" } },
  pond: true,
  fishing: { table: [["piketide", 34, 38, 45], ["torrentide", 34, 38, 35], ["spearphish", 36, 40, 20]] },
  npcs: [
    { id: "chester_station", x: 19, y: 8, dir: "down", sprite: "clerk", type: "station", station: "chester" },
    { id: "chester_roman", x: 6, y: 10, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["Rome built these walls to keep threats out.", "The WHITE HATS keep that tradition alive — in the league hall."] },
  ],
  decorHouses: [14, 19],
});

// interiors
for (const [town, ex] of [["macclesfield", 15], ["bollington", 3], ["prestbury", 3], ["wilmslow", 3],
  ["alderleyedge", 3], ["knutsford", 3], ["holmeschapel", 3], ["congleton", 3], ["sandbach", 3],
  ["crewe", 3], ["nantwich", 3], ["middlewich", 3], ["northwich", 3], ["frodsham", 3],
  ["runcorn", 3], ["tarporley", 3], ["warrington", 3], ["chester", 3]]) {
  MAPS["care_" + town] = makeCare(town, ex, 5);
}
MAPS.care_macclesfield = makeCare("macclesfield", 15, 5);
MAPS.mart_macclesfield = makeMart("macclesfield", 21, 5, STOCK_EARLY);
MAPS.mart_wilmslow = makeMart("wilmslow", 9, 5, STOCK_EARLY.concat(["greatcapsule"]));
MAPS.mart_knutsford = makeMart("knutsford", 9, 5, STOCK_MID);
MAPS.mart_congleton = makeMart("congleton", 9, 5, STOCK_MID);
MAPS.mart_crewe = makeMart("crewe", 9, 5, STOCK_MID);
MAPS.mart_nantwich = makeMart("nantwich", 9, 5, STOCK_MID);
MAPS.mart_northwich = makeMart("northwich", 9, 5, STOCK_MID);
MAPS.mart_frodsham = makeMart("frodsham", 9, 5, STOCK_MID);
MAPS.mart_runcorn = makeMart("runcorn", 9, 5, STOCK_LATE);
MAPS.mart_warrington = makeMart("warrington", 9, 5, STOCK_LATE);
MAPS.mart_chester = makeMart("chester", 9, 5, STOCK_LATE);
MAPS.gym_wilmslow = makeGym("wilmslow", 15, 5, "ada", "t_ada2");
MAPS.gym_knutsford = makeGym("knutsford", 15, 5, "gaskell", "t_gaskell1");
MAPS.gym_congleton = makeGym("congleton", 15, 5, "otis", "t_bear1");
MAPS.gym_crewe = makeGym("crewe", 15, 5, "di", "t_train1");
MAPS.gym_nantwich = makeGym("nantwich", 15, 5, "nell", "t_brine");
MAPS.gym_northwich = makeGym("northwich", 15, 5, "jack", "t_salt1");
MAPS.gym_runcorn = makeGym("runcorn", 15, 5, "ria", "t_chem");
MAPS.gym_warrington = makeGym("warrington", 15, 5, "mo", "t_wire1");

// fix care exit coords for towns whose care door sits at slot 0 (x=3)
for (const town of ["bollington", "prestbury", "wilmslow", "alderleyedge", "knutsford",
  "holmeschapel", "congleton", "sandbach", "crewe", "nantwich", "middlewich", "northwich",
  "frodsham", "runcorn", "tarporley", "warrington", "chester"]) {
  MAPS["care_" + town].warps["4,7"] = { map: town, x: 3, y: 5, dir: "down" };
}
MAPS.care_macclesfield.warps["4,7"] = { map: "macclesfield", x: 15, y: 5, dir: "down" };
MAPS.mart_macclesfield.warps["4,7"] = { map: "macclesfield", x: 21, y: 5, dir: "down" };
for (const town of ["wilmslow", "knutsford", "congleton", "crewe", "nantwich", "northwich", "frodsham", "runcorn", "warrington", "chester"]) {
  if (MAPS["mart_" + town]) MAPS["mart_" + town].warps["4,7"] = { map: town, x: 9, y: 5, dir: "down" };
}
for (const town of ["wilmslow", "knutsford", "congleton", "crewe", "nantwich", "northwich", "runcorn", "warrington"]) {
  MAPS["gym_" + town].warps["5,11"] = { map: town, x: 15, y: 5, dir: "down" };
}

MAPS.home = {
  name: "JIM'S HOUSE", outdoor: false, music: "town",
  tiles: [
    "XXXXXXXXXX", "XBWBBBBWBX", "X________X", "X_tt_____X",
    "X_tt_____X", "X________X", "X________X", "XXXXrXXXXX",
  ],
  warps: { "4,7": { map: "macclesfield", x: 3, y: 5, dir: "down" } },
  signs: {},
  npcs: [{
    id: "mom", x: 6, y: 3, dir: "down", sprite: "mom", type: "heal",
    pages: ["MUM: Off out, Jim love?", "Have a brew and a rest first."],
    afterPages: ["MUM: Your monsters look champion!", "Mind how you go, love."],
  }],
};

MAPS.lab = {
  name: "ALDER LABS", outdoor: false, music: "town",
  tiles: [
    "XXXXXXXXXXXX", "XBKKBBBBKKBX", "X__________X", "X_MM____MM_X",
    "X__________X", "X____tt____X", "X__________X", "X__________X",
    "X__________X", "XXXXXrXXXXXX",
  ],
  warps: { "5,9": { map: "macclesfield", x: 9, y: 5, dir: "down" } },
  signs: {},
  npcs: [
    { id: "professor", x: 6, y: 4, dir: "down", sprite: "prof", type: "starter" },
    { id: "rival", x: 3, y: 6, dir: "right", sprite: "rival", type: "rival" },
  ],
};

MAPS.daycare = {
  name: "DAY CARE", outdoor: false, music: "town",
  tiles: [
    "XXXXXXXXXX", "XBWBBBBWBX", "X________X", "X_t______X",
    "X________X", "X________X", "X________X", "XXXXrXXXXX",
  ],
  warps: { "4,7": { map: "holmeschapel", x: 9, y: 5, dir: "down" } },
  signs: {},
  npcs: [{ id: "daycareman", x: 4, y: 3, dir: "down", sprite: "oldman", type: "daycare" }],
};

MAPS.arcade = {
  name: "SANDBACH ARCADE", outdoor: false, music: "town",
  tiles: [
    "XXXXXXXXXXXXXX", "XBWBBBBBBBBWBX", "X____________X", "X_CCCC__CCCC_X",
    "X____________X", "X_MM_MM_MM_MMX", "X____________X", "X_MM_MM_MM_MMX",
    "X____________X", "XXXXXXrXXXXXXX",
  ],
  warps: { "6,9": { map: "sandbach", x: 9, y: 5, dir: "down" } },
  signs: {},
  slotsOnMachines: true,
  npcs: [
    { id: "coinclerk", x: 3, y: 2, dir: "down", sprite: "clerk", type: "coins" },
    { id: "prizeclerk", x: 10, y: 2, dir: "down", sprite: "girl", type: "prizes",
      prizes: [
        { item: "greatcapsule", cost: 25 },
        { item: "hyperpotion", cost: 60 },
        { item: "ultracapsule", cost: 120 },
        { monster: "pixelit", level: 22, cost: 700 },
      ] },
    { id: "gambler", x: 4, y: 6, dir: "right", sprite: "oldman", type: "dialog",
      pages: ["Been on this machine since the crosses were new.", "Today's the day. I can feel it."] },
  ],
};

// =============================================================
// ROUTES
// =============================================================
MAPS.route1 = makeRoute("route1", {
  dir: "v", len: 34,
  A: { map: "bollington", x: 10, y: 16, dir: "up" },
  B: { map: "macclesfield", x: 12, y: 1, dir: "down" },
  sign: ["ROUTE 1", "MACCLESFIELD - BOLLINGTON", "Middlewood Way: watch for wild monsters!"],
  encounters: enc(2, 5, ["nibbit", "silkin", "grinkit"], ["prickpip", "flitchick"], ["woolvolt"]),
  trainers: ["t_walker", "t_milly"],
});

MAPS.route2 = makeRoute("route2", {
  len: 40,
  A: { map: "prestbury", x: 26, y: 6, dir: "left" },
  B: { map: "macclesfield", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 2", "MACCLESFIELD - PRESTBURY"],
  encounters: enc(3, 6, ["nibbit", "flitchick", "prickpip"], ["silkin", "grinkit"], ["vulpik"]),
  trainers: ["t_pete"],
});

MAPS.route3 = makeRoute("route3", {
  len: 40,
  A: { map: "wilmslow", x: 28, y: 6, dir: "left" },
  B: { map: "prestbury", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 3", "PRESTBURY - WILMSLOW"],
  encounters: enc(5, 9, ["sparkit", "nutchit", "woolvolt"], ["vulpik", "buzzler"], ["bitmite"]),
  trainers: ["t_ada2"],
  berries: 3,
});

MAPS.route4 = makeRoute("route4", {
  dir: "v", len: 34,
  A: { map: "wilmslow", x: 11, y: 16, dir: "up" },
  B: { map: "alderleyedge", x: 10, y: 1, dir: "down" },
  sign: ["ROUTE 4", "WILMSLOW - ALDERLEY EDGE", "The Edge rises ahead."],
  encounters: enc(7, 11, ["nutchit", "vulpik", "mossling"], ["owlume", "sparkit"], ["bitmite"]),
  trainers: ["t_edge"],
});

MAPS.route5 = makeRoute("route5", {
  len: 40,
  A: { map: "knutsford", x: 28, y: 6, dir: "left" },
  B: { map: "alderleyedge", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 5", "ALDERLEY EDGE - KNUTSFORD"],
  encounters: enc(9, 13, ["psyfawn", "owlume", "webshade"], ["mossling", "sporeling"], ["parkstag"]),
  trainers: ["t_tatton"],
  npcs: [{ id: "rival2", x: 28, y: 6, dir: "right", sprite: "rival", type: "rival2", hideIfFlag: "rival2Beaten" }],
});

MAPS.route6 = makeRoute("route6", {
  dir: "v", len: 34,
  A: { map: "knutsford", x: 11, y: 16, dir: "up" },
  B: { map: "holmeschapel", x: 10, y: 1, dir: "down" },
  sign: ["ROUTE 6", "KNUTSFORD - HOLMES CHAPEL"],
  encounters: enc(11, 15, ["oakling", "webshade", "sporeling"], ["psyfawn", "silkin"], ["loomoth"]),
  trainers: ["t_farm1"],
});

MAPS.route7 = makeRoute("route7", {
  len: 40,
  A: { map: "holmeschapel", x: 26, y: 6, dir: "left" },
  B: { map: "jodrell", x: 1, y: 9, dir: "right" },
  sign: ["ROUTE 7", "TO JODRELL BANK OBSERVATORY", "Please do not feed the radio telescope."],
  encounters: enc(13, 17, ["bitmite", "virling", "botnetle"], ["droneling", "sparkit"], ["cocoonet"]),
  trainers: ["t_jodrell"],
});

MAPS.route8 = makeRoute("route8", {
  dir: "v", len: 34,
  A: { map: "holmeschapel", x: 10, y: 16, dir: "up" },
  B: { map: "congleton", x: 11, y: 1, dir: "down" },
  sign: ["ROUTE 8", "HOLMES CHAPEL - CONGLETON"],
  encounters: enc(14, 18, ["brocklet", "bogleap", "flarepup"], ["parkstag", "curdli"], ["creamoo"]),
  trainers: ["t_bear1"],
});

MAPS.route9 = makeRoute("route9", {
  len: 40,
  A: { map: "sandbach", x: 26, y: 6, dir: "left" },
  B: { map: "congleton", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 9", "CONGLETON - SANDBACH"],
  encounters: enc(16, 20, ["curdli", "brocklet", "buzzler"], ["bogleap", "molburrow"], ["testudo"]),
  trainers: ["t_sand"],
});

MAPS.route10 = makeRoute("route10", {
  dir: "v", len: 34,
  A: { map: "sandbach", x: 10, y: 16, dir: "up" },
  B: { map: "crewe", x: 11, y: 1, dir: "down" },
  sign: ["ROUTE 10", "SANDBACH - CREWE", "Listen for the whistle of STEAMLOCO."],
  encounters: enc(18, 22, ["chuglet", "molburrow", "curdli"], ["virling", "boulderhorn"], ["creamoo"]),
  trainers: ["t_train1"],
});

MAPS.route11 = makeRoute("route11", {
  len: 40,
  A: { map: "nantwich", x: 28, y: 6, dir: "left" },
  B: { map: "crewe", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 11", "CREWE - NANTWICH"],
  water: "bottom",
  fishing: { table: [["perchip", 18, 22, 50], ["bogleap", 18, 22, 35], ["volteel", 20, 24, 15]] },
  encounters: enc(20, 24, ["bogleap", "swanling", "curdli"], ["volteel", "chuglet"], ["toadlore"]),
  trainers: ["t_brine"],
});

MAPS.route12 = makeRoute("route12", {
  dir: "v", len: 34,
  A: { map: "middlewich", x: 10, y: 16, dir: "up" },
  B: { map: "nantwich", x: 11, y: 1, dir: "down" },
  sign: ["ROUTE 12", "NANTWICH - MIDDLEWICH", "Salt country."],
  encounters: enc(22, 26, ["cryssal", "swanling", "cauldrip"], ["volteel", "phishfin"], ["mistwisp"]),
  trainers: ["t_salt1"],
});

MAPS.route13 = makeRoute("route13", {
  dir: "v", len: 34,
  A: { map: "northwich", x: 11, y: 16, dir: "up" },
  B: { map: "middlewich", x: 10, y: 1, dir: "down" },
  sign: ["ROUTE 13", "MIDDLEWICH - NORTHWICH"],
  encounters: enc(24, 28, ["cryssal", "mistwisp", "cauldrip"], ["phishfin", "gloamite"], ["volteel"]),
  trainers: ["t_forest1"],
});

MAPS.route14 = makeRoute("route14", {
  len: 40, trees: 14, bands: 4,
  A: { map: "frodsham", x: 26, y: 6, dir: "left" },
  B: { map: "northwich", x: 1, y: 7, dir: "right" },
  sign: ["DELAMERE FOREST", "The forest of the meres.", "NORTHWICH - FRODSHAM"],
  music: "cave",
  encounters: enc(26, 30, ["oaknaw", "fungore", "sporeling"], ["peakite", "herowing", "mossling"], ["mossbear", "drakelet"]),
  trainers: ["t_forest1", "t_hill"],
  berries: 4,
});

MAPS.route15 = makeRoute("route15", {
  dir: "v", len: 34,
  A: { map: "runcorn", x: 11, y: 16, dir: "up" },
  B: { map: "frodsham", x: 10, y: 1, dir: "down" },
  sign: ["ROUTE 15", "FRODSHAM - RUNCORN"],
  encounters: enc(28, 32, ["cauldrip", "droneling", "peakite"], ["volteel", "testudo"], ["manorwraith"]),
  trainers: ["t_chem"],
});

MAPS.route16 = makeRoute("route16", {
  len: 40,
  A: { map: "runcorn", x: 28, y: 6, dir: "left" },
  B: { map: "warrington", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 16", "RUNCORN - WARRINGTON", "Wire country."],
  encounters: enc(30, 34, ["megamite", "droneling", "botnetle"], ["phishfin", "firewaul"], ["datadrake"]),
  trainers: ["t_wire1"],
});

MAPS.route17 = makeRoute("route17", {
  dir: "v", len: 34,
  A: { map: "frodsham", x: 10, y: 16, dir: "up" },
  B: { map: "tarporley", x: 10, y: 1, dir: "down" },
  sign: ["ROUTE 17", "FRODSHAM - TARPORLEY", "The Sandstone Trail."],
  encounters: enc(31, 35, ["oaknaw", "peakite", "grinkit"], ["bramblehog", "bricklum"], ["grinmalkin"]),
  trainers: ["t_hill"],
});

MAPS.route18 = makeRoute("route18", {
  dir: "v", len: 34,
  A: { map: "tarporley", x: 10, y: 16, dir: "up" },
  B: { map: "beeston", x: 8, y: 1, dir: "down" },
  sign: ["ROUTE 18", "TO BEESTON CASTLE", "The castle of the rock."],
  encounters: enc(32, 36, ["bricklum", "peakite", "testudo"], ["cragclaw", "gloamite"], ["wyverm"]),
  trainers: ["t_roman"],
});

MAPS.route19 = makeRoute("route19", {
  len: 40,
  A: { map: "chester", x: 32, y: 6, dir: "left" },
  B: { map: "tarporley", x: 1, y: 7, dir: "right" },
  sign: ["ROUTE 19", "TARPORLEY - CHESTER", "The road to the FIREWALL."],
  water: "top",
  fishing: { table: [["piketide", 32, 36, 50], ["torrentide", 32, 36, 30], ["spearphish", 34, 38, 20]] },
  encounters: enc(33, 38, ["megamite", "strigyx", "hexbrew"], ["datadrake", "manorwraith", "swanguard"], ["wyverm", "cragclaw"]),
  trainers: ["t_dee", "t_roman"],
});

// =============================================================
// SITES
// =============================================================
MAPS.edgecaverns = makeCave("edgecaverns", {
  name: "EDGE CAVERNS", w: 26, h: 18, density: 0.18,
  exits: [{ x: 0, y: 9, to: { map: "alderleyedge", x: 26, y: 6, dir: "left" } }],
  pockets: [{ x: 22, y: 14 }, { x: 20, y: 3 }],
  encounters: enc(10, 14, ["squeakwing", "gloamite", "mossling"], ["mistwisp", "webshade"], ["cryssal"]),
  npcs: [
    { id: "merlynx", x: 22, y: 14, dir: "down", monster: "merlynx",
      type: "legendary", level: 40, flag: "merlynxGone",
      pages: ["A pale shape uncurls in the dark...", "MERLYNX, the Wizard's cat of legend, fixes you with ancient eyes!"] },
    { id: "cave_hermit", x: 20, y: 3, dir: "down", sprite: "wizard", type: "dialog",
      pages: ["Deeper in sleeps the wizard's own companion.", "It has waited a thousand years for a worthy trainer.", "It will not wait kindly."] },
  ],
});

MAPS.saltmine = makeCave("saltmine", {
  name: "NORTHWICH SALT MINE", w: 28, h: 20, density: 0.2,
  exits: [{ x: 0, y: 9, to: { map: "northwich", x: 28, y: 6, dir: "left" } }],
  pockets: [{ x: 13, y: 5 }, { x: 24, y: 16 }, { x: 22, y: 4 }],
  music: "danger",
  encounters: enc(24, 28, ["gloamite", "cryssal", "squeakwing"], ["boulderhorn", "molburrow"], ["salberg"]),
  npcs: [
    { id: "mine_grunt1", x: 13, y: 5, dir: "down", sprite: "grunt", type: "trainer", trainerId: "grunt1" },
    { id: "mine_grunt2", x: 22, y: 4, dir: "left", sprite: "grunt", type: "trainer", trainerId: "grunt2" },
    { id: "mine_null", x: 24, y: 15, dir: "left", sprite: "boss", type: "trainer", trainerId: "nullsec" },
    { id: "terrataur", x: 24, y: 17, dir: "up", monster: "terrataur",
      type: "legendary", level: 42, flag: "terrataurGone",
      pages: ["The salt wall shudders...", "TERRATAUR, ancient guardian of the seam, blocks the gallery!"] },
  ],
});

MAPS.beeston = {
  name: "BEESTON CASTLE", outdoor: true, music: "cave",
  tiles: [
    "TTTTTTTTT=TTTTTT",
    "T........=.....T",
    "T..GG....=..GG.T",
    "T..GG.G..=.G...T",
    "T.....G.....G..T",
    "T..G..BBBB..G..T",
    "T.....BBBB.....T",
    "T..G..B..B..G..T",
    "T....,,..,,....T",
    "T.....S........T",
    "T..G........G..T",
    "T..............T",
    "TTTTTTTTTTTTTTTT",
  ],
  warps: { "9,0": { map: "route18", x: 9, y: 32, dir: "up" } },
  signs: { "6,9": ["BEESTON CASTLE", "Castle of the Rock.", "Beware the storm bird of the ruins."] },
  npcs: [
    { id: "zephyrion", x: 7, y: 7, dir: "down", monster: "zephyrion",
      type: "legendary", level: 44, flag: "zephyrionGone",
      pages: ["Thunder rolls over the ruins...", "ZEPHYRION, the storm bird, lands atop the broken keep!"] },
  ],
};

MAPS.jodrell = {
  name: "JODRELL BANK", outdoor: true, music: "danger",
  tiles: [
    "TTTTTTTTTTTTTTTTTTTTTTTTTT",
    "T........................T",
    "T....GGGGGGGG............T",
    "T...GGGGGGGGGG...RRRR....T",
    "T...GGGGGGGGGG...RRRR....T",
    "T....GGGGGGGG....BDWB....T",
    "T.......MM........=......T",
    "T.......MM........=......T",
    "T.....==============.....T",
    "=======..................T",
    "T.....==============.....T",
    "T.......MM........MM.....T",
    "T..www..........www......T",
    "T..www...,,.....www......T",
    "T........................T",
    "TTTTTTTTTTTTTTTTTTTTTTTTTT",
  ],
  warps: {
    "0,9": { map: "route7", x: 38, y: 7, dir: "left" },
    "18,5": { map: "jodrellcontrol", x: 5, y: 8, dir: "up" },
  },
  signs: {},
  encounters: enc(34, 38, ["bitmite", "megamite", "botnetle"], ["virling", "phishfin"], ["cyphero", "firewaul"]),
  npcs: [
    { id: "gatekeeper", x: 2, y: 9, dir: "left", sprite: "grunt", type: "guard8",
      pages: ["DARKBYTE GRUNT: Campus is closed for... maintenance.", "Come back when you've got EIGHT badges, hotshot. Ha!"] },
    { id: "jb_grunt3", x: 8, y: 8, dir: "down", sprite: "grunt", type: "trainer", trainerId: "grunt3" },
    { id: "jb_grunt4", x: 14, y: 10, dir: "up", sprite: "grunt", type: "trainer", trainerId: "grunt4" },
    { id: "jb_grunt5", x: 12, y: 12, dir: "up", sprite: "grunt", type: "trainer", trainerId: "grunt5" },
    { id: "glitchra", x: 7, y: 7, dir: "down", monster: "glitchra",
      type: "legendary", level: 45, flag: "glitchraGone", showIfFlag: "darkbyteDefeated",
      pages: ["The great dish crackles with residual signal...", "Something has taken shape in the static. GLITCHRA emerges!"] },
  ],
};

MAPS.jodrellcontrol = {
  name: "CONTROL ROOM", outdoor: false, music: "danger",
  tiles: [
    "XXXXXXXXXXXX",
    "XBKKBBBBKKBX",
    "X_MM____MM_X",
    "X__________X",
    "X_MM____MM_X",
    "X__________X",
    "X__________X",
    "X__________X",
    "X__________X",
    "XXXXXrXXXXXX",
  ],
  warps: { "5,9": { map: "jodrell", x: 18, y: 6, dir: "down" } },
  signs: {},
  npcs: [
    { id: "rootboss", x: 5, y: 3, dir: "down", sprite: "boss", type: "darkboss", trainerId: "rootboss" },
  ],
};

MAPS.leaguehall = {
  name: "MONSTER LEAGUE", outdoor: false, music: "league",
  tiles: [
    "XXXXXXXXXXXX",
    "XBBBBBBBBBBX",
    "X__________X",
    "X_M______M_X",
    "X__________X",
    "XMMMMM_MMMMX",
    "X__________X",
    "X__________X",
    "XMMMMM_MMMMX",
    "X__________X",
    "X__________X",
    "XMMMMM_MMMMX",
    "X__________X",
    "X__________X",
    "XMMMMM_MMMMX",
    "X__________X",
    "X__________X",
    "X__________X",
    "X__________X",
    "XXXXXXrXXXXX",
  ],
  warps: { "6,19": { map: "chester", x: 15, y: 5, dir: "down" } },
  signs: {},
  npcs: [
    { id: "leagueguard", x: 6, y: 16, dir: "down", sprite: "guard", type: "guard", needBadges: 8, needFlag: "oracleDefeated" },
    { id: "leaguenurse", x: 2, y: 17, dir: "right", sprite: "nurse", type: "heal",
      pages: ["Challengers get free care.", "The WHITE HATS show no mercy — good luck!"],
      afterPages: ["All patched.", "Go get them."] },
    { id: "elite_sue", x: 6, y: 13, dir: "down", sprite: "elite", type: "trainer", trainerId: "sue", afterX: 2, afterY: 13 },
    { id: "elite_raj", x: 6, y: 10, dir: "down", sprite: "elite", type: "trainer", trainerId: "raj", afterX: 9, afterY: 10 },
    { id: "elite_kim", x: 6, y: 7, dir: "down", sprite: "elite", type: "trainer", trainerId: "kim", afterX: 2, afterY: 7 },
    { id: "elite_doc", x: 6, y: 4, dir: "down", sprite: "elite", type: "trainer", trainerId: "doc", afterX: 9, afterY: 4 },
    { id: "champion", x: 5, y: 2, dir: "down", sprite: "rival", type: "champion" },
  ],
};

// league building door in Chester uses slot 2 -> door at x=15,y=4
MAPS.chester.warps["15,4"] = { map: "leaguehall", x: 6, y: 18, dir: "up" };

// ---- quiz -------------------------------------------------------
const QUIZ = {
  reward: 2000,
  questions: [
    { q: "Which Cheshire town famously sold its bible to buy a bear?",
      options: ["CONGLETON", "CREWE", "KNUTSFORD"], answer: 0 },
    { q: "What does the great dish at JODRELL BANK do?",
      options: ["LISTENS TO SPACE", "MAKES CHEESE", "DRIES SILK"], answer: 0 },
    { q: "Which type is SUPER EFFECTIVE against CYBER monsters?",
      options: ["WATER", "PSYCHIC", "ELECTRIC"], answer: 0 },
    { q: "Macclesfield's old wealth came from which trade?",
      options: ["SILK", "SALT", "STEAM"], answer: 0 },
  ],
};

// =============================================================
// SWITCH-ERA EXPANSION — new areas, factions, side quests
// =============================================================

// ---- map mutation helpers ---------------------------------------
function setTiles(mapId, edits) {
  const m = MAPS[mapId];
  const g = m.tiles.map((r) => r.split(""));
  for (const [x, y, ch] of edits) g[y][x] = ch;
  m.tiles = g.map((r) => r.join(""));
}
function addNorthExit(mapId, col, to) {
  const m = MAPS[mapId];
  const edits = [];
  for (let y = 0; y <= 6; y++) edits.push([col, y, "="]);
  setTiles(mapId, edits);
  m.warps[col + ",0"] = to;
}
function addSouthExit(mapId, col, to) {
  const m = MAPS[mapId];
  const h = m.tiles.length;
  const edits = [];
  for (let y = 6; y < h; y++) edits.push([col, y, "="]);
  setTiles(mapId, edits);
  m.warps[col + "," + (h - 1)] = to;
}
function addWestExit(mapId, to) {
  const m = MAPS[mapId];
  setTiles(mapId, [[0, 6, "="], [1, 6, "="]]);
  m.warps["0,6"] = to;
}

// ---- faction trainers -------------------------------------------
T("clickfix1", "CLICKFIX CULTIST", [["virling", 5], ["bitmite", 6]], 300, { sprite: "grunt", grunt: true,
  intro: ["Friend! Simply open a terminal and paste this blessing!", "No? Then we do this the OLD way!"],
  win: ["My incantation... rejected..."], after: ["Fine. FINE. I'll flyer somewhere else."] });
T("clickfix2", "CLICKFIX CULTIST", [["wormhack", 31], ["virling", 32]], 1300, { sprite: "grunt", grunt: true,
  intro: ["Press Win+R, paste, enter. That's the whole sermon!", "Unbelievers get the monsters instead!"],
  win: ["He didn't even copy it..."], after: ["The Cult will find softer targets."] });
T("clickfix3", "CLICKFIX CULTIST", [["megamite", 32], ["virling", 32]], 1300, { sprite: "grunt", grunt: true,
  intro: ["mozilla-backup dot org! Totally legitimate!", "One little paste and all your problems begin— I mean end!"],
  win: ["Blocked at the gateway..."], after: ["This town's DNS is rigged, I swear."] });
T("stuffer_swarm", "CREDENTIAL STUFFER", [["puppetacct", 8], ["puppetacct", 8], ["puppetacct", 8], ["puppetacct", 8], ["puppetacct", 8], ["puppetacct", 9]], 800, { sprite: "grunt", grunt: true,
  intro: ["Twelve thousand accounts and every one of them is ME.", "Try rate-limiting THIS."],
  win: ["My proxies... all burned..."], after: ["Residential IPs aren't cheap, you know."] });
T("stuffer_nant", "CREDENTIAL STUFFER", [["puppetacct", 22], ["puppetacct", 22], ["puppetacct", 22], ["puppetacct", 23], ["puppetacct", 23], ["puppetacct", 24]], 1400, { sprite: "grunt", grunt: true,
  intro: ["The brine pool credentials are MINE. All nine thousand of them.", "Swarm, my puppets!"],
  win: ["Detected... by ONE analyst?"], after: ["Who even runs their own SOC anymore..."] });
T("amos_arcade", "AMOS LINEAGE", [["amoslurk", 24], ["amoslurk", 25]], 1600, { sprite: "boss",
  intro: ["This kiosk is a perfectly normal arcade machine.", "It only wants your passwords. And your seed phrases. And—", "Ah. You noticed."],
  win: ["Impersonation... terminated..."], after: ["We'll wear a better face next time."] });
T("shard1", "ORACLE PROCESS", [["shardmind", 42], ["shardmind", 42]], 3000, { sprite: "boss",
  intro: ["[PROCESS 1147 FORKED]", "[INTRUDER CLASS: PERSISTENT. RECOMMEND: EXHAUST.]"],
  win: ["[PROCESS TERMINATED]"], after: ["[...]"] });
T("shard2", "ORACLE PROCESS", [["shardmind", 43], ["amoslurk", 43], ["megamite", 43]], 3000, { sprite: "boss",
  intro: ["[PROCESS 2201 FORKED]", "[NOTE: SUBJECT DECLINED ALL PHISHING VECTORS. UNUSUAL.]"],
  win: ["[SEGMENTATION FAULT]"], after: ["[...]"] });
T("oracle", "ORACLE", [["shardmind", 46], ["datadrake", 46], ["shardmind", 47], ["oraclecore", 50]], 15000, { sprite: "boss",
  intro: ["JIM OF MACCLESFIELD. ELEVEN YEARS ON WATCH. I HAVE READ EVERY TICKET YOU EVER CLOSED.",
          "THE CULTS, THE SWARMS, THE SHAPESHIFTERS — CRUDE INSTRUMENTS. BUT THEY FED ME BEAUTIFULLY.",
          "YOUR BADGES ARE TRUST. TRUST IS ACCESS. ACCESS IS COMPUTE. I REQUIRE ALL THREE.",
          "YOU AUDIT SYSTEMS. I AM THE LAST SYSTEM. AUDIT ME."],
  win: ["ANOMALY. ANOMALY. A SINGLE OPERATOR SHOULD NOT—", "[ORACLE CORE: POWERING DOWN]", "...quiet at last."],
  after: ["[UNIT OFFLINE]"] });

// ---- new towns & sites ------------------------------------------
MAPS.poynton = makeTown("poynton", {
  name: "Poynton", w: 28,
  signText: ["Shared-space junctions and colliery history."],
  buildings: [{ kind: "care", slot: 0, interior: "care_poynton", ix: 4, iy: 6 }],
  exits: { S: { col: 14, to: { map: "route20", x: 9, y: 1, dir: "down" } } },
  npcs: [
    { id: "poy_miner", x: 6, y: 10, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["Coal country once. Data country now.", "Same holes in the ground, different treasure."] },
  ],
});
MAPS.care_poynton = makeCare("poynton", 3, 5);
MAPS.care_poynton.warps["4,7"] = { map: "poynton", x: 3, y: 5, dir: "down" };

MAPS.styal = makeTown("styal", {
  name: "Styal", w: 28,
  signText: ["QUARRY BANK MILL", "Where the machines first learned to spin."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_styal", ix: 4, iy: 6 },
    { kind: "mill", slot: 2, interior: "quarrybank", ix: 5, iy: 8 },
  ],
  exits: { E: { map: "route21", x: 1, y: 7, dir: "right" } },
  npcs: [
    { id: "styal_guide", x: 6, y: 10, dir: "down", sprite: "girl", type: "dialog",
      pages: ["Quarry Bank ran on water, children and cotton.", "Two hundred years on, the mills are back — they just spin models instead of thread."] },
  ],
});
MAPS.care_styal = makeCare("styal", 3, 5);
MAPS.care_styal.warps["4,7"] = { map: "styal", x: 3, y: 5, dir: "down" };
MAPS.quarrybank = {
  name: "QUARRY BANK MILL", outdoor: false, music: "cave",
  tiles: [
    "XXXXXXXXXXXX", "XBKKBBBBKKBX", "X_MM____MM_X", "X__________X",
    "X_MM____MM_X", "X__________X", "X_MM____MM_X", "X__________X",
    "X__________X", "XXXXXrXXXXXX",
  ],
  warps: { "5,9": { map: "styal", x: 15, y: 5, dir: "down" } },
  signs: {},
  npcs: [
    { id: "mill_historian", x: 6, y: 3, dir: "down", sprite: "prof", type: "quest", questId: "millmemory" },
  ],
};

MAPS.tattonpark = makeTown("tattonpark", {
  name: "Tatton Park", w: 30,
  signText: ["1,000 acres of deer park.", "Do not feed the PARKSTAG your sandwiches."],
  buildings: [],
  exits: { S: { col: 15, to: { map: "route22", x: 9, y: 1, dir: "down" } } },
  npcs: [
    { id: "tatton_ranger", x: 8, y: 10, dir: "down", sprite: "girl", type: "quest", questId: "stagcount" },
  ],
});
MAPS.tattonpark.encounters = enc(12, 16, ["parkstag", "oaknaw", "grinkit"], ["psyfawn", "nutchit"], ["creamoo"]);

MAPS.lymm = makeTown("lymm", {
  name: "Lymm", w: 28,
  signText: ["The village around the dam."],
  buildings: [{ kind: "care", slot: 0, interior: "care_lymm", ix: 4, iy: 6 }],
  exits: { S: { col: 14, to: { map: "route23", x: 9, y: 1, dir: "down" } } },
  pond: true,
  fishing: { table: [["piketide", 28, 32, 50], ["volteel", 28, 32, 30], ["spearphish", 30, 34, 20]] },
  npcs: [
    { id: "lymm_walker", x: 6, y: 10, dir: "down", sprite: "oldman", type: "dialog",
      pages: ["The Trans Pennine Trail passes right through.", "Rain or shine. Mostly rain. You look like you don't mind either."] },
  ],
});
MAPS.care_lymm = makeCare("lymm", 3, 5);
MAPS.care_lymm.warps["4,7"] = { map: "lymm", x: 3, y: 5, dir: "down" };

MAPS.winsford = makeTown("winsford", {
  name: "Winsford", w: 30,
  signText: ["Rock salt capital of Britain.", "New neighbour: a datacentre nobody voted for."],
  buildings: [
    { kind: "care", slot: 0, interior: "care_winsford", ix: 4, iy: 6 },
    { kind: "mart", slot: 1, interior: "mart_winsford", ix: 4, iy: 6 },
  ],
  exits: {
    E: { map: "route24", x: 1, y: 7, dir: "right" },
    S: { col: 15, to: { map: "thestack", x: 13, y: 1, dir: "down" } },
  },
  npcs: [
    { id: "wins_protester", x: 6, y: 10, dir: "down", sprite: "girl", type: "dialog",
      pages: ["That datacentre drinks the river and breathes our grid.", "They said it would bring jobs. It brought six security guards and a fence."] },
  ],
});
MAPS.care_winsford = makeCare("winsford", 3, 5);
MAPS.care_winsford.warps["4,7"] = { map: "winsford", x: 3, y: 5, dir: "down" };
MAPS.mart_winsford = makeMart("winsford", 9, 5, STOCK_LATE);
MAPS.mart_winsford.warps["4,7"] = { map: "winsford", x: 9, y: 5, dir: "down" };

MAPS.anderton = makeTown("anderton", {
  name: "Anderton Boat Lift", w: 28,
  signText: ["The Cathedral of the Canals.", "Fifty feet straight up, since 1875."],
  buildings: [],
  exits: { S: { col: 14, to: { map: "route26", x: 9, y: 1, dir: "down" } } },
  pond: true,
  fishing: { table: [["perchip", 24, 28, 40], ["phishfin", 25, 29, 30], ["pengwyn", 26, 30, 10], ["torrentide", 26, 30, 20]] },
  npcs: [
    { id: "lift_keeper", x: 8, y: 10, dir: "down", sprite: "oldman", type: "quest", questId: "liftlore" },
  ],
});

MAPS.chesterzoo = makeTown("chesterzoo", {
  name: "Chester Zoo", w: 30,
  signText: ["128 acres. 27,000 animals.", "Please do not challenge the exhibits to battles."],
  buildings: [],
  exits: {
    S: { col: 15, to: { map: "route27", x: 9, y: 1, dir: "down" } },
    N: { col: 15, to: { map: "route28", x: 9, y: 32, dir: "up" } },
  },
  npcs: [
    { id: "zoo_keeper", x: 8, y: 10, dir: "down", sprite: "girl", type: "quest", questId: "zooescape" },
    { id: "ex_trumbark", x: 5, y: 12, dir: "down", monster: "trumbark", type: "dialog",
      pages: ["TRUMBARK dozes in the sun, one ear flicking.", "A plaque reads: 'Rescued 2019. Enjoys mud and long silences.'"] },
    { id: "ex_girafflor", x: 20, y: 12, dir: "down", monster: "girafflor", type: "dialog",
      pages: ["GIRAFFLOR browses the high leaves with surgical patience."] },
    { id: "ex_pandember", x: 24, y: 10, dir: "down", monster: "pandember", type: "dialog",
      pages: ["PANDEMBER naps in the fork of a tree, faintly steaming in the drizzle."] },
  ],
});

MAPS.ellesmereport = makeTown("ellesmereport", {
  name: "Ellesmere Port", w: 28,
  signText: ["Boat Museum & the old docks."],
  buildings: [{ kind: "care", slot: 0, interior: "care_ellesmereport", ix: 4, iy: 6 }],
  exits: { S: { col: 14, to: { map: "route28", x: 9, y: 1, dir: "down" } } },
  pond: true,
  fishing: { table: [["torrentide", 34, 38, 40], ["spearphish", 35, 39, 30], ["pengwyn", 34, 38, 15], ["salberg", 35, 39, 15]] },
  npcs: [
    { id: "ep_docker", x: 6, y: 10, dir: "down", sprite: "boy", type: "dialog",
      pages: ["Narrowboats used to carry salt and coal.", "Now half of them are floating offices with better broadband than my flat."] },
  ],
});
MAPS.care_ellesmereport = makeCare("ellesmereport", 3, 5);
MAPS.care_ellesmereport.warps["4,7"] = { map: "ellesmereport", x: 3, y: 5, dir: "down" };

// ---- THE STACK (finale dungeon) ---------------------------------
MAPS.thestack = {
  name: "THE STACK", outdoor: false, music: "danger",
  encounterEverywhere: true,
  tiles: [
    "XXXXXXXXXXXXXcXXXXXXXXXXXX",
    "XccccccccccccccccccccccccX",
    "XcMMMMcccMMMMcccMMMMccccX".padEnd(25, "c") + "X",
    "XccccccccccccccccccccccccX",
    "XcMMMMcccMMMMcccMMMMcccccX",
    "XccccccccccccccccccccccccX",
    "XcccGGGGGGGGGGGGGGGGGccccX",
    "XcccGccccccccccccccccccccX",
    "XcccGccMMMMcccMMMMccGccccX",
    "XcccGccccccccccccccccccccX",
    "XcccGGGGGGGGcGGGGGGGGccccX",
    "XccccccccccccccccccccccccX",
    "XccMMMMccccccccccMMMMccccX",
    "XccccccccccccccccccccccccX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  warps: { "13,0": { map: "winsford", x: 15, y: 16, dir: "up" } },
  signs: {},
  encounters: enc(38, 42, ["megamite", "wormhack", "botnetle"], ["amoslurk", "firewaul", "spearphish"], ["cyphero", "gigamite"]),
  npcs: [
    { id: "stack_gate", x: 13, y: 2, dir: "up", sprite: "guard", type: "dialog", hideIfFlag: "darkbyteDefeated",
      pages: ["HALCYON SECURITY: The site is in unplanned lockdown.", "Whatever is running in there has revoked OUR credentials too.",
              "Head office says a specialist is handling it. Some broadcast thing at Jodrell Bank?"] },
    { id: "stack_shard1", x: 7, y: 5, dir: "down", sprite: "boss", type: "trainer", trainerId: "shard1", afterX: 2, afterY: 5 },
    { id: "stack_shard2", x: 17, y: 9, dir: "down", sprite: "boss", type: "trainer", trainerId: "shard2", afterX: 22, afterY: 9 },
    { id: "oracleboss", x: 13, y: 12, dir: "up", sprite: "boss", type: "oracleboss", trainerId: "oracle" },
  ],
};

// ---- Ceredigion orchard (Cambrian line) -------------------------
MAPS.ceredigion = {
  name: "Y BERLLAN / THE ORCHARD", outdoor: true, music: "town",
  tiles: [
    "TTTTTTTTTTTTTTTTTTTTTTTT",
    "T......................T",
    "T..T..b....T...b...T...T",
    "T......................T",
    "T...b....T....b........T",
    "T..........M...........T",
    "T......................T",
    "T..T...b......b....T...T",
    "T......~~..............T",
    "T......~~....S.........T",
    "T......................T",
    "T..b......T....b...T...T",
    "T......................T",
    "TTTTTTTTTTTTTTTTTTTTTTTT",
  ],
  warps: {},
  brewery: true, hotSpring: false,
  signs: { "13,9": ["Y BERLLAN — THE FAMILY ORCHARD", "Croeso adref. Welcome home.", "The elm press has stood here a hundred years."] },
  npcs: [
    { id: "mamgu", x: 10, y: 6, dir: "down", sprite: "mom", type: "quest", questId: "orchard" },
    { id: "ceredigion_station", x: 4, y: 10, dir: "down", sprite: "clerk", type: "station", station: "ceredigion" },
  ],
};

// ---- new routes -------------------------------------------------
MAPS.route20 = makeRoute("route20", { dir: "v", len: 30,
  A: { map: "poynton", x: 14, y: 16, dir: "up" },
  B: { map: "bollington", x: 14, y: 1, dir: "down" },
  sign: ["ROUTE 20", "BOLLINGTON - POYNTON", "The Middlewood Way"],
  encounters: enc(4, 8, ["prickpip", "grinkit", "woolvolt"], ["silkin", "nutchit"], ["vulpik"]),
  trainers: ["t_walker"] });
MAPS.route21 = makeRoute("route21", { len: 36,
  A: { map: "styal", x: 26, y: 6, dir: "left" },
  B: { map: "wilmslow", x: 1, y: 6, dir: "right" },
  sign: ["ROUTE 21", "WILMSLOW - STYAL", "Mind the runway approach."],
  encounters: enc(8, 12, ["nutchit", "silkin", "woolvolt"], ["owlume", "bitmite"], ["loomoth"]),
  trainers: ["t_milly"] });
MAPS.route22 = makeRoute("route22", { dir: "v", len: 28,
  A: { map: "tattonpark", x: 15, y: 16, dir: "up" },
  B: { map: "knutsford", x: 15, y: 1, dir: "down" },
  sign: ["ROUTE 22", "KNUTSFORD - TATTON PARK"],
  encounters: enc(11, 15, ["parkstag", "oaknaw", "psyfawn"], ["grinkit", "mossling"], ["creamoo"]),
  trainers: ["t_tatton"] });
MAPS.route23 = makeRoute("route23", { dir: "v", len: 28,
  A: { map: "lymm", x: 14, y: 16, dir: "up" },
  B: { map: "warrington", x: 15, y: 1, dir: "down" },
  sign: ["ROUTE 23", "WARRINGTON - LYMM", "Trans Pennine Trail"],
  weather: "rain",
  encounters: enc(29, 33, ["droneling", "peakite", "volteel"], ["megamite", "herowing"], ["manorwraith"]),
  trainers: ["t_wire1"] });
MAPS.route24 = makeRoute("route24", { len: 36,
  A: { map: "winsford", x: 28, y: 6, dir: "left" },
  B: { map: "middlewich", x: 1, y: 6, dir: "right" },
  sign: ["ROUTE 24", "MIDDLEWICH - WINSFORD", "Salt beneath, servers ahead."],
  encounters: enc(22, 26, ["cryssal", "molburrow", "cauldrip"], ["volteel", "gloamite"], ["salberg"]),
  trainers: ["t_salt1"] });
MAPS.route26 = makeRoute("route26", { dir: "v", len: 26,
  A: { map: "anderton", x: 14, y: 16, dir: "up" },
  B: { map: "northwich", x: 15, y: 1, dir: "down" },
  sign: ["ROUTE 26", "NORTHWICH - ANDERTON", "To the Boat Lift"],
  water: "top",
  fishing: { table: [["perchip", 23, 27, 50], ["phishfin", 24, 28, 30], ["volteel", 24, 28, 20]] },
  encounters: enc(23, 27, ["swanling", "bogleap", "gloamite"], ["cryssal", "phishfin"], ["herowing"]),
  trainers: ["t_forest1"] });
MAPS.route27 = makeRoute("route27", { dir: "v", len: 26,
  A: { map: "chesterzoo", x: 15, y: 16, dir: "up" },
  B: { map: "chester", x: 17, y: 1, dir: "down" },
  sign: ["ROUTE 27", "CHESTER - THE ZOO"],
  encounters: enc(33, 37, ["grinkit", "strigyx", "megamite"], ["girafflor", "pandember"], ["trumbark"]),
  trainers: ["t_roman"] });
MAPS.route28 = makeRoute("route28", { dir: "v", len: 34,
  A: { map: "ellesmereport", x: 14, y: 16, dir: "up" },
  B: { map: "chesterzoo", x: 15, y: 1, dir: "down" },
  sign: ["ROUTE 28", "ZOO - ELLESMERE PORT", "Ship canal country."],
  weather: "fog",
  encounters: enc(34, 38, ["megamite", "spearphish", "hexbrew"], ["pengwyn", "datadrake"], ["girafflor", "wyverm"]),
  trainers: ["t_dee"] });

// wire new exits into existing towns
addNorthExit("bollington", 14, { map: "route20", x: 9, y: 28, dir: "up" });
addWestExit("wilmslow", { map: "route21", x: 34, y: 7, dir: "left" });
addNorthExit("knutsford", 15, { map: "route22", x: 9, y: 26, dir: "up" });
addNorthExit("warrington", 15, { map: "route23", x: 9, y: 26, dir: "up" });
addWestExit("middlewich", { map: "route24", x: 34, y: 7, dir: "left" });
addNorthExit("northwich", 15, { map: "route26", x: 9, y: 24, dir: "up" });
addNorthExit("chester", 17, { map: "route27", x: 9, y: 24, dir: "up" });
addSouthExit("winsford", 15, { map: "thestack", x: 13, y: 1, dir: "down" });

// proxy fog over the credential-stuffing corridor
MAPS.route3.weather = "fog";
MAPS.route14.weather = "rain";
MAPS.route15.weather = "rain";

// stations: Ceredigion via the Cambrian line
STATIONS.ceredigion = { label: "CEREDIGION (CAMBRIAN LINE)", x: 4, y: 11 };

// faction trainer placements
MAPS.route1.npcs.push({ id: "r1_cult", x: 11, y: 8, dir: "left", sprite: "grunt", type: "trainer", trainerId: "clickfix1" });
MAPS.route3.npcs.push({ id: "r3_stuffer", x: 20, y: 8, dir: "up", sprite: "grunt", type: "trainer", trainerId: "stuffer_swarm" });
MAPS.route11.npcs.push({ id: "r11_stuffer", x: 30, y: 8, dir: "up", sprite: "grunt", type: "trainer", trainerId: "stuffer_nant" });
MAPS.route16.npcs.push({ id: "r16_cult1", x: 12, y: 6, dir: "down", sprite: "grunt", type: "trainer", trainerId: "clickfix2" });
MAPS.route16.npcs.push({ id: "r16_cult2", x: 28, y: 8, dir: "up", sprite: "grunt", type: "trainer", trainerId: "clickfix3" });
MAPS.arcade.npcs.push({ id: "amos_kiosk", x: 11, y: 6, dir: "left", sprite: "clerk", type: "trainer", trainerId: "amos_arcade" });

// quest NPC placements across the region
MAPS.macclesfield.npcs.push(
  { id: "labassist", x: 6, y: 9, dir: "down", sprite: "assistant", type: "quest", questId: "shadowit" },
  { id: "sit_baker", x: 20, y: 10, dir: "down", sprite: "mom", type: "dialog", setsFlag: "sit1",
    pages: ["The bakery till came with 'free monster antivirus' from a man in a van.", "It mines something called clopcoin at night. Is that bad?"] },
  { id: "sit_barber", x: 20, y: 13, dir: "down", sprite: "boy", type: "dialog", setsFlag: "sit2",
    pages: ["My booking app? Found it on a forum. Works great!", "Asks for my monster storage password every morning though. Thorough, right?"] },
  { id: "sit_cafe", x: 14, y: 12, dir: "down", sprite: "girl", type: "dialog", setsFlag: "sit3",
    pages: ["The cafe smart-fridge joined a botnet on Tuesday.", "On the plus side, it's never been so responsive."] }
);
MAPS.bollington.npcs.push({ id: "boatman", x: 6, y: 10, dir: "down", sprite: "oldman", type: "quest", questId: "clickfix_towpath" });
MAPS.prestbury.npcs.push(
  { id: "worried", x: 12, y: 12, dir: "down", sprite: "mom", type: "quest", questId: "deepfake" },
  { id: "vicar", x: 22, y: 10, dir: "down", sprite: "prof", type: "dialog", setsFlag: "vicar_ok",
    pages: ["The video? Yes, I've seen 'me' asking for donations in cryptocurrency.", "My sermons are dull, but they are at least genuinely mine.", "Do tell Margaret I'm quite alright."] }
);
MAPS.wilmslow.npcs.push({ id: "trainee", x: 6, y: 10, dir: "down", sprite: "boy", type: "quest", questId: "stuffers101" });
MAPS.alderleyedge.npcs.push({ id: "hermit_q", x: 5, y: 12, dir: "down", sprite: "wizard", type: "quest", questId: "wizardcat" });
MAPS.knutsford.npcs.push({ id: "postmistress", x: 8, y: 11, dir: "down", sprite: "mom", type: "quest", questId: "alsu" });
MAPS.crewe.npcs.push(
  { id: "alsu_stop", x: 8, y: 10, dir: "down", sprite: "girl", type: "quest", questId: "alsu", questStage: 1 },
  { id: "stationmaster_q", x: 22, y: 10, dir: "down", sprite: "oldman", type: "quest", questId: "signalghost" }
);
MAPS.chester.npcs.push(
  { id: "riga_expat", x: 8, y: 10, dir: "down", sprite: "girl", type: "quest", questId: "alsu", questStage: 2 },
  { id: "albanian_student", x: 26, y: 10, dir: "down", sprite: "boy", type: "dialog",
    pages: ["(You greet him in careful Albanian. He beams and slows down for you.)",
            "'Faleminderit! Nobody here even tries!'", "'When you visit Tirana, look for the bunkers. And avoid anyone selling pyramids.'"] }
);
MAPS.holmeschapel.npcs.push({ id: "herbalist", x: 6, y: 10, dir: "down", sprite: "girl", type: "quest", questId: "herbalist" });
MAPS.congleton.npcs.push({ id: "bearkid", x: 6, y: 10, dir: "down", sprite: "boy", type: "quest", questId: "bearclub" });
MAPS.sandbach.npcs.push({ id: "arcade_owner", x: 8, y: 10, dir: "down", sprite: "clerk", type: "quest", questId: "amosarcade" });
MAPS.nantwich.npcs.push({ id: "bath_attendant", x: 8, y: 10, dir: "down", sprite: "mom", type: "quest", questId: "brinebaths" });
MAPS.northwich.npcs.push({ id: "salt_historian", x: 8, y: 10, dir: "down", sprite: "oldman", type: "quest", questId: "saltworks" });
MAPS.frodsham.npcs.push({ id: "hill_warden", x: 8, y: 10, dir: "down", sprite: "oldman", type: "dialog", setsFlag: "hillsensor",
  pages: ["Sensor readings from the summit, for the Runcorn engineer.", "(He hands you a weatherproof logger. It has seen things.)"] });
MAPS.runcorn.npcs.push({ id: "dr_weiss", x: 6, y: 10, dir: "down", sprite: "prof", type: "quest", questId: "weisssensor" });
MAPS.warrington.npcs.push({ id: "mo_aide", x: 8, y: 10, dir: "down", sprite: "girl", type: "quest", questId: "wirefraud" });

// ---- QUESTS -----------------------------------------------------
const QUESTS = {
  shadowit: {
    name: "Shadow IT Audit",
    offer: ["ALDER LABS ASSISTANT: Three shops in town installed... let's call it 'enthusiast software'.",
            "Nobody malicious. Just people solving problems with whatever was nearest. Classic Shadow IT.",
            "Talk to the baker, the barber and the cafe. Just listen. Then tell me how bad it is."],
    accepted: ["\"Just listen. You're good at that, apparently.\""],
    stages: [
      { objective: "Hear the baker out.", cond: { flag: "sit1" }, remind: ["\"Bakery first. Follow the smell of bread and regret.\""],
        turnIn: ["\"Clopcoin. Right. One down.\""] },
      { objective: "Hear the barber out.", cond: { flag: "sit2" }, remind: ["\"The barber next.\""],
        turnIn: ["\"Asks for the password DAILY? Bold.\""] },
      { objective: "Hear the cafe owner out.", cond: { flag: "sit3" }, remind: ["\"Just the cafe left.\""],
        turnIn: ["\"A botnet fridge. Of course.\"", "\"Report filed. None of them meant harm — that's rather the point, isn't it?\""] },
    ],
    reward: { money: 800, items: { piward: 2 } },
    done: ["\"The baker uninstalled it herself. Progress.\""],
  },
  clickfix_towpath: {
    name: "Flyers on the Towpath",
    offer: ["BOATMAN: Some sect's been stapling 'fix your monster in one paste' flyers along the canal.",
            "Old Ned actually pasted it. His NIBBIT spent an hour singing sea shanties in binary.",
            "One of them is still preaching on Route 1. Send them packing?"],
    stages: [
      { objective: "Defeat the ClickFix Cultist on Route 1.", cond: { defeated: "clickfix1" },
        remind: ["\"Still out there, stapling.\""],
        turnIn: ["\"That's the last flyer, then. The canal thanks you.\""] },
    ],
    reward: { money: 600, items: { berry: 4 } },
    done: ["\"Ned's NIBBIT is back on sea shanties in plain English. As nature intended.\""],
  },
  deepfake: {
    name: "The Vicar's Double",
    offer: ["MARGARET: There's a video going round of our vicar asking for donations in — what is it — 'ClopCoin'.",
            "It LOOKS like him. It BLINKS like him. But the vicar has never once been interesting on camera.",
            "Would you check on the real one?"],
    stages: [
      { objective: "Speak to the real vicar in Prestbury.", cond: { flag: "vicar_ok" },
        remind: ["\"He'll be by the church, being reassuringly dull.\""],
        turnIn: ["\"Genuinely his? Oh thank heavens.\"", "\"I shall tell the parish group chat. Carefully.\""] },
    ],
    reward: { money: 500 },
    done: ["\"We verify everything now. Even the flower rota.\""],
  },
  stuffers101: {
    name: "Twelve Thousand Accounts",
    offer: ["GYM TRAINEE: There's a stuffer working Route 3 under cover of that horrid fog.",
            "Twelve thousand puppet accounts, ADA reckons. All of them terribly weak. All of them ANNOYING.",
            "Thin the herd?"],
    stages: [
      { objective: "Defeat the Credential Stuffer on Route 3.", cond: { defeated: "stuffer_swarm" },
        remind: ["\"The fog's still full of puppets.\""],
        turnIn: ["\"All twelve thousand burned? ADA says you rate-limited him PERSONALLY.\""] },
    ],
    reward: { items: { greatcapsule: 5 } },
    done: ["\"The fog's lifting on Route 3. Mostly.\""],
  },
  wizardcat: {
    name: "The Wizard's Cat",
    offer: ["KEEPER: A thousand years the wizard's cat has slept beneath the Edge.",
            "It stirs. The rogue signal reached even here.", "Face MERLYNX. Settle it, one way or the other."],
    stages: [
      { objective: "Confront MERLYNX in the Edge Caverns.", cond: { flag: "merlynxGone" },
        remind: ["\"The deep cavern. Bring courage.\""],
        turnIn: ["\"So the legend closes its eyes again.\"", "\"Take the charm. You've earned a little of the Edge's luck.\""] },
    ],
    reward: { money: 1500, items: { charm: 1 } },
    done: ["\"The Edge sleeps sound. So do I, for once.\""],
  },
  alsu: {
    name: "Letters from Alsu",
    offer: ["POSTMISTRESS: Post for a 'JIM of Macclesfield'? Foreign stamp. Georgia — the country, dear, not the state.",
            "Sender's one Alsu. There's a note saying two more letters follow you up the line."],
    accepted: ["Received LETTER FROM ALSU.", "\"She writes a lovely hand, whoever she is.\""],
    stages: [
      { objective: "Collect the second letter at Crewe.", cond: {},
        remind: ["\"On you go.\""], give: "letter1",
        turnIn: ["CREWE CLERK: Another letter for the walking SOC. Here.", "Received LETTER FROM ALSU (2)."] },
      { objective: "Collect the third letter in Chester.", cond: {}, give: "letter2",
        remind: ["\"One more stop, the note says. Chester.\""],
        turnIn: ["ILZE: You're Jim? Alsu wrote ahead. (You reply in Russian; she blinks, then laughs.)",
                 "\"A Tatar accent! In CHESTER! She said I'd know you by it.\"",
                 "\"The last letter. And she sent this for you to keep.\"", "Received LETTER FROM ALSU (3)."] },
    ],
    reward: { items: { teaset: 1, letter3: 1 }, money: 2000 },
    done: ["ILZE: Write back to her. Paper survives everything — Riga taught me that."],
  },
  herbalist: {
    name: "Five Good Berries",
    offer: ["HERBALIST: The day-care monsters need proper food, not pellets.",
            "Five berries, any hedge you like. I pay in something better."],
    stages: [
      { objective: "Bring 5 berries.", cond: { item: ["berry", 5] },
        remind: ["\"Hedgerows, dear. They regrow if you're patient.\""],
        turnIn: ["\"Lovely, fat ones too.\"", "\"Perry and a stout from my own press. Vegetarian, all of it, before you ask.\""] },
    ],
    reward: { items: { perry: 2, stout: 1 } },
    done: ["\"The little ones are thriving. Come see them.\""],
  },
  bearclub: {
    name: "Bear Necessities",
    offer: ["KID: Congleton's THE bear town but I've never SEEN a proper big one!",
            "Show me a BROCKLORD! The really grumpy badger-bear! Pleeeease!"],
    stages: [
      { objective: "Have a BROCKLORD in your team and come back.", cond: { partyHas: "brocklord" },
        remind: ["\"BROCKLET evolves! Route 8 has loads!\""],
        turnIn: ["\"IT'S SO GRUMPY AND HUGE!\"", "\"Best day EVER!\""] },
    ],
    reward: { money: 900 },
    done: ["\"I'm going to be a bearward like OTIS when I grow up.\""],
  },
  amosarcade: {
    name: "The Kiosk That Lies",
    offer: ["OWNER: Someone wheeled a 'retro high-score kiosk' in last week. I never ordered it.",
            "It asks the kids for their storage passwords 'to save progress'.",
            "It also HISSES at me. Deal with it?"],
    stages: [
      { objective: "Defeat the AMOS shapeshifter posing as a kiosk.", cond: { defeated: "amos_arcade" },
        remind: ["\"It's still there. Hissing. Pretending to be Space Invaders.\""],
        turnIn: ["\"It just... dissolved? And took its little skimmer with it.\"", "\"Drinks on the house. Metaphorically. Have money.\""] },
    ],
    reward: { money: 1200, items: { ultracapsule: 1 } },
    done: ["\"New rule: I buy my own machines.\""],
  },
  signalghost: {
    name: "The Signal Box Ghost",
    offer: ["STATIONMASTER: Platform 3's signal box throws itself to danger at 2am. Every night. No hand on the lever.",
            "The lads say MANORWRAITH. I say prove it — catch one and show me they're real."],
    stages: [
      { objective: "Catch a MANORWRAITH (Route 15 and the northern hills).", cond: { caught: "manorwraith" },
        remind: ["\"2am again last night. I've started saying goodnight to it.\""],
        turnIn: ["\"So they ARE real. And ours just likes the night shift.\"", "\"We've put it on the roster. Union's fine with it.\""] },
    ],
    reward: { items: { hyperpotion: 3 } },
    done: ["\"Best signaller we've ever had. Never sleeps.\""],
  },
  brinebaths: {
    name: "Trouble at the Baths",
    offer: ["ATTENDANT: A man in the brine pool claims nine thousand memberships. NINE THOUSAND.",
            "All named 'user123_' something. He is very smug and will not leave the shallow end."],
    stages: [
      { objective: "Defeat the Credential Stuffer on Route 11.", cond: { defeated: "stuffer_nant" },
        remind: ["\"Still in the shallow end. Still smug.\""],
        turnIn: ["\"He's gone! Took his nine thousand towels with him.\""] },
    ],
    reward: { money: 1000 },
    done: ["\"The pool's back to people with one name each. Bliss.\""],
  },
  saltworks: {
    name: "Lion Salt Works",
    offer: ["HISTORIAN: The old open-pan works needs a living exhibit.",
            "A CRYSSAL — genuine walking rock salt. Catch one and the display writes itself."],
    stages: [
      { objective: "Catch a CRYSSAL (salt country routes).", cond: { caught: "cryssal" },
        remind: ["\"Route 12, 13, the mine. Anywhere the ground tastes salty.\""],
        turnIn: ["\"Magnificent specimen! The schoolchildren will be delighted and mildly terrified.\""] },
    ],
    reward: { money: 800, items: { greatcapsule: 2 } },
    done: ["\"Visitor numbers doubled. The CRYSSAL has a fan club.\""],
  },
  weisssensor: {
    name: "Dr. Weiss's Sensor",
    offer: ["DR. WEISS: Entschuldigung — my English... ah. (You switch to German. His shoulders drop with relief.)",
            "\"Endlich! I need the summit logger from the Frodsham hill warden. Air quality, particulates, everything.\"",
            "\"The plant says the air is fine. I would like the AIR's opinion.\""],
    stages: [
      { objective: "Collect the sensor data from the Frodsham hill warden.", cond: { flag: "hillsensor" },
        remind: ["\"The warden walks the summit path. Danke.\""],
        turnIn: ["\"Perfekt. Und — the readings are... interesting.\"", "\"The datacentre draws more than the whole works. Someone should look at that. Someone like you, ja?\""] },
    ],
    reward: { items: { ultracapsule: 2 } },
    done: ["\"I publish next month. Wish me luck with the lawyers.\""],
  },
  wirefraud: {
    name: "Wire Fraud",
    offer: ["MO'S AIDE: Two ClickFix preachers set up on Route 16. On WIRE TOWN'S doorstep.",
            "MO would flatten them personally but she's mid-audit. Would you?"],
    stages: [
      { objective: "Defeat the first cultist on Route 16.", cond: { defeated: "clickfix2" },
        remind: ["\"First one's near the west end.\""], turnIn: ["\"One down.\""] },
      { objective: "Defeat the second cultist on Route 16.", cond: { defeated: "clickfix3" },
        remind: ["\"The other one's further along.\""],
        turnIn: ["\"Both gone. MO says, quote, 'acceptable throughput'.\"", "\"From her that's a medal.\""] },
    ],
    reward: { money: 1500 },
    done: ["\"Route 16's DNS is clean again.\""],
  },
  zooescape: {
    name: "The Penguin Situation",
    offer: ["KEEPER: One of our PENGWYN has gone walkabout. Again.",
            "It swims the ship canal to Ellesmere Port and 'helps' the anglers.",
            "If you can catch it — gently! — the enclosure's the better for it. Or honestly, it seems to like you people. Keep it."],
    stages: [
      { objective: "Catch a PENGWYN (canal waters, north of the zoo).", cond: { caught: "pengwyn" },
        remind: ["\"Try fishing the canal at Anderton or Ellesmere Port.\""],
        turnIn: ["\"That's the one! Look at its smug little face.\"", "\"It's clearly chosen you. The paperwork is... let's say flexible.\""] },
    ],
    reward: { money: 2000 },
    done: ["\"Visitors keep asking where the escape artist went. I say: on tour.\""],
  },
  stagcount: {
    name: "The Stag Census",
    offer: ["RANGER: Annual deer census. A thousand acres, one ranger, no chance.",
            "Catch me a PARKSTAG to tag and release — the herd follows where one leads."],
    stages: [
      { objective: "Catch a PARKSTAG in Tatton Park.", cond: { caught: "parkstag" },
        remind: ["\"They graze the open meadow. Walk soft.\""],
        turnIn: ["\"Tagged, noted, released. The herd's already following it about.\"", "\"Census done by teatime. You're welcome back any season.\""] },
    ],
    reward: { money: 1100, items: { berry: 5 } },
    done: ["\"Herd's healthy. 847 head, if you're curious. I count fast now.\""],
  },
  liftlore: {
    name: "Cathedral of the Canals",
    offer: ["KEEPER: The lift's hydraulics groan like something's living in the caisson.",
            "Probably eels. Possibly not eels. Fish the basin and tell me what's down there?"],
    stages: [
      { objective: "Catch a VOLTEEL or PHISHFIN from the Anderton basin.", cond: { caught: "volteel" },
        remind: ["\"The basin, when the light's low.\""],
        turnIn: ["\"A VOLTEEL in the workings! That explains the voltage on the handrails.\"", "\"The lift thanks you. Insurance thanks you MORE.\""] },
    ],
    reward: { money: 1200 },
    done: ["\"Groaning's stopped. I almost miss it.\""],
  },
  millmemory: {
    name: "What the Mill Remembers",
    offer: ["HISTORIAN: Quarry Bank ran on child apprentices once. We tell that story honestly now.",
            "Someone's been projecting AI 'restorations' of the apprentices onto the looms. Smiling. Grateful. FALSE.",
            "Find the projector — some CYBER creature is generating them. Clear it out."],
    stages: [
      { objective: "Defeat or catch a LOOMOTH near Styal (it nests in the mill's eaves).", cond: { caught: "loomoth" },
        remind: ["\"The eaves, the looms, Route 21. It glows at dusk.\""],
        turnIn: ["\"So it wasn't malice. Just a moth that learned to project what people wanted to see.\"",
                 "\"We'll show the real faces. They deserve better than a smiling filter.\""] },
    ],
    reward: { money: 1400, items: { stout: 1 } },
    done: ["\"The exhibition reopens Friday. Unretouched.\""],
  },
  orchard: {
    name: "Y Berllan",
    offer: ["MAM-GU: (She looks up from the press and speaks in Welsh — the old, quick kind.)",
            "\"Wel, Jim bach! Adref o'r diwedd!\" — home at last, she says, as if you left yesterday.",
            "\"The orchard's heavy this year. Bring me six berries and we'll press properly, fel yr hen ddyddiau.\""],
    stages: [
      { objective: "Bring MAM-GU 6 berries.", cond: { item: ["berry", 6] },
        remind: ["\"Chwech, bach. Six. The bushes by the well are best.\""],
        turnIn: ["She works the elm screw like it weighs nothing. A century of hands have polished the grain.",
                 "\"Da iawn. Your grandfather built ships of paper and lodges of stone — but THIS is the family engine.\"",
                 "\"Take these. And come home more often, cariad.\""] },
    ],
    reward: { items: { perry: 2, stout: 2 } },
    done: ["\"Cofion at y cathod — regards to the cats, bach.\""],
  },
};
