// Hand-crafted town overlays — generated by the town design pass.
// Loaded after maps.js; replaces factory-generated town layouts with
// landmark-faithful designs. Placeholder until the design pass lands.
