// MonsterQuest v2 service worker — precache everything for offline play.
// ASSETS and CACHE are regenerated by tools/gen-index.js.
const CACHE = "mq2-1";
const ASSETS = [
  ".",
  "index.html",
  "manifest.webmanifest",
  "css/style.css",
  "js/core/ns.js",
  "js/core/util.js",
  "js/core/events.js",
  "js/core/view.js",
  "js/core/input.js",
  "js/core/loop.js",
  "js/core/scene.js",
  "js/core/text.js",
  "js/core/ui.js",
  "js/core/dialog.js",
  "js/core/script.js",
  "js/core/flags.js",
  "js/core/clock.js",
  "js/core/save.js",
  "js/core/registry.js",
  "js/art/sprites.js",
  "js/art/tiles.js",
  "js/art/monsters.js",
  "js/art/people.js",
  "js/art/fx.js",
  "js/audio/audio.js",
  "js/audio/songs.js",
  "js/audio/sfx.js",
  "js/data/types.js",
  "js/data/moves.js",
  "js/data/abilities.js",
  "js/data/items.js",
  "js/data/species.js",
  "js/data/encounters_east.js",
  "js/data/trainers_east.js",
  "js/data/dialogue.js",
  "js/world/mapformat.js",
  "js/world/npc.js",
  "js/world/interact.js",
  "js/world/encounters.js",
  "js/world/overworld.js",
  "js/world/maps/_demo.js",
  "js/world/maps/east__build.js",
  "js/world/maps/east_bollington.js",
  "js/world/maps/east_macclesfield.js",
  "js/world/maps/east_routes.js",
  "js/battle/effects.js",
  "js/battle/ai.js",
  "js/battle/engine.js",
  "js/battle/scene.js",
  "js/content/achievements-engine.js",
  "js/content/cats.js",
  "js/content/daycare.js",
  "js/content/progression.js",
  "js/content/quests-engine.js",
  "js/content/state.js",
  "js/ui/bag.js",
  "js/ui/party.js",
  "js/ui/pause.js",
  "js/ui/save.js",
  "js/ui/settings.js",
  "js/ui/shop.js",
  "js/ui/theme.js",
  "js/ui/title.js",
  "js/story/main.js",
  "js/boot.js",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).then((res) => {
        if (res.ok && new URL(e.request.url).origin === location.origin) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy));
        }
        return res;
      }).catch(() => {
        if (e.request.mode === "navigate") return caches.match("index.html");
        throw new Error("offline");
      });
    })
  );
});
