// MonsterQuest v2 service worker — precache everything for offline play.
// ASSETS and CACHE are regenerated by tools/gen-index.js.
const CACHE = "mq2-1";
const ASSETS = [
  ".",
  "index.html",
  "manifest.webmanifest",
  "css/style.css",
  "js/core/ns.js",
  "js/core/util.js",
  "js/core/events.js",
  "js/core/view.js",
  "js/core/input.js",
  "js/core/loop.js",
  "js/core/scene.js",
  "js/core/text.js",
  "js/core/ui.js",
  "js/core/dialog.js",
  "js/core/script.js",
  "js/core/flags.js",
  "js/core/clock.js",
  "js/core/save.js",
  "js/core/registry.js",
  "js/art/sprites.js",
  "js/art/tiles.js",
  "js/art/monsters.js",
  "js/art/people.js",
  "js/art/fx.js",
  "js/audio/audio.js",
  "js/audio/songs.js",
  "js/audio/sfx.js",
  "js/data/types.js",
  "js/data/moves.js",
  "js/data/abilities.js",
  "js/data/items.js",
  "js/data/species.js",
  "js/data/encounters_east.js",
  "js/data/encounters_mid.js",
  "js/data/encounters_sw.js",
  "js/data/trainers_east.js",
  "js/data/trainers_mid.js",
  "js/data/trainers_sw.js",
  "js/data/quests_east.js",
  "js/data/quests_mid.js",
  "js/data/quests_sw.js",
  "js/data/achievements.js",
  "js/data/dialogue.js",
  "js/world/mapformat.js",
  "js/world/npc.js",
  "js/world/interact.js",
  "js/world/encounters.js",
  "js/world/overworld.js",
  "js/world/maps/_demo.js",
  "js/world/maps/east__build.js",
  "js/world/maps/east_alderley.js",
  "js/world/maps/east_bollington.js",
  "js/world/maps/east_lindow.js",
  "js/world/maps/east_lyme.js",
  "js/world/maps/east_macclesfield.js",
  "js/world/maps/east_poynton.js",
  "js/world/maps/east_prestbury.js",
  "js/world/maps/east_routes.js",
  "js/world/maps/east_styal.js",
  "js/world/maps/east_teggs.js",
  "js/world/maps/east_wilmslow.js",
  "js/world/maps/mid__build.js",
  "js/world/maps/mid_congleton.js",
  "js/world/maps/mid_crewe.js",
  "js/world/maps/mid_holmes.js",
  "js/world/maps/mid_jodrell.js",
  "js/world/maps/mid_knutsford.js",
  "js/world/maps/mid_moreton.js",
  "js/world/maps/mid_routes.js",
  "js/world/maps/mid_sandbach.js",
  "js/world/maps/mid_tatton.js",
  "js/world/maps/mid_zlinks.js",
  "js/world/maps/sw__build.js",
  "js/world/maps/sw_anderton.js",
  "js/world/maps/sw_borders.js",
  "js/world/maps/sw_hackgreen.js",
  "js/world/maps/sw_middlewich.js",
  "js/world/maps/sw_nantwich.js",
  "js/world/maps/sw_northwich.js",
  "js/world/maps/sw_routes.js",
  "js/world/maps/sw_saltmine.js",
  "js/world/maps/sw_winsford.js",
  "js/world/maps/sw_yberllan.js",
  "js/battle/effects.js",
  "js/battle/ai.js",
  "js/battle/engine.js",
  "js/battle/scene.js",
  "js/content/achievements-engine.js",
  "js/content/arena.js",
  "js/content/bounties.js",
  "js/content/brewing.js",
  "js/content/cats.js",
  "js/content/daycare.js",
  "js/content/fishing.js",
  "js/content/minigames.js",
  "js/content/photo.js",
  "js/content/progression.js",
  "js/content/quests-engine.js",
  "js/content/rematch.js",
  "js/content/shrine.js",
  "js/content/state.js",
  "js/ui/bag.js",
  "js/ui/casebook.js",
  "js/ui/dex.js",
  "js/ui/hud.js",
  "js/ui/party.js",
  "js/ui/pause.js",
  "js/ui/perks.js",
  "js/ui/save.js",
  "js/ui/settings.js",
  "js/ui/shop.js",
  "js/ui/theme.js",
  "js/ui/title.js",
  "js/ui/trainercard.js",
  "js/ui/worldmap.js",
  "js/story/main.js",
  "js/story/npcs_east.js",
  "js/story/npcs_mid.js",
  "js/story/npcs_sw.js",
  "js/story/chapters/ch01_silk_and_static.js",
  "js/story/chapters/ch02_the_wheel_and_the_edge.js",
  "js/story/chapters/ch03_picnic_blankets.js",
  "js/story/chapters/ch04_the_dish_goes_dark.js",
  "js/story/chapters/ch05_puppets_on_the_line.js",
  "js/story/chapters/ch06_brine_and_perry.js",
  "js/story/chapters/ch07_salt.js",
  "js/boot.js",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Own files are network-first so a reload always lands on the newest build;
// the cache is the offline fallback, not the source of truth. Anything from
// another origin stays cache-first.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  let sameOrigin = false;
  try { sameOrigin = new URL(e.request.url).origin === location.origin; } catch (err) { sameOrigin = false; }

  const fromCache = () => caches.match(e.request, { ignoreSearch: true }).then((hit) => {
    if (hit) return hit;
    if (e.request.mode === "navigate") return caches.match("index.html");
    throw new Error("offline");
  });

  if (!sameOrigin) { e.respondWith(fromCache()); return; }

  e.respondWith(
    fetch(e.request).then((res) => {
      if (res && res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {});
      }
      return res;
    }).catch(fromCache)
  );
});
